// СГЕНЕРИРОВАНО scripts/convert-codes.mjs — официальный реестр item_codes.py (396 записей)
export type RegistryCategory = "Предметы" | "Боеприпасы" | "Материалы" | "Оружие" | "Техника" | "Сооружения" | "Снаряжение" | "Другое";
export type RegistryFaction = "Колонисты" | "Варден" | "Нейтральные";

export interface RegistryEntry {
  code: string;
  nameEn: string;
  nameRu: string;
  iconCode: string;
  icon: string | null;
  category: RegistryCategory;
  faction: RegistryFaction;
  review: boolean;
}

export const REGISTRY_CATEGORIES: RegistryCategory[] = ["Предметы", "Боеприпасы", "Материалы", "Оружие", "Техника", "Сооружения", "Снаряжение", "Другое"];
export const REGISTRY_FACTIONS: RegistryFaction[] = ["Колонисты", "Варден", "Нейтральные"];

export const CODE_REGISTRY: RegistryEntry[] = [
  { code: "AAAmmo", nameEn: "950-70b Anti-Aircraft Shell", nameRu: "Зенитный снаряд 950-70b", iconCode: "AAAmmoIcon.webp", icon: "AAAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "AAGunAI", nameEn: "Anti-Air Gun", nameRu: "Anti-Air Gun", iconCode: "Anti-Air_Gun.jpg", icon: "Anti-Air_Gun.jpg", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "ATAmmo", nameEn: "68mm", nameRu: "68-мм", iconCode: "ATAmmoIcon.webp", icon: "ATAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "ATGrenadeW", nameEn: "BF5 White Ash Flask Grenade", nameRu: "Граната BF5 White Ash Flask", iconCode: "ATGrenadeWIcon.webp", icon: "ATGrenadeW.webp", category: "Боеприпасы", faction: "Варден", review: false },
  { code: "ATLargeAmmo", nameEn: "94.5mm", nameRu: "94.5мм снаряды", iconCode: "ATLargeAmmoIcon.webp", icon: "ATLargeAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "ATLaunchedGrenadeW", nameEn: "B2 Varsi Anti-Tank Grenade", nameRu: "B2 Varsi Anti-Tank Grenade", iconCode: "ATLaunchedGrenadeWIcon.webp", icon: "ATLaunchedGrenadeW.webp", category: "Боеприпасы", faction: "Варден", review: false },
  { code: "ATRPGAmmo", nameEn: "AP⧸RPG", nameRu: "АРПГ Снаряды", iconCode: "ATRPGAmmoIcon.webp", icon: "ATRpgAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "ATRPGC", nameEn: "Venom c.II 35", nameRu: "Venom c.II 35", iconCode: "ATRPGCIcon.webp", icon: "ATRpgC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "ATRPGHeavyC", nameEn: "Bane 45", nameRu: "Bane 45", iconCode: "ATRpgC.webp", icon: "ATRpgC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "ATRPGIndirectAmmo", nameEn: "ARC⧸RPG", nameRu: "ARC⧸RPG", iconCode: "ATMortarAmmo.webp", icon: "ATMortarAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "ATRPGLightC", nameEn: "Ignifist 30", nameRu: "Ignifist 30", iconCode: "ATRPGLightCIcon.webp", icon: "ATRPGLightC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "ATRPGTW", nameEn: "Mounted Bonesaw MK.3", nameRu: "Mounted Bonesaw MK.3", iconCode: "ATRPGTWIcon.webp", icon: "ATRPGTW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "ATRPGW", nameEn: "Bonesaw MK.3", nameRu: "Противотанковый РПГ (станковый)", iconCode: "ATRPGWIcon.webp", icon: null, category: "Оружие", faction: "Варден", review: true },
  { code: "ATRifleAmmo", nameEn: "14.5mm", nameRu: "14.5 мм", iconCode: "ATRifleAmmoIcon.webp", icon: "ATRifleAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "ATRifleAssaultW", nameEn: "228 Satterley Heavy Storm Rifle", nameRu: "228 Satterley Heavy Storm Rifle", iconCode: "ATRifleAssaultWtga.webp", icon: "ATRifleAssaultWtga.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "ATRifleAutomaticW", nameEn: "Booker Greyhound Model 910", nameRu: "Booker Greyhound Model 910", iconCode: "ATRifleAutomaticWIcon.webp", icon: "ATRifleAutomaticW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "ATRifleLightC", nameEn: "“Dawn” Ve.II", nameRu: "“Dawn” Ve.II", iconCode: "ATRifleLightCIcon.webp", icon: "ATRifleLightC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "ATRifleSniperC", nameEn: "“Quickhatch” Rt.I", nameRu: "“Quickhatch” Rt.I", iconCode: "ATRifleSniperCtga.webp", icon: "ATRifleSniperCtga.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "ATRifleTC", nameEn: "“Typhon” ra.XII", nameRu: "“Typhon” ra.XII", iconCode: "ATRifleTCIcon.webp", icon: "ATRifleTC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "ATRifleW", nameEn: "Neville Anti-Tank Rifle", nameRu: "противотанковое ружье 20мм", iconCode: "ATRifleWIcon.webp", icon: null, category: "Оружие", faction: "Варден", review: true },
  { code: "AirSirenT", nameEn: "Air Raid Siren", nameRu: "Air Raid Siren", iconCode: "AirSirenTIcon.webp", icon: "AirSirenT.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "AircraftAmmo", nameEn: "20mm", nameRu: "20мм", iconCode: "AircraftAmmoIcon.webp", icon: "AircraftAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "AircraftBomberC", nameEn: "V-1 Tzykalia", nameRu: "V-1 Tzykalia", iconCode: "AircraftBomberC.webp", icon: "AircraftBomberC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "AircraftBomberW", nameEn: "Tulka P4 Welkinrive", nameRu: "Tulka P4 Welkinrive", iconCode: "AircraftBomberW.webp", icon: "AircraftBomberW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "AircraftDepot", nameEn: "Aircraft Depot", nameRu: "Aircraft Depot", iconCode: "AircraftDepot.png", icon: "AircraftDepot.png", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "AircraftDiveC", nameEn: "Mergo-4 “Myrmidon”", nameRu: "Mergo-4 “Myrmidon”", iconCode: "AircraftDiveC.webp", icon: "AircraftDiveC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "AircraftFactory", nameEn: "Aircraft Hangar", nameRu: "Aircraft Hangar", iconCode: "AircraftFactory.webp", icon: "AircraftFactory.webp", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "AircraftFighterC", nameEn: "Toxot-902 “Blind Silver”", nameRu: "Toxot-902 “Blind Silver”", iconCode: "AircraftFigtherC.webp", icon: "AircraftFigtherC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "AircraftFighterW", nameEn: "Luminary Mk. II Harbinger", nameRu: "Luminary Mk. II Harbinger", iconCode: "AircraftFighterWIcon.webp", icon: "AircraftFighterWIcon.webp", category: "Техника", faction: "Варден", review: false },
  { code: "AircraftParatrooperC", nameEn: "V-5b Pegasus", nameRu: "V-5b Pegasus", iconCode: "AircraftParatrooperCIcon.webp", icon: "AircraftParatrooperCIcon.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "AircraftParatrooperW", nameEn: "Rinnspeir Mk. I Zealot", nameRu: "Rinnspeir Mk. I Zealot", iconCode: "AircraftParatrooperWIcon.webp", icon: "AircraftParatrooperWIcon.webp", category: "Техника", faction: "Варден", review: false },
  { code: "AircraftScout2C", nameEn: "A59 Venti “Perdix”", nameRu: "A59 Venti “Perdix”", iconCode: "AircraftScout2CIcon.webp", icon: "AircraftScout2CIcon.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "AircraftScout2W", nameEn: "Luminary Mk. VI Emissary", nameRu: "Luminary Mk. VI Emissary", iconCode: "AircraftScout2WIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "AircraftScoutC", nameEn: "A51 Venti “Daedalus”", nameRu: "A51 Venti “Daedalus”", iconCode: "AircraftScoutCIcon.webp", icon: "AircraftScoutCIcon.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "AircraftScoutW", nameEn: "Luminary Mk. IV Herald", nameRu: "Luminary Mk. IV Herald", iconCode: "AircraftScoutWIcon.webp", icon: "AircraftScoutWIcon.webp", category: "Техника", faction: "Варден", review: false },
  { code: "AircraftTorpedoAmmo", nameEn: "Tenta Torpedo", nameRu: "Tenta Torpedo", iconCode: "AircraftTorpedoAmmoIcon.webp", icon: "AircraftTorpedoAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "AircraftTorpedoW", nameEn: "M925 Austringer Man-O-War", nameRu: "M925 Austringer Man-O-War", iconCode: "AircraftTorpedoWIcon.webp", icon: "AircraftTorpedoWIcon.webp", category: "Техника", faction: "Варден", review: false },
  { code: "AircraftWaterW", nameEn: "Tulka I1.9 White Raven", nameRu: "Tulka I1.9 White Raven", iconCode: "AircraftWaterWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "Aluminum", nameEn: "Aluminum", nameRu: "Aluminum", iconCode: "ResouceAluminumIcon.png", icon: "ResouceAluminumIcon.png", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "AluminumA", nameEn: "Aluminum Alloy", nameRu: "Алюминий", iconCode: "AluminumAIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "AmbulanceC", nameEn: "R-12 - “Salus” Ambulance", nameRu: "R-12 - “Salus” Ambulance", iconCode: "Ambulance.webp", icon: "Ambulance.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "AmbulanceFlameC", nameEn: "R-12b - “Salva” Flame Truck", nameRu: "R-12b - “Salva” Flame Truck", iconCode: "AmbulanceFlameCIcon.webp", icon: "AmbulanceFlameC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "AmbulanceFlameW", nameEn: "Dunne Dousing Engine 3r", nameRu: "пожарная машина", iconCode: "AmbulanceFlameWIcon.webp", icon: "AmbulanceFlameW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "AmbulanceW", nameEn: "Dunne Responder 3e", nameRu: "скорая помощь", iconCode: "AmbulanceWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "AmmoUniformW", nameEn: "Specialist's Overcoat", nameRu: "шинель специалиста", iconCode: "AmmoUniformWIcon.webp", icon: "AmmoUniformW.webp", category: "Боеприпасы", faction: "Варден", review: false },
  { code: "ArmoredCar2LargeW", nameEn: "O'Brien V.101 Freeman", nameRu: "бронированная дюна", iconCode: "ArmoredCarOffensiveWVehicleW.webp", icon: "ArmoredCarOffensiveWVehicleW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "ArmoredCar2MultiW", nameEn: "O'Brien V.200 Squire", nameRu: "O'Brien V.200 Squire", iconCode: "ArmoredCar2MultiWIcon.webp", icon: "ArmoredCar2MultiW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "ArmoredCar2TwinW", nameEn: "O'Brien V.190 Knave", nameRu: "O'Brien V.101 Freeman / Twin AC", iconCode: "ArmoredCar2TwinWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "ArmoredCarATW", nameEn: "O'Brien V.113 Gravekeeper", nameRu: "O'Brien V.113 Gravekeeper", iconCode: "ArmoredCarATWVehicleIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "ArmoredCarC", nameEn: "T3 “Xiphos”", nameRu: "T3 “Xiphos”", iconCode: "ArmoredCarVehicleC.webp", icon: "ArmoredCarVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "ArmoredCarFlameW", nameEn: "O'Brien V.130 Wild Jack", nameRu: "Бронеавтомобиль с огнемётом", iconCode: "ArmoredCarFlameWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "ArmoredCarMobilityW", nameEn: "O'Brien V.121 Highlander", nameRu: "Мобильная бронемашина", iconCode: "ArmoredCarMobilityWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "ArmoredCarOffensiveC", nameEn: "T5 “Percutio”", nameRu: "T5 “Percutio”", iconCode: "ArmoredCarOffensiveCVehicleC.webp", icon: "ArmoredCarOffensiveCVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "ArmoredCarTwinC", nameEn: "T8 “Gemini”", nameRu: "T8 “Gemini”", iconCode: "ArmoredCarTwinCIcon.webp", icon: "ArmoredCarTwinC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "ArmoredCarW", nameEn: "O'Brien V.110", nameRu: "O", iconCode: "ArmoredCarWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "ArmourUniformC", nameEn: "Velian Flak Vest", nameRu: "Velian Flak Vest", iconCode: "ArmourUniformCIcon.webp", icon: "ArmourUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "ArmourUniformW", nameEn: "Gunner's Breastplate", nameRu: "Стальная кираса", iconCode: "ArmourUniformWIcon.webp", icon: "ArmourUniformW.webp", category: "Материалы", faction: "Варден", review: false },
  { code: "AssaultRifleAmmo", nameEn: "7.92mm", nameRu: "7.92-мм", iconCode: "AssaultRifleAmmoIcon.webp", icon: "AssaultRifleAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "AssaultRifleC", nameEn: "Catara mo.II", nameRu: "Catara mo.II", iconCode: "LightMachineGun.webp", icon: "LightMachineGun.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "AssaultRifleHeavyC", nameEn: "“Dusk” ce.III", nameRu: "“Dusk” ce.III", iconCode: "AssaultRifleHeavyCIcon.webp", icon: "AssaultRifleHeavyC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "AssaultRifleHeavyW", nameEn: "Booker Storm Rifle Model 838", nameRu: "Booker Storm Rifle Model 838", iconCode: "AssaultRifleHeavyWItem.webp", icon: "AssaultRifleHeavyWItem.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "AssaultRifleW", nameEn: "Aalto Storm Rifle 24", nameRu: "Aalto Storm Rifle 24", iconCode: "AssaultRifleItem.webp", icon: "AssaultRifleItem.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "Bandages", nameEn: "Bandages", nameRu: "бинт", iconCode: "BandagesIcon.webp", icon: "Bandages.webp", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "BannerTW", nameEn: "War Ensign", nameRu: "War Ensign", iconCode: "BannerTWItemIcon.webp", icon: "BannerTWItemIcon.webp", category: "Снаряжение", faction: "Варден", review: false },
  { code: "BarbedWireMaterials", nameEn: "Barbed Wire", nameRu: "колючая проволока", iconCode: "BarbedWireMaterialsIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "Barge", nameEn: "BMS - Aquatipper", nameRu: "баржа", iconCode: "BargeIcon.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "BattleTankATC", nameEn: "Lance-25 “Hasta”", nameRu: "Lance-25 “Hasta”", iconCode: "BattleTankATCIcon.webp", icon: "BattleTankATC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "BattleTankAmmo", nameEn: "75mm", nameRu: "75mm", iconCode: "BattleTankAmmoIcon.webp", icon: "BattleTankAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "BattleTankC", nameEn: "Lance-36", nameRu: "Lance-36", iconCode: "BattleTankCIcon.webp", icon: "BattleTankC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "BattleTankDefensiveW", nameEn: "Flood Juggernaut Mk. VII", nameRu: "Flood Juggernaut Mk. VII", iconCode: "BattleTankWarDefensiveVehicle.webp", icon: "BattleTankWarDefensiveVehicle.webp", category: "Техника", faction: "Варден", review: false },
  { code: "BattleTankHeavyArtilleryC", nameEn: "Lance-46 “Sarissa”", nameRu: "Lance-46 “Sarissa”", iconCode: "BattleTankHeavyArtilleryCIcon.webp", icon: "BattleTankHeavyArtilleryC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "BattleTankHeavyArtilleryW", nameEn: "Flood Mk. IX Stain", nameRu: "Flood Mk. IX Stain", iconCode: "BattleTankHeavyArtilleryWIcon.webp", icon: "BattleTankHeavyArtilleryW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "BattleTankW", nameEn: "Flood Mk. I", nameRu: "Flood Mk. I", iconCode: "BattleTankWar.webp", icon: "BattleTankWar.webp", category: "Техника", faction: "Варден", review: false },
  { code: "Bayonet", nameEn: "Buckhorn CCQ-18", nameRu: "штык-нож", iconCode: "BayonetIcon.webp", icon: "Bayonet.webp", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "Bicycle", nameEn: "Blumfield LK205", nameRu: "Blumfield LK205", iconCode: "RelicBicycleVehicle.webp", icon: "RelicBicycleVehicle.webp", category: "Техника", faction: "Нейтральные", review: false },
  { code: "Binoculars", nameEn: "Binoculars", nameRu: "бинокль", iconCode: "BinocularsIcon.webp", icon: "Binoculars.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "BloodPlasma", nameEn: "Blood Plasma", nameRu: "Плазма", iconCode: "BloodPlasmaIcon.webp", icon: "BloodPlasma.webp", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "BomberAmmo", nameEn: "Mark II Raidbreaker", nameRu: "Mark II Raidbreaker", iconCode: "AerialBombsIcon.webp", icon: "AerialBombs.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "BusC", nameEn: "R-15 - “Chariot”", nameRu: "R-15 - “Chariot”", iconCode: "BusCIcon.webp", icon: "BusC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "BusW", nameEn: "Dunne Caravaner 2f", nameRu: "автобус", iconCode: "BusWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "Cloth", nameEn: "Basic Materials", nameRu: "Базовые материалы", iconCode: "ClothIcon.webp", icon: "Cloth.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "Coal", nameEn: "Coal", nameRu: "Coal", iconCode: "CoalIcon.webp", icon: "CoalIcon.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "Components", nameEn: "Components", nameRu: "Компоненты", iconCode: "ComponentsIcon.webp", icon: "ComponentsIcon.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "Concrete", nameEn: "Concrete Materials", nameRu: "Concrete Materials", iconCode: "ConcreteBag.webp", icon: "ConcreteBag.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "ConcreteMixer", nameEn: "Бетономешалка", nameRu: "Бетономешалка", iconCode: "ConcreteMixerIcon.png", icon: "ConcreteMixerIcon.png", category: "Другое", faction: "Нейтральные", review: false },
  { code: "Construction", nameEn: "BMS - Universal Assembly Rig", nameRu: "CV (тир 1)", iconCode: "ConstructionIcon.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "ConstructionEquipment", nameEn: "Строительное оборудование", nameRu: "Строительное оборудование", iconCode: "ConstructionEquipment.webp", icon: "ConstructionEquipment.webp", category: "Другое", faction: "Нейтральные", review: false },
  { code: "ConstructionUtility", nameEn: "BMS - Fabricator", nameRu: "Строительная техника", iconCode: "AdvancedConstructionVehicle.webp", icon: "AdvancedConstructionVehicle.webp", category: "Техника", faction: "Нейтральные", review: false },
  { code: "Copper", nameEn: "Copper", nameRu: "Copper", iconCode: "ResourceCopperRefined.png", icon: "ResourceCopperRefined.png", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "CopperA", nameEn: "Copper Alloy", nameRu: "Медь", iconCode: "CopperAIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "Crane", nameEn: "BMS - Class 2 Mobile Auto-Crane", nameRu: "Мобильный автокран БМС 2 класса", iconCode: "CraneIcon.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "Crate", nameEn: "Crate", nameRu: "Crate", iconCode: "CrateIcon.webp", icon: null, category: "Предметы", faction: "Нейтральные", review: true },
  { code: "CriticalSoldier", nameEn: "Critically Wounded Soldier", nameRu: "Critically Wounded Soldier", iconCode: "CriticallyWounded.webp", icon: "CriticallyWounded.webp", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "DemolitionRocketAmmo", nameEn: "Shatter Missile", nameRu: "Разрушающая ракета", iconCode: "DemolitionRocketAmmoIcon.webp", icon: "DemolitionRocketAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "DeployedATRifleTC", nameEn: "Deployed “Typhon” ra.XII", nameRu: "Deployed “Typhon” ra.XII", iconCode: "ATRifleTC.webp", icon: "ATRifleTC.webp", category: "Сооружения", faction: "Колонисты", review: false },
  { code: "DepthChargeAmmo", nameEn: "Model-7 “Evie”", nameRu: "Model-7 “Evie”", iconCode: "DepthCharge.webp", icon: "DepthCharge.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "DestroyerTankFlameW", nameEn: "Noble Firebrand Mk. XVII", nameRu: "Noble Firebrand Mk. XVII", iconCode: "DestroyerTankFlameWIcon.webp", icon: "DestroyerTankFlameW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "DestroyerTankW", nameEn: "Noble Widow MK. XIV", nameRu: "Noble Widow MK. XIV", iconCode: "DestroyerTankWVehicle.webp", icon: "DestroyerTankWVehicle.webp", category: "Техника", faction: "Варден", review: false },
  { code: "Diesel", nameEn: "Diesel", nameRu: "Дизель", iconCode: "DieselIcon.webp", icon: null, category: "Предметы", faction: "Нейтральные", review: true },
  { code: "DiveBomberAmmo", nameEn: "912 Shrike Rounds", nameRu: "912 Shrike Rounds", iconCode: "DiveBomberAmmoIcon.webp", icon: "DiveBomberAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "EmplacedATLargeW", nameEn: "Huber Starbreaker 94.5mm", nameRu: "Huber Starbreaker 94.5", iconCode: "EmplacedATLargeWIcon.webp", icon: null, category: "Сооружения", faction: "Варден", review: true },
  { code: "EmplacedATW", nameEn: "Leary Shellbore 68mm", nameRu: "Leary Shellbore 68-мм", iconCode: "EmplacedATWIcon.webp", icon: null, category: "Сооружения", faction: "Варден", review: true },
  { code: "EmplacedAircraftC", nameEn: "DAE 5b “Zeal”", nameRu: "DAE 5b Zeal", iconCode: "EmplacedAircraftCIcon.webp", icon: null, category: "Сооружения", faction: "Колонисты", review: true },
  { code: "EmplacedAircraftW", nameEn: "Leary AA-70 Bolas", nameRu: "Leary AA-70 Bolas", iconCode: "EmplacedAircraftWIcon.webp", icon: null, category: "Сооружения", faction: "Варден", review: true },
  { code: "EmplacedCannonLargeC", nameEn: "DAE 2a-1 “Ruptura”", nameRu: "DAE 2a-1 Ruptura", iconCode: "EmplacedCannonLargeCIcon.webp", icon: null, category: "Сооружения", faction: "Колонисты", review: true },
  { code: "EmplacedHeavyArtilleryC", nameEn: "50-500 “Thunderbolt” Cannon", nameRu: "50-500 Thunderbolt Cannon", iconCode: "EmplacedHeavyArtilleryCIcon.webp", icon: null, category: "Сооружения", faction: "Колонисты", review: true },
  { code: "EmplacedHeavyArtilleryW", nameEn: "Huber Exalt 150mm", nameRu: "Huber Exalt 150mm", iconCode: "EmplacedHeavyArtilleryWIcon.webp", icon: null, category: "Сооружения", faction: "Варден", review: true },
  { code: "EmplacedIndirectC", nameEn: "DAE 1o-3 “Polybolos”", nameRu: "DAE 1o-3 Polybolos", iconCode: "EmplacedIndirectCIcon.webp", icon: null, category: "Сооружения", faction: "Колонисты", review: true },
  { code: "EmplacedInfantryC", nameEn: "DAE 1b-2 “Serra”", nameRu: "DAE 1b-2 Serra", iconCode: "EmplacedInfantryCIcon.webp", icon: null, category: "Сооружения", faction: "Колонисты", review: true },
  { code: "EmplacedInfantryW", nameEn: "Leary Snare Trap 20", nameRu: "Leary Snare Trap 20", iconCode: "EmplacedInfantryWIcon.webp", icon: null, category: "Сооружения", faction: "Варден", review: true },
  { code: "EmplacedLightArtilleryW", nameEn: "Huber Lariat 120mm", nameRu: "Huber Lariat 120мм", iconCode: "EmplacedLightArtilleryWIcon.webp", icon: null, category: "Сооружения", faction: "Варден", review: true },
  { code: "EmplacedMultiC", nameEn: "DAE 3b-2 “Hades' Net”", nameRu: "DAE 3b-2 Hades Net", iconCode: "EmplacedMultiCIcon.webp", icon: null, category: "Сооружения", faction: "Колонисты", review: true },
  { code: "EngineerUniformC", nameEn: "Fabri Rucksack", nameRu: "Fabri Rucksack", iconCode: "EngineerUniformCIcon.webp", icon: "EngineerUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "EngineerUniformW", nameEn: "Sapper Gear", nameRu: "Сапёрное снаряжение", iconCode: "EngineerUniformWIcon.webp", icon: "EngineerUniformW.webp", category: "Снаряжение", faction: "Варден", review: false },
  { code: "Explosive", nameEn: "Explosive Powder", nameRu: "порох", iconCode: "ExplosiveIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "ExplosiveLightC", nameEn: "Hydra's Whisper", nameRu: "Hydra's Whisper", iconCode: "Bangalore.webp", icon: "Bangalore.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "ExplosiveTripod", nameEn: "Станковый Fissura gd.I", nameRu: "Станковый Fissura gd.I", iconCode: "ExplosiveTripod.webp", icon: "ExplosiveTripod.webp", category: "Оружие", faction: "Нейтральные", review: false },
  { code: "FacilityCoal1", nameEn: "Coke", nameRu: "Coke", iconCode: "CokeIcon.webp", icon: "CokeIcon.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "FacilityComponents1", nameEn: "Damaged Components", nameRu: "Damaged Components", iconCode: "ComponentsDamaged.webp", icon: "ComponentsDamaged.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "FacilityMaterials1", nameEn: "Construction Materials", nameRu: "Сборочные материалы I", iconCode: "FacilityMaterials1Icon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "FacilityMaterials10", nameEn: "Unstable Substances", nameRu: "Unstable Substances", iconCode: "FacilityMaterials10Icon.webp", icon: "FacilityMaterials10.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "FacilityMaterials12", nameEn: "Rare Materials", nameRu: "Rare Materials", iconCode: "FacilityMaterials12Icon.webp", icon: "FacilityMaterials12.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "FacilityMaterials3", nameEn: "Steel Construction Materials", nameRu: "Steel Construction Materials", iconCode: "SteelConstructionMaterials.webp", icon: "SteelConstructionMaterials.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "FacilityMaterials4", nameEn: "Assembly Materials I", nameRu: "Сборочные материалы IV", iconCode: "FacilityMaterials4Icon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "FacilityMaterials5", nameEn: "Assembly Materials II", nameRu: "Assembly Materials II", iconCode: "Сборочные материалы 2.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "FacilityMaterials6", nameEn: "Assembly Materials III", nameRu: "Assembly Materials III", iconCode: "AssemblyMaterials3.webp.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "FacilityMaterials7", nameEn: "Assembly Materials IV", nameRu: "Assembly Materials IV", iconCode: "AssemblyMaterials4.webp", icon: "AssemblyMaterials4.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "FacilityMaterials8", nameEn: "Assembly Materials V", nameRu: "Assembly Materials V", iconCode: "AssemblyMaterials5.webp", icon: "AssemblyMaterials5.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "FacilityMaterials9", nameEn: "Rare Alloys", nameRu: "Rare Alloys", iconCode: "FacilityMaterials09.webp", icon: "FacilityMaterials09.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "FacilityOil1", nameEn: "Heavy Oil", nameRu: "Нефть для объекта I", iconCode: "FacilityOil1Icon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "FacilityOil2", nameEn: "Enriched Oil", nameRu: "Обогащенное топливо", iconCode: "FacilityOil2Icon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "FacilityOil3", nameEn: "Нефть для объекта III", nameRu: "Нефть для объекта III", iconCode: "FacilityOil3Icon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "FacilityPower", nameEn: "Facility Power", nameRu: "Facility Power", iconCode: "FilterPower.webp", icon: "FilterPower.webp", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "FieldAT2C", nameEn: "GA6 “Cestus”", nameRu: "GA6 “Cestus”", iconCode: "FieldAT2CIcon.webp", icon: "FieldAT2C.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "FieldAT2W", nameEn: "Duncan's Coin 14.5mm", nameRu: "Duncan's Coin 14.5mm", iconCode: "FieldAT2WIcon.webp", icon: "FieldAT2W.webp", category: "Техника", faction: "Варден", review: false },
  { code: "FieldATC", nameEn: "AA-2 Battering Ram", nameRu: "AA-2 Battering Ram", iconCode: "FieldAntiTankColVehicle.webp", icon: "FieldAntiTankColVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "FieldATDamageW", nameEn: "Balfour Rampart 68mm", nameRu: "Balfour Rampart 68mm", iconCode: "FieldCannonOffensiveW.webp", icon: "FieldCannonOffensiveW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "FieldATW", nameEn: "Collins Cannon 68mm", nameRu: "Полевая противотанковая пушка", iconCode: "FieldATWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "FieldCannonDamageC", nameEn: "40-45 “Smelter”", nameRu: "40-45 “Smelter”", iconCode: "FieldATOffensiveC.webp", icon: "FieldATOffensiveC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "FieldCannonW", nameEn: "Balfour Wolfhound 40mm", nameRu: "Полевое орудие", iconCode: "FieldCannonWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "FieldMGC", nameEn: "G40 “Sagittarii”", nameRu: "G40 “Sagittarii”", iconCode: "FieldMachineGun.webp", icon: "FieldMachineGun.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "FieldMGW", nameEn: "Swallowtail 988/127-2", nameRu: "Полевой пулемёт", iconCode: "FieldMachineGunWar.webp", icon: "FieldMachineGunWar.webp", category: "Техника", faction: "Варден", review: false },
  { code: "FieldMortarC", nameEn: "30-250 “Tisiphone” Field Cannon", nameRu: "30-250 “Tisiphone” Field Cannon", iconCode: "FieldMortarCIcon.webp", icon: "FieldMortarC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "FieldMortarW", nameEn: "Balfour Falconer 250mm", nameRu: "Balfour Falconer 250mm", iconCode: "FieldMortarWIcon.webp", icon: "FieldMortarW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "FirePitT2", nameEn: "Field Range", nameRu: "Field Range", iconCode: "FirePitIcon.webp", icon: "FirePitIcon.webp", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "FireRocketAmmo", nameEn: "4C-Fire Rocket", nameRu: "4C-Fire Rocket", iconCode: "FlameRocketAmmo.webp", icon: "FlameRocketAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "FirstAidKit", nameEn: "First Aid Kit", nameRu: "Набор Первой Помощи", iconCode: "FirstAidKitIcon.webp", icon: "FirstAidKit.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "FlameAmmo", nameEn: "Flame Ammo", nameRu: "Огненные патроны", iconCode: "FlameAmmoIcon.webp", icon: "FlameAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "FlameBackpackC", nameEn: "“Molten Wind” v.II Ammo", nameRu: "“Molten Wind” v.II Ammo", iconCode: "FlamePackC.webp", icon: "FlamePackC.webp", category: "Боеприпасы", faction: "Колонисты", review: false },
  { code: "FlameBackpackW", nameEn: "Willow's Bane Ammo", nameRu: "Топливо для Willow", iconCode: "FlameBackpackWIcon.webp", icon: null, category: "Боеприпасы", faction: "Варден", review: true },
  { code: "FlameTorchC", nameEn: "“Molten Wind” v.II Flame Torch", nameRu: "“Molten Wind” v.II Flame Torch", iconCode: "FlamegunC.webp", icon: "FlamegunC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "FlameTorchW", nameEn: "Willow's Bane Model 845", nameRu: "Willow's Bane Model 845", iconCode: "FlamegunW.webp", icon: "FlamegunW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "FlatbedTruck", nameEn: "BMS - Packmule Flatbed", nameRu: "Флэтбед (пакмул)", iconCode: "FlatbedTruckIcon.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "FortConstructionPart", nameEn: "Строительные детали", nameRu: "Строительные детали", iconCode: "ConstructionPartsShippable.webp", icon: "ConstructionPartsShippable.webp", category: "Другое", faction: "Нейтральные", review: false },
  { code: "FortGarrisonStationPart", nameEn: "Детали подземной крепости", nameRu: "Детали подземной крепости", iconCode: "FortGarrisonStation.webp", icon: "FortGarrisonStation.webp", category: "Другое", faction: "Нейтральные", review: false },
  { code: "FortIntelCenterPart", nameEn: "Разведывательный Центр", nameRu: "Разведывательный Центр", iconCode: "IntelCenterShippable.png", icon: "IntelCenterShippable.png", category: "Другое", faction: "Нейтральные", review: false },
  { code: "FortLRArtilleryPart", nameEn: "Детали Штурмового Орудия", nameRu: "Детали Штурмового Орудия", iconCode: "StormCannonShippable.webp", icon: "StormCannonShippable.webp", category: "Оружие", faction: "Нейтральные", review: false },
  { code: "FortLargeRadarPart", nameEn: "SC-3 Aerial Interceptor Array Parts", nameRu: "SC-3 Aerial Interceptor Array Parts", iconCode: "FortLargeRadarShippble.webp", icon: "FortLargeRadarShippble.webp", category: "Другое", faction: "Нейтральные", review: false },
  { code: "FortWeatherStationPart", nameEn: "Детали погодной станции", nameRu: "Детали погодной станции", iconCode: "WeatherStationShippable.png", icon: "WeatherStationShippable.png", category: "Другое", faction: "Нейтральные", review: false },
  { code: "Freighter", nameEn: "BMS - Ironship", nameRu: "судно Ironship", iconCode: "FreighterIcon.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "FreighterLight", nameEn: "Das Krokodil by VAC", nameRu: "судно Krokodil", iconCode: "FreighterLightIcon.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "GasMask", nameEn: "Gas Mask", nameRu: "противогаз", iconCode: "GasMaskIcon.webp", icon: "Gasmask.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "GasMaskFilter", nameEn: "Gas Mask Filter", nameRu: "Фильтр для противогаза", iconCode: "GasMaskFilterIcon.webp", icon: "GasMaskFilter.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "GreenAsh", nameEn: "Green Ash Grenade", nameRu: "газовая граната", iconCode: "GreenAshIcon.webp", icon: null, category: "Боеприпасы", faction: "Нейтральные", review: true },
  { code: "GrenadeAdapter", nameEn: "Подствольный гранатомёт", nameRu: "Подствольный гранатомёт", iconCode: "GrenadeAdapter.webp", icon: "GrenadeAdapter.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "GrenadeC", nameEn: "Bomastone Grenade", nameRu: "Bomastone Grenade", iconCode: "GrenadeCIcon.webp", icon: "GrenadeC.webp", category: "Боеприпасы", faction: "Колонисты", review: false },
  { code: "GrenadeLauncherC", nameEn: "KLG901-2 Lunaire F", nameRu: "KLG901-2 Lunaire F", iconCode: "GrenadeLauncherCIcon.webp", icon: "GrenadeLauncherC.webp", category: "Боеприпасы", faction: "Колонисты", review: false },
  { code: "GrenadeLauncherTC", nameEn: "Mounted Fissura gd.I", nameRu: "Mounted Fissura gd.I", iconCode: "GrenadeLauncherTCIcon.webp", icon: "GrenadeLauncherTC.webp", category: "Боеприпасы", faction: "Колонисты", review: false },
  { code: "GrenadeUniformC", nameEn: "Grenadier's Baldric", nameRu: "Grenadier's Baldric", iconCode: "GrenadeUniformCIcon.webp", icon: "GrenadeUniformC.webp", category: "Боеприпасы", faction: "Колонисты", review: false },
  { code: "GrenadeW", nameEn: "A3 Harpa Fragmentation Grenade", nameRu: "Осколочная граната", iconCode: "GrenadeWIcon.webp", icon: "GrenadeW.webp", category: "Боеприпасы", faction: "Варден", review: false },
  { code: "GroundMaterials", nameEn: "Gravel", nameRu: "гравий", iconCode: "GroundMaterialsIcon.webp", icon: "GroundMaterials.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "Gunboat2C", nameEn: "Type B - “Lucian”", nameRu: "Type B - “Lucian”", iconCode: "GunBoat2CVehicle.webp", icon: "GunBoat2CVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "Gunboat2W", nameEn: "81f-f Ronan Blackguard", nameRu: "БТР-Амфибия (Mulloy)", iconCode: "Gunboat2WIcon.webp", icon: "Gunboat2W.webp", category: "Техника", faction: "Варден", review: false },
  { code: "GunboatC", nameEn: "Type C - “Charon”", nameRu: "Type C - “Charon”", iconCode: "GunBoatCHull.webp", icon: "GunBoatCHull.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "GunboatW", nameEn: "74b-1 Ronan Gunship", nameRu: "74b-1 Ronan Gunship", iconCode: "GunboatWIcon.webp", icon: "GunboatW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "HEGrenade", nameEn: "Mammon 91-b", nameRu: "Маммонка", iconCode: "HEGrenadeIcon.webp", icon: "HEGrenade.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "HELaunchedGrenade", nameEn: "Tremola Grenade GPb-1", nameRu: "Осколочный снаряд РПГ", iconCode: "HELaunchedGrenadeIcon.webp", icon: "HELaunchedGrenade.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "HERocketAmmo", nameEn: "3C-High Explosive Rocket", nameRu: "3C-High Explosive Rocket", iconCode: "HERocketAmmoIcon.webp", icon: "HERocketAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "HalfTrackArtilleryC", nameEn: "HH-d “Peltast”", nameRu: "HH-d “Peltast”", iconCode: "HalfTrackArtilleryCIcon.webp", icon: "HalfTrackArtilleryC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "HalfTrackC", nameEn: "HH-a “Javelin”", nameRu: "HH-a “Javelin”", iconCode: "HalfTrackColVehicle.webp", icon: "HalfTrackColVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "HalfTrackDefensiveC", nameEn: "HH-b “Hoplite”", nameRu: "HH-b “Hoplite”", iconCode: "HalfTrackColHeavyArmorVehicle.webp", icon: "HalfTrackColHeavyArmorVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "HalfTrackOffensiveW", nameEn: "Niska Mk. II Blinder", nameRu: "Niska Mk. II Blinder", iconCode: "HalfTrackOffensiveWarVehicle.webp", icon: "HalfTrackOffensiveWarVehicle.webp", category: "Техника", faction: "Варден", review: false },
  { code: "HalfTrackTwinW", nameEn: "Niska Mk. III Scar Twin", nameRu: "Niska Mk. III Scar Twin", iconCode: "HalfTrackTwinWIcon.webp", icon: "HalftrackTwinW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "HalfTrackW", nameEn: "Niska Mk. I Gun Motor Carriage", nameRu: "Полугусеничный бронеавтомобиль", iconCode: "HalfTrackWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "HalftrackMultiW", nameEn: "Niska-Rycker Mk. IX Skycaller", nameRu: "Niska-Rycker Mk. IX Skycaller", iconCode: "HalftrackMultiWIcon.webp", icon: "HalftrackMultiW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "Harvester", nameEn: "BMS - Scrap Hauler", nameRu: "BMS - Scrap Hauler", iconCode: "HarvesterIcon.webp", icon: "Harvester.webp", category: "Техника", faction: "Нейтральные", review: false },
  { code: "HeavyArtilleryAmmo", nameEn: "150mm", nameRu: "150-мм", iconCode: "HeavyArtilleryAmmoIcon.webp", icon: "HeavyArtilleryAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "HeavyExplosive", nameEn: "Heavy Explosive Powder", nameRu: "Тяжёлая взрывчатка", iconCode: "HeavyExplosiveIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "HeavyTruckC", nameEn: "AU-A150 Taurine Rigger", nameRu: "AU-A150 Taurine Rigger", iconCode: "HeavyTruckCVehicleC.webp", icon: "HeavyTruckCVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "HeavyTruckW", nameEn: "Cnute Cliffwrest", nameRu: "кнут", iconCode: "HeavyTruckWIcon.webp", icon: "HeavyTruckW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "ISGTC", nameEn: "Daucus isg.III", nameRu: "Daucus isg.III", iconCode: "InfantrySupportGun.webp", icon: "InfantrySupportGun.webp", category: "Предметы", faction: "Колонисты", review: false },
  { code: "In06KItem", nameEn: "Blackened Runestone", nameRu: "Blackened Runestone", iconCode: "RunestoneSIcon.png", icon: "RunestoneSIcon.png", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "InfantryMine", nameEn: "Crow's Foot Mine", nameRu: "Crow's Foot Mine", iconCode: "InfantryMineIcon.webp", icon: "InfantryMine.webp", category: "Оружие", faction: "Нейтральные", review: false },
  { code: "Iron", nameEn: "Iron", nameRu: "Iron", iconCode: "ResouceIron.png", icon: "ResouceIron.png", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "IronA", nameEn: "Iron Alloy", nameRu: "Iron Alloy", iconCode: "ResouceIronRefined.png", icon: "ResouceIronRefined.png", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "LRArtillery", nameEn: "Storm Cannon", nameRu: "Storm Cannon", iconCode: "LongRangedArtillery.webp", icon: "LongRangedArtillery.webp", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "LRArtilleryAmmo", nameEn: "300mm", nameRu: "300mm", iconCode: "LRArtilleryAmmoIcon.webp", icon: "LRArtilleryAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "LandingCraftC", nameEn: "AB-8 “Acheron”", nameRu: "десантный катер", iconCode: "LandingCraftVehicleC.webp", icon: "LandingCraftVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LandingCraftOffensiveC", nameEn: "AB-11 “Doru”", nameRu: "AB-11 “Doru”", iconCode: "LLandingCraftOffensiveVehicleC.webp", icon: null, category: "Техника", faction: "Колонисты", review: true },
  { code: "LandingCraftW", nameEn: "Mulloy LPC", nameRu: "БТР-Амфибия (Mulloy)", iconCode: "LandingCraftWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "LandingShipC", nameEn: "Interceptor PA-12", nameRu: "Interceptor PA-12", iconCode: "LandingShipCIcon.webp", icon: "LandingShipC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LandingShipW", nameEn: "MacConmara Shorerunner", nameRu: "MacConmara Shorerunner", iconCode: "LandingShipWIcon.webp", icon: "LandingShipW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "LargeCrane", nameEn: "BMS - Overseer Sky-Hauler", nameRu: "BMS - Overseer Sky-Hauler", iconCode: "LargeCrane.webp", icon: "LargeCrane.webp", category: "Техника", faction: "Нейтральные", review: false },
  { code: "LargeFieldATC", nameEn: "945g “Stygian Bolt”", nameRu: "945g “Stygian Bolt”", iconCode: "FieldATHeavyC.webp", icon: "FieldATHeavyC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LargeFieldCannonW", nameEn: "Balfour Stockade 75mm", nameRu: "Balfour Stockade 75mm", iconCode: "FieldCannonHeavyW.webp", icon: "FieldCannonHeavyW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "LargeFieldLightArtilleryC", nameEn: "120-68 “Koronides” Field Gun", nameRu: "120-68 “Koronides” Field Gun", iconCode: "FieldArtilleryColVehicle.webp", icon: "FieldArtilleryColVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LargeFieldMortarC", nameEn: "40-250 “Alekto” Heavy Cannon", nameRu: "40-250 “Alekto” Heavy Cannon", iconCode: "LargeFieldMortarCIcon.webp", icon: "LargeFieldMortarC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LargeFieldMultiW", nameEn: "Rycker 4/3-F Wasp Nest", nameRu: "Полевая многозарядная установка", iconCode: "FieldMultiWItem.webp", icon: "FieldMultiWItem.webp", category: "Техника", faction: "Варден", review: false },
  { code: "LargeShipAircraftC", nameEn: "Poseidon", nameRu: "Poseidon", iconCode: "LargeshipAircraftC.webp", icon: "LargeshipAircraftC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LargeShipBaseShip", nameEn: "BMS - Longhook", nameRu: "BMS - Longhook", iconCode: "LargeShipBaseShip.webp", icon: "LargeShipBaseShip.webp", category: "Техника", faction: "Нейтральные", review: false },
  { code: "LargeShipBattleshipAircraftW", nameEn: "Mercy", nameRu: "Mercy", iconCode: "LargeShipBattleshipAircraftW.webp", icon: "LargeShipBattleshipAircraftW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "LargeShipDestroyerW", nameEn: "Blacksteele", nameRu: "Blacksteele", iconCode: "LargeShipDestroyerW.webp", icon: "LargeShipDestroyerW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "LargeShipResourceShip", nameEn: "BMS - Bowhead", nameRu: "BMS - Bowhead", iconCode: "LargeShipResource.webp.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "LargeShipStorageShip", nameEn: "BMS - Bluefin", nameRu: "BMS - Bluefin", iconCode: "LargeShipStorageShip.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "LightAAAmmo", nameEn: "Absol Anti-Aircraft Rounds", nameRu: "Зенитный снаряд “Absol”", iconCode: "LightAAAmmoIcon.webp", icon: "LightAAAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "LightArtilleryAmmo", nameEn: "120mm", nameRu: "120-мм", iconCode: "LightArtilleryAmmoIcon.webp", icon: "LightArtilleryAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "LightBoatInfantryC", nameEn: "K-81e “Sombre”", nameRu: "K-81e “Sombre”", iconCode: "LightBoatInfantryCIcon.webp", icon: "LightBoatInfantryC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LightBoatInfantryW", nameEn: "68A-4 Ronan Fathomer", nameRu: "лёгкая пехотная лодка", iconCode: "LightBoatInfantryWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "LightTank2InfantryC", nameEn: "HC-2 “Scorpion”", nameRu: "HC-2 “Scorpion”", iconCode: "LightTank2InfantryCVehicle.webp", icon: "LightTank2InfantryCVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LightTank3C", nameEn: "HA-1 “Sagaris”", nameRu: "HA-1 “Sagaris”", iconCode: "LightTank3CVehicle.webp", icon: "LightTank3CVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LightTank3W", nameEn: "Sharkey-Devitt Birdeater Mk. I", nameRu: "Sharkey-Devitt Birdeater Mk. I", iconCode: "LightTank3WVehicle.webp", icon: "LightTank3WVehicle.webp", category: "Техника", faction: "Варден", review: false },
  { code: "LightTankAmmo", nameEn: "40mm", nameRu: "40-мм", iconCode: "LightTankAmmoIcon.webp", icon: "LightTankAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "LightTankArtilleryW", nameEn: "Devitt-Caine Mk. IV MMR", nameRu: "Легкий арт-танк", iconCode: "LightTankArtilleryWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "LightTankC", nameEn: "H-5 “Hatchet”", nameRu: "строительный прицеп", iconCode: "LightTankCIcon.webp", icon: null, category: "Техника", faction: "Колонисты", review: true },
  { code: "LightTankDefensiveW", nameEn: "Devitt Ironhide Mk. IV", nameRu: "Devitt Ironhide Mk. IV", iconCode: "LightTankWarDefensiveVehicle.webp", icon: "LightTankWarDefensiveVehicle.webp", category: "Техника", faction: "Варден", review: false },
  { code: "LightTankFlameC", nameEn: "H-19 “Vulcan”", nameRu: "H-19 “Vulcan”", iconCode: "LightTankFlameCIcon.webp", icon: "LightTankFlameC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LightTankMobilityC", nameEn: "H-8 “Kranesca”", nameRu: "H-8 “Kranesca”", iconCode: "LightTankColMobilityVehicle.webp", icon: "LightTankColMobilityVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LightTankOffensiveC", nameEn: "H-10 “Pelekys”", nameRu: "H-10 “Pelekys”", iconCode: "LightTankOffensiveCVehicle.webp", icon: "LightTankOffensiveCVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "LightTankW", nameEn: "Devitt Mk. III", nameRu: "Devitt Mk. III", iconCode: "LightTankWarDefensiveVehicle.webp", icon: "LightTankWarDefensiveVehicle.webp", category: "Техника", faction: "Варден", review: false },
  { code: "LiquidContainer", nameEn: "Liquid Container", nameRu: "Жидкостный контейнер", iconCode: "LiquidContainerIcon.webp", icon: null, category: "Сооружения", faction: "Нейтральные", review: true },
  { code: "ListeningKit", nameEn: "Listening Kit", nameRu: "Набор для прослушивания", iconCode: "ListeningKitIcon.webp", icon: "ListeningKit.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "MGAmmo", nameEn: "12.7mm", nameRu: "12.7 мм (пулемётные) патроны", iconCode: "MGAmmoIcon.webp", icon: null, category: "Боеприпасы", faction: "Нейтральные", review: true },
  { code: "MGC", nameEn: "KRN886-127 Gast Machine Gun", nameRu: "KRN886-127 Gast Machine Gun", iconCode: "MGC.webp", icon: "MGC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "MGTC", nameEn: "Lamentum mm.IV", nameRu: "Lamentum mm.IV", iconCode: "HeavyMachineGun.webp", icon: "HeavyMachineGun.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "MGTW", nameEn: "Malone Ratcatcher MK.1", nameRu: "Станковый пулемет варденов", iconCode: "MGTWIcon.webp", icon: null, category: "Оружие", faction: "Варден", review: true },
  { code: "MGW", nameEn: "Malone MK.2", nameRu: "Malone MK.2", iconCode: "MGWIcon.webp", icon: "MGW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "MaceW", nameEn: "Falias Raiding Club", nameRu: "Falias Raiding Club", iconCode: "TrenchMaceW", icon: null, category: "Предметы", faction: "Варден", review: true },
  { code: "MaintenanceSupplies", nameEn: "Maintenance Supplies", nameRu: "Припасы Обслуживания", iconCode: "MaintenanceSuppliesIcon.webp", icon: "MaintenanceSupplies.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "MaterialPlatform", nameEn: "Material Pallet", nameRu: "Поддон для материалов", iconCode: "MaterialPlatformIcon.webp", icon: "MaterialPlatform.webp", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "MedicUniformC", nameEn: "Medic Fatigues", nameRu: "Medic Fatigues", iconCode: "MedicUniformCIcon.webp", icon: "MedicUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "MedicUniformW", nameEn: "Physician's Jacket", nameRu: "Куртка врача", iconCode: "MedicUniformWIcon.webp", icon: "MedicUniformW.webp", category: "Снаряжение", faction: "Варден", review: false },
  { code: "MediumBoatC", nameEn: "Strider", nameRu: "пожарная машина", iconCode: "MediumBoatCIcon.webp", icon: "MediumBoatC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "MediumBoatW", nameEn: "Rinnspeir Ornitier-Class Gunship", nameRu: "Средняя лодка варденов", iconCode: "MediumBoatWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "MediumTank2C", nameEn: "86K-a “Bardiche”", nameRu: "86K-a “Bardiche”", iconCode: "MediumTank2CIcon.webp", icon: "MediumTank2C.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "MediumTank2IndirectW", nameEn: "Gallagher Thornfall Mk. VI", nameRu: "Gallagher Thornfall Mk. VI", iconCode: "MediumTank2IndirectWIcon.webp", icon: "MediumTank2IndirectW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "MediumTank2MultiW", nameEn: "Gallagher Highwayman Mk. III", nameRu: "Gallagher Highwayman Mk. III", iconCode: "MediumTank2MultiWIcon.webp", icon: "MediumTank2MultiW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "MediumTank2RangeW", nameEn: "Gallagher Outlaw Mk. II", nameRu: "Gallagher Outlaw Mk. II", iconCode: "MediumTank2RangeWIcon.webp", icon: "MediumTank2RangeW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "MediumTank2TwinC", nameEn: "86K-c “Ranseur”", nameRu: "86K-c “Ranseur”", iconCode: "MediumTank2TwinC", icon: null, category: "Техника", faction: "Колонисты", review: true },
  { code: "MediumTank2W", nameEn: "Gallagher Brigand Mk. I", nameRu: "Средний танк (тир 2)", iconCode: "MediumTank2WIcon.webp", icon: "MediumTank2W.webp", category: "Техника", faction: "Варден", review: false },
  { code: "MediumTank3C", nameEn: "90T-v “Nemesis”", nameRu: "90T-v “Nemesis”", iconCode: "MediumTank3C.webp", icon: null, category: "Техника", faction: "Колонисты", review: true },
  { code: "MediumTankATW", nameEn: "Silverhand Lordscar - Mk. X", nameRu: "Silverhand Lordscar - Mk. X", iconCode: "MediumTankATWIcon.webp", icon: "MediumTankATW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "MediumTankC", nameEn: "85K-b “Falchion”", nameRu: "85K-b “Falchion”", iconCode: "ColonialMediumTank.webp", icon: "ColonialMediumTank.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "MediumTankLargeC", nameEn: "85V-g “Talos”", nameRu: "85V-g “Talos”", iconCode: "MediumTankLargeCIcon.webp", icon: "MediumTankLargeC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "MediumTankOffensiveC", nameEn: "85K-a “Spatha”", nameRu: "85K-a “Spatha”", iconCode: "ColonialMediumTankOffensive.webp", icon: "ColonialMediumTankOffensive.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "MediumTankSiegeW", nameEn: "Silverhand Chieftain - Mk. VI", nameRu: "Silverhand Chieftain - Mk. VI", iconCode: "MediumTankSiegeWVehicle.webp", icon: "MediumTankSiegeWVehicle.webp", category: "Техника", faction: "Варден", review: false },
  { code: "MediumTankW", nameEn: "Silverhand - Mk. IV", nameRu: "Silverhand - Mk. IV", iconCode: "WardenMediumTank", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "Metal", nameEn: "Salvage", nameRu: "Salvage", iconCode: "Salvage.webp", icon: "Salvage.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "MetalBeamMaterials", nameEn: "Metal Beam", nameRu: "металлическая балка", iconCode: "MetalBeamMaterialsIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "MineBoat", nameEn: "Bellweather by VAC", nameRu: "Bellweather by VAC", iconCode: "MineBoatIcon.webp", icon: "Mineboat.webp", category: "Техника", faction: "Нейтральные", review: false },
  { code: "MiniTankAmmo", nameEn: "30mm", nameRu: "Снаряды малого танка", iconCode: "MiniTankAmmoIcon.webp", icon: "MiniTankAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "MiniTorpedoAmmo", nameEn: "Quillback Torpedo", nameRu: "торпеда", iconCode: "MiniTorpedoAmmoIcon.webp", icon: "MiniTorpedoAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "Mortar", nameEn: "Cremari Mortar", nameRu: "миномёт", iconCode: "MortarIcon.webp", icon: "Mortar.webp", category: "Оружие", faction: "Нейтральные", review: false },
  { code: "MortarAmmo", nameEn: "Mortar Shell", nameRu: "миномётный снаряд", iconCode: "MortarAmmoIcon.webp", icon: "MortarAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "MortarAmmoFL", nameEn: "Flare Mortar Shell", nameRu: "Осветительный миномётный снаряд", iconCode: "MortarAmmoFLIcon.webp", icon: null, category: "Боеприпасы", faction: "Нейтральные", review: true },
  { code: "MortarAmmoFlame", nameEn: "Incendiary Mortar Shell", nameRu: "Зажигательный миномётный снаряд", iconCode: "MortarAmmoFlameIcon.webp", icon: "MortarAmmoFlame.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "MortarAmmoSH", nameEn: "Shrapnel Mortar Shell", nameRu: "Осколочный миномётный снаряд", iconCode: "MortarAmmoSHIcon.webp", icon: null, category: "Боеприпасы", faction: "Нейтральные", review: true },
  { code: "MortarTankAmmo", nameEn: "250mm “Purity” Shell", nameRu: "Снаряд миномётного танка", iconCode: "MortarTankAmmoIcon.webp", icon: null, category: "Боеприпасы", faction: "Нейтральные", review: true },
  { code: "MortarTankAmmoBR", nameEn: "250mm “Fury” Shell", nameRu: "Снаряд миномётного танка (бронебойный)", iconCode: "MortarTankAmmoBRIcon.webp", icon: "MortarTankAmmoBR.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "MortarTankC", nameEn: "HC-7 “Ballista”", nameRu: "HC-7 “Ballista”", iconCode: "MortarTankVehicle.webp", icon: "MortarTankVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "Motorboat", nameEn: "BMS - Grouper", nameRu: "BMS - Grouper", iconCode: "Motorboat.webp", icon: "Motorboat.webp", category: "Техника", faction: "Нейтральные", review: false },
  { code: "MotorcycleC", nameEn: "03MM “Caster”", nameRu: "03MM “Caster”", iconCode: "MotorcycleVehicleC.webp", icon: "MotorcycleVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "MotorcycleOffensiveC", nameEn: "00MS “Stinger”", nameRu: "00MS “Stinger”", iconCode: "MotorcycleOffensiveVehicleIcon.webp", icon: null, category: "Техника", faction: "Колонисты", review: true },
  { code: "MotorcycleW", nameEn: "Kivela Power Wheel 80-1", nameRu: "Мотоцикл", iconCode: "MotorcycleWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "NavalUniformC", nameEn: "Remex Garb", nameRu: "Remex Garb", iconCode: "NavalUniformCIcon.webp", icon: "NavalUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "NavalUniformW", nameEn: "Gentleman's Peacoat", nameRu: "форма моряка", iconCode: "NavalUniformWIcon.webp", icon: "NavalUniformW.webp", category: "Снаряжение", faction: "Варден", review: false },
  { code: "OfficerUniformC", nameEn: "Officialis' Attire", nameRu: "Officialis' Attire", iconCode: "OfficerUniformCIcon.webp", icon: "OfficerUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "OfficerUniformW", nameEn: "Officer's Regalia", nameRu: "офицерская форма", iconCode: "OfficerUniformWIcon.webp", icon: "OfficerUniformW.webp", category: "Снаряжение", faction: "Варден", review: false },
  { code: "Oil", nameEn: "Oil", nameRu: "Нефть", iconCode: "OilIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "ParatrooperBackpack", nameEn: "Paratrooper's Ruck", nameRu: "Paratrooper's Ruck", iconCode: "ParatrooperBackpackIcon.webp", icon: "ParatrooperBackpack.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "ParatrooperUniformC", nameEn: "Auster's Harness", nameRu: "Auster's Harness", iconCode: "ParatrooperUniformCIcon.webp", icon: "ParatrooperUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "Petrol", nameEn: "Petrol", nameRu: "Бензин", iconCode: "PetrolIcon.webp", icon: null, category: "Предметы", faction: "Нейтральные", review: true },
  { code: "PilotMask", nameEn: "Flight Mask", nameRu: "Маска пилота", iconCode: "PilotMaskIcon.webp", icon: "PilotMask.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "PilotUniformC", nameEn: "Lodesman's Lorica", nameRu: "Lodesman's Lorica", iconCode: "PilotUniformCIcon.webp", icon: "PilotUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "PilotUniformW", nameEn: "Aviator's Raiment", nameRu: "Aviator's Raiment", iconCode: "PilotUniformWIcon.webp", icon: "PilotUniformW.webp", category: "Снаряжение", faction: "Варден", review: false },
  { code: "PipeMaterials", nameEn: "Pipe", nameRu: "Pipe", iconCode: "EngineRoomPipe.webp", icon: "EngineRoomPipe.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "PistolAmmo", nameEn: "8mm", nameRu: "8мм (пистолет)", iconCode: "PistolAmmoIcon.webp", icon: "PistolAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "PistolC", nameEn: "Ferro 879", nameRu: "Ferro 879", iconCode: "PistolCIcon.webp", icon: "PistolC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "PistolLightW", nameEn: "Cascadier 873", nameRu: "Cascadier 873", iconCode: "PistolLightWIcon.webp", icon: "PistolLightW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "PistolW", nameEn: "Ahti Model 2", nameRu: "Ahti Model 2", iconCode: "PistolWIcon.webp", icon: "PistolW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "PrototypeKit", nameEn: "Prototype Kit", nameRu: "Prototype Kit", iconCode: "PrototypeKit.png", icon: "PrototypeKit.png", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "RPGTW", nameEn: "Cutler Foebreaker", nameRu: "РПГ (танковый вариант)", iconCode: "RPGTWIcon.webp", icon: null, category: "Оружие", faction: "Варден", review: true },
  { code: "Radio", nameEn: "Radio", nameRu: "рация", iconCode: "RadioIcon.webp", icon: "Radio.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "RadioBackpack", nameEn: "Radio Backpack", nameRu: "Радиорюкзак", iconCode: "RadioBackpackIcon.webp", icon: "RadioBackpack.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "RareMaterials", nameEn: "Редкие материалы", nameRu: "Редкие материалы", iconCode: "RareMaterials.webp", icon: "RareMaterials.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "RareMetal", nameEn: "Rare Metal", nameRu: "Редкий металл", iconCode: "RareMetalIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "ReservePower", nameEn: "Reserve Power", nameRu: "Reserve Power", iconCode: "ReservePower.png", icon: "ReservePower.png", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "ResourceContainer", nameEn: "Resource Container", nameRu: "контейнер для ресурсов", iconCode: "ResourceContainerIcon.webp", icon: "ResourceContainer.webp", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "Revolver", nameEn: "Cometa T2-9", nameRu: "револьвер", iconCode: "RevolverIcon.webp", icon: "Revolver.webp", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "RevolverAmmo", nameEn: ".44 Mag", nameRu: ".44 Магнум", iconCode: "RevolverAmmoIcon.webp", icon: "RevolverAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "RifleAmmo", nameEn: "7.62mm", nameRu: "7.62-мм", iconCode: "RifleAmmoIcon.webp", icon: "RifleAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "RifleAutomaticC", nameEn: "Catena rt.IV Auto-Rifle", nameRu: "Catena rt.IV Auto-Rifle", iconCode: "RifleAutomaticCIcon.webp", icon: "RifleAutomaticC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "RifleAutomaticW", nameEn: "Sampo Auto-Rifle 77", nameRu: "Автоматическая винтовка Sampo 77", iconCode: "RifleAutomaticWIcon.webp", icon: "RifleAutomaticW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "RifleC", nameEn: "Argenti r.II Rifle", nameRu: "Argenti r.II Rifle", iconCode: "RifleCIcon.webp", icon: "RifleC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "RifleHeavyC", nameEn: "Volta r.I Repeater", nameRu: "Volta r.I Repeater", iconCode: "RifleHeavyCIcon.webp", icon: "RifleHeavyC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "RifleHeavyW", nameEn: "The Hangman 757", nameRu: "Хангман 757", iconCode: "RifleHeavyWIcon.webp", icon: null, category: "Оружие", faction: "Варден", review: true },
  { code: "RifleLightC", nameEn: "Fuscina pi.I", nameRu: "Fuscina pi.I", iconCode: "RifleLightCIcon.webp", icon: "RifleLightC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "RifleLightW", nameEn: "Blakerow 871", nameRu: "винтовка Blakerov", iconCode: "RifleLightWIcon.webp", icon: null, category: "Оружие", faction: "Варден", review: true },
  { code: "RifleLongC", nameEn: "KRR2-790 Omen", nameRu: "KRR2-790 Omen", iconCode: "RifleLongCIcon.webp", icon: "RifleLongC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "RifleLongW", nameEn: "Clancy Cinder M3", nameRu: "Clancy Cinder M3", iconCode: "RifleLongWIcon.webp", icon: "RifleLongW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "RifleShortW", nameEn: "No.2B Hawthorne", nameRu: "No.2B Hawthorne", iconCode: "RifleShortWIcon.webp", icon: "RifleShortW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "RifleW", nameEn: "No.2 Loughcaster", nameRu: "Винтовка No.2 Loughcaster", iconCode: "RifleWIcon.webp", icon: "RifleW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "Rocket", nameEn: "A0E-9 Rocket", nameRu: "A0E-9 Rocket", iconCode: "Rocket.jpg", icon: "Rocket.jpg", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "RocketPartBottom", nameEn: "A0E-9 Rocket Booster", nameRu: "AOE-9 Ракетный Ускоритель", iconCode: "RocketPartBottomIcon.webp", icon: null, category: "Сооружения", faction: "Нейтральные", review: true },
  { code: "RocketPartCenter", nameEn: "A0E-9 Rocket Body", nameRu: "Корпус ракеты AOE-9", iconCode: "RocketPartCenterIcon.webp", icon: null, category: "Сооружения", faction: "Нейтральные", review: true },
  { code: "RocketPartTop", nameEn: "A0E-9 Rocket Warhead", nameRu: "AOE-9 ракетная боеголовка", iconCode: "RocketPartTopIcon.webp", icon: "RocketPartTop.webp", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "RocketSite", nameEn: "A0E-9 Rocket Platform", nameRu: "A0E-9 Rocket Platform", iconCode: "RocketSite.webp", icon: "RocketSite.webp", category: "Сооружения", faction: "Нейтральные", review: false },
  { code: "RpgAmmo", nameEn: "RPG", nameRu: "снаряд РПГ", iconCode: "RpgAmmoIcon.webp", icon: "RpgAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "RpgW", nameEn: "Cutler Launcher 4", nameRu: "Cutler Launcher 4", iconCode: "RpgWIcon.webp", icon: "RpgW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "SMGAmmo", nameEn: "9mm", nameRu: "9мм", iconCode: "SMGAmmoIcon.webp", icon: null, category: "Боеприпасы", faction: "Нейтральные", review: true },
  { code: "SMGC", nameEn: "“The Pitch Gun” mc.V", nameRu: "“The Pitch Gun” mc.V", iconCode: "SMGCIcon.webp", icon: "SMGC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "SMGHeavyC", nameEn: "“Lionclaw” mc.VIII", nameRu: "“Lionclaw” mc.VIII", iconCode: "SMGHeavyCIcon.webp", icon: "SMGHeavyC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "SMGHeavyW", nameEn: "No.1 “The Liar” Submachine Gun", nameRu: "Пистолет-пулемёт No.1 ", iconCode: "SMGHeavyWIcon.webp", icon: "SMGHeavyW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "SMGW", nameEn: "Fiddler Submachine Gun Model 868", nameRu: "Пистолет пулемет Fiddler", iconCode: "SMGWIcon.webp", icon: null, category: "Оружие", faction: "Варден", review: true },
  { code: "SandbagMaterials", nameEn: "Sandbag", nameRu: "Мешки с песком (материалы)", iconCode: "SandbagMaterialsIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "SatchelChargeT", nameEn: "Заряд Аллигатор", nameRu: "Заряд Аллигатор", iconCode: "SatchelChargeTIcon.webp", icon: "SatchelChargeT.webp", category: "Другое", faction: "Нейтральные", review: false },
  { code: "SatchelChargeW", nameEn: "Alligator Charge", nameRu: "Хавок Заряд", iconCode: "SatchelCharge.webp", icon: "SatchelCharge.webp", category: "Предметы", faction: "Варден", review: false },
  { code: "ScoutTankMultiW", nameEn: "King Jester Mk. I-1", nameRu: "King Jester Mk. I-1", iconCode: "ScoutTankMultiWIcon.webp", icon: "ScoutTankMultiW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "ScoutTankOffensiveW", nameEn: "King Gallant Mk. II", nameRu: "King Gallant Mk. II", iconCode: "ScoutTankOffensiveWIcon.webp", icon: "ScoutTankOffensiveW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "ScoutTankW", nameEn: "King Spire Mk. I", nameRu: "King Spire Mk.1 (скаут танк)", iconCode: "ScoutTankWIcon.webp", icon: "ScoutTankW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "ScoutUniformC", nameEn: "Recon Camo", nameRu: "Recon Camo", iconCode: "ScoutUniformCIcon.webp", icon: "ScoutUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "ScoutUniformW", nameEn: "Outrider's Mantle", nameRu: "Дозорная мантия", iconCode: "ScoutUniformWIcon.webp", icon: "ScoutUniformW.webp", category: "Снаряжение", faction: "Варден", review: false },
  { code: "ScoutVehicleMobilityC", nameEn: "UV-05a “Argonaut”", nameRu: "UV-05a “Argonaut”", iconCode: "ScoutVehicleMobilityVehicleC.webp", icon: "ScoutVehicleMobilityVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "ScoutVehicleOffensiveC", nameEn: "UV-24 “Icarus”", nameRu: "UV-24 “Icarus”", iconCode: "ScoutVehicleOffensiveVehicleC.webp", icon: "ScoutVehicleOffensiveVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "ScoutVehicleOffensiveW", nameEn: "Drummond Spitfire 100d", nameRu: "Spitfire", iconCode: "ScoutVehicleOffensiveWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "ScoutVehicleUtilityC", nameEn: "UV-5c “Odyssey”", nameRu: "Машина скорой помощи", iconCode: "ScoutVehicleUtilityCIcon.webp", icon: null, category: "Техника", faction: "Колонисты", review: true },
  { code: "ScoutVehicleUtilityW", nameEn: "Drummond Loscann 55c", nameRu: "Drummond Loscann 55c", iconCode: "ScoutVehicleAmphibiousWa", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "ScoutVehicleW", nameEn: "Drummond 100a", nameRu: "O'Brien V.110 / Скаут", iconCode: "ScoutVehicleWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "ShipPart1", nameEn: "Naval Hull Segments", nameRu: "Корабельный сегмент корпуса", iconCode: "ShipPart1Icon.webp", icon: null, category: "Сооружения", faction: "Нейтральные", review: true },
  { code: "ShipPart2", nameEn: "Naval Shell Plating", nameRu: "Корабельная обшивка корпуса", iconCode: "ShipPart2Icon.webp", icon: null, category: "Сооружения", faction: "Нейтральные", review: true },
  { code: "ShipPart3", nameEn: "Naval Turbine Components", nameRu: "Компоненты морских турбин", iconCode: "ShipPart3Icon.webp", icon: null, category: "Сооружения", faction: "Нейтральные", review: true },
  { code: "ShippingContainer", nameEn: "Shipping Container", nameRu: "Грузовой контейнер", iconCode: "ShippingContainerIcon.webp", icon: null, category: "Сооружения", faction: "Нейтральные", review: true },
  { code: "ShotgunAmmo", nameEn: "Buckshot", nameRu: "дробь", iconCode: "ShotgunAmmoIcon.webp", icon: "ShotgunAmmo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "ShotgunC", nameEn: "KRF1-750 Dragonfly", nameRu: "KRF1-750 Dragonfly", iconCode: "ShotgunCIcon.webp", icon: "ShotgunC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "ShotgunW", nameEn: "No.4 The Pillory Scattergun", nameRu: "дробовик", iconCode: "ShotgunWIcon.webp", icon: "ShotgunW.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "Shovel", nameEn: "Shovel", nameRu: "лопата", iconCode: "ShovelIcon.webp", icon: "Shovel.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "SledgeHammer", nameEn: "Sledge Hammer", nameRu: "кувалда", iconCode: "SledgeHammerIcon.webp", icon: "SledgeHammer.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "SmokeGrenade", nameEn: "PT-815 Smoke Grenade", nameRu: "дымовая граната", iconCode: "SmokeGrenadeIcon.webp", icon: "Smokegrenade.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "SniperRifleC", nameEn: "KRR3-792 Auger", nameRu: "KRR3-792 Auger", iconCode: "SniperRifleCIcon.webp", icon: "SniperRifleC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "SniperRifleW", nameEn: "Clancy-Raca M4", nameRu: "Clancy-Raca M4", iconCode: "SniperRifle.webp", icon: "SniperRifle.webp", category: "Оружие", faction: "Варден", review: false },
  { code: "SnowUniformC", nameEn: "Heavy Topcoat", nameRu: "Heavy Topcoat", iconCode: "SnowUniformCIcon.webp", icon: "SnowUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "SnowUniformW", nameEn: "Парка Caoivish", nameRu: "Парка Caoivish", iconCode: "SnowUniformW.webp", icon: "SnowUniformW.webp", category: "Снаряжение", faction: "Варден", review: false },
  { code: "SoldierSupplies", nameEn: "Soldier Supplies", nameRu: "рубашки", iconCode: "SoldierSuppliesIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "SoldierUniformW", nameEn: "Infantry Battledress", nameRu: "Infantry Battledress", iconCode: "SoldierUniformWIcon.webp", icon: "SoldierUniformW.webp", category: "Снаряжение", faction: "Варден", review: false },
  { code: "StickyBomb", nameEn: "Anti-Tank Sticky Bomb", nameRu: "липкая бомба (стика)", iconCode: "StickyBombIcon.webp", icon: "StickyBomb.webp", category: "Оружие", faction: "Нейтральные", review: false },
  { code: "StructureCrate", nameEn: "Shippable Crate", nameRu: "Ящик с сооружениями", iconCode: "StructureCrateIcon.webp", icon: null, category: "Сооружения", faction: "Нейтральные", review: true },
  { code: "Sulfur", nameEn: "Sulfur", nameRu: "Sulfur", iconCode: "Sulfur.webp", icon: "Sulfur.webp", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "SuperTankC", nameEn: "O-75b “Ares”", nameRu: "O-75b “Ares”", iconCode: "SuperTankCtem.webp", icon: "SuperTankCtem.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "SuperTankW", nameEn: "Cullen Predator Mk. III", nameRu: "Cullen Predator Mk. III", iconCode: "SuperTankWVehicle.webp", icon: "SuperTankWVehicle.webp", category: "Техника", faction: "Варден", review: false },
  { code: "SurfaceWaterMine", nameEn: "E681-B Hullbreaker Mine", nameRu: "Морская мина E681-B", iconCode: "SurfaceWaterMineIcon.webp", icon: null, category: "Боеприпасы", faction: "Нейтральные", review: true },
  { code: "SwordC", nameEn: "Eleos Infantry Dagger", nameRu: "Eleos Infantry Dagger", iconCode: "StilSwordC.webp", icon: "StilSwordC.webp", category: "Оружие", faction: "Колонисты", review: false },
  { code: "TankMine", nameEn: "Abisme AT-99", nameRu: "Abisme AT-99", iconCode: "AntiTankMine.webp", icon: "AntiTankMine.webp", category: "Оружие", faction: "Нейтральные", review: false },
  { code: "TankUniformC", nameEn: "Tankman's Coveralls", nameRu: "Tankman's Coveralls", iconCode: "TankUniformCIcon.webp", icon: "TankUniformC.webp", category: "Снаряжение", faction: "Колонисты", review: false },
  { code: "TankUniformW", nameEn: "Padded Boiler Suit", nameRu: "форма танкиста", iconCode: "TankUniformWIcon.webp", icon: "TankUniformW.webp", category: "Материалы", faction: "Варден", review: false },
  { code: "TanketteC", nameEn: "T12 “Actaeon” Tankette", nameRu: "T12 “Actaeon” Tankette", iconCode: "TanketteCVehicle.webp", icon: "TanketteCVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TanketteFlameC", nameEn: "T14 “Vesta” Tankette", nameRu: "T14 “Vesta” Tankette", iconCode: "TanketteFlameCIcon.webp", icon: "TanketteFlameC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TanketteMultiC", nameEn: "T13 “Deioneus” Rocket Battery", nameRu: "T13 “Deioneus” Rocket Battery", iconCode: "TanketteMultiCIcon.webp", icon: "TanketteMultiC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TanketteOffensiveC", nameEn: "T20 “Ixion” Tankette", nameRu: "T20 “Ixion” Tankette", iconCode: "TanketteOffensiveCVehicle.webp", icon: "TanketteOffensiveCVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TorpedoAmmo", nameEn: "Moray Torpedo", nameRu: "Moray Torpedo", iconCode: "Torpedo.webp", icon: "Torpedo.webp", category: "Боеприпасы", faction: "Нейтральные", review: false },
  { code: "TrailerLiquid", nameEn: "Rooster - Lamploader", nameRu: "Жидкостный прицеп", iconCode: "TrailerLiquidIcon.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "TrailerMaterial", nameEn: "Rooster - Tumblebox", nameRu: "строительный прицеп", iconCode: "TrailerMaterialIcon.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "TrailerResource", nameEn: "Rooster - Junkwagon", nameRu: "Ресурсный прицеп", iconCode: "TrailerResourceIcon.webp", icon: null, category: "Техника", faction: "Нейтральные", review: true },
  { code: "TrainLRArtillery", nameEn: "Tempest Cannon RA-2", nameRu: "Tempest Cannon RA-2", iconCode: "TrainLRArtilleryVehicle.webp", icon: "TrainLRArtilleryVehicle.webp", category: "Техника", faction: "Нейтральные", review: false },
  { code: "TraumaKit", nameEn: "Trauma Kit", nameRu: "Травма-аптечка", iconCode: "TraumaKitIcon.webp", icon: "TraumaKit.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "Tripod", nameEn: "Tripod", nameRu: "Тренога", iconCode: "TripodIcon.webp", icon: null, category: "Оружие", faction: "Нейтральные", review: true },
  { code: "TruckC", nameEn: "R-1 Hauler", nameRu: "R-1 Hauler", iconCode: "TruckVehicleC.webp", icon: "TruckVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TruckDefensiveW", nameEn: "Dunne Leatherback 2a", nameRu: "Дюна", iconCode: "TruckDefensiveWIcon.webp", icon: "TruckDefensiveW.webp", category: "Техника", faction: "Варден", review: false },
  { code: "TruckLiquidC", nameEn: "RR-3 “Stolon” Tanker", nameRu: "RR-3 “Stolon” Tanker", iconCode: "OilTankerC.webp", icon: "OilTankerC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TruckLiquidW", nameEn: "Dunne Fuelrunner 2d", nameRu: "Дюна бензовоз", iconCode: "OilTankerWar.webp", icon: "OilTankerWar.webp", category: "Техника", faction: "Варден", review: false },
  { code: "TruckMobilityC", nameEn: "R-5b “Sisyphus” Hauler", nameRu: "R-5b “Sisyphus” Hauler", iconCode: "TruckMobilityCVehicle.webp", icon: "TruckMobilityCVehicle.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TruckMobilityW", nameEn: "Dunne Landrunner 12c", nameRu: "Landrunner", iconCode: "TruckMobilityWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "TruckMultiC", nameEn: "R-17 “Retiarius” Skirmisher", nameRu: "R-17 “Retiarius” Skirmisher", iconCode: "TruckMultiCIcon.webp", icon: "TruckMultiC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TruckOffensiveC", nameEn: "R-9 “Speartip” Escort", nameRu: "R-9 “Speartip” Escort", iconCode: "TruckOffensiveVehicleC.webp", icon: "TruckOffensiveVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TruckResourceC", nameEn: "R-5 “Atlas” Hauler", nameRu: "R-5 “Atlas” Hauler", iconCode: "TruckUtilityVehicleC.webp", icon: "TruckUtilityVehicleC.webp", category: "Техника", faction: "Колонисты", review: false },
  { code: "TruckResourceW", nameEn: "Dunne Loadlugger 3c", nameRu: "самосвал", iconCode: "TruckResourceWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "TruckW", nameEn: "Dunne Transport", nameRu: "грузовик", iconCode: "TruckWIcon.webp", icon: null, category: "Техника", faction: "Варден", review: true },
  { code: "Unknown", nameEn: "Неизвестно", nameRu: "Неизвестно", iconCode: "UnknownIcon.webp", icon: null, category: "Другое", faction: "Нейтральные", review: true },
  { code: "Water", nameEn: "Water", nameRu: "вода", iconCode: "WaterIcon.webp", icon: "Water.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "WaterBucket", nameEn: "Water Bucket", nameRu: "Ведро для воды", iconCode: "WaterBucketIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "WaterMine", nameEn: "E680-S Rudder Lock", nameRu: "E680-S Rudder Lock", iconCode: "SeaMine.webp", icon: "SeaMine.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "WaterWallMaterials", nameEn: "Naval Buoy", nameRu: "naval buoy", iconCode: "WaterWallMaterialsIcon.webp", icon: null, category: "Материалы", faction: "Нейтральные", review: true },
  { code: "WindsockT", nameEn: "Wind Sock", nameRu: "Wind Sock", iconCode: "WindsockItem.webp", icon: "WindsockItem.webp", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "Wood", nameEn: "Refined Materials", nameRu: "Refined Materials", iconCode: "RefinedMaterials.webp", icon: "RefinedMaterials.webp", category: "Материалы", faction: "Нейтральные", review: false },
  { code: "WorkHammer", nameEn: "Hammer", nameRu: "Hammer", iconCode: "Hammer.webp", icon: "Hammer.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "WorkWrench", nameEn: "Wrench", nameRu: "Гаечный ключ", iconCode: "WorkWrenchIcon.webp", icon: "WorkWrench.webp", category: "Снаряжение", faction: "Нейтральные", review: false },
  { code: "WoundedCarriedPlayer", nameEn: "Wounded Player", nameRu: "Wounded Player", iconCode: "Wounded.webp", icon: "Wounded.webp", category: "Предметы", faction: "Нейтральные", review: false },
  { code: "Wreckage", nameEn: "Wreckage", nameRu: "Wreckage", iconCode: "Salvage02.webp", icon: "Salvage02.webp", category: "Предметы", faction: "Нейтральные", review: false },
];
