import { ITEM_ICON_OVERRIDES } from "./item-icon-overrides";
import { FOXHOLE_DATA, type FoxholeDataEntry } from "./foxhole-data";

// Официальный реестр Foxhole из item_codes.py — 396 кодов.

export interface ItemConfig {
  name_en: string | null;
  name_ru: string;
  icon: string | null;
  origin: string | null;
}

export const ITEM_CODES: Record<string, ItemConfig> = {
  "AAAmmo": {"name_en": "950-70b Anti-Aircraft Shell", "name_ru": "Зенитный снаряд 950-70b", "icon": "AAAmmo.webp", "origin": "item"},
  "AAGunAI": {"name_en": "Anti-Air Gun", "name_ru": "Anti-Air Gun", "icon": null, "origin": "structure"},
  "ATAmmo": {"name_en": "68mm", "name_ru": "68-мм", "icon": "ATAmmo.webp", "origin": "item"},
  "ATGrenadeW": {"name_en": "BF5 White Ash Flask Grenade", "name_ru": "Граната BF5 White Ash Flask", "icon": "ATGrenadeW.webp", "origin": "item"},
  "ATLargeAmmo": {"name_en": "94.5mm", "name_ru": "94.5мм снаряды", "icon": "ATLargeAmmo.webp", "origin": "item"},
  "ATLaunchedGrenadeW": {"name_en": "B2 Varsi Anti-Tank Grenade", "name_ru": "B2 Varsi Anti-Tank Grenade", "icon": "ATLaunchedGrenadeW.webp", "origin": "item"},
  "ATRPGAmmo": {"name_en": "AP⧸RPG", "name_ru": "АРПГ Снаряды", "icon": "ATRpgAmmo.webp", "origin": "item"},
  "ATRPGC": {"name_en": "Venom c.II 35", "name_ru": "Venom c.II 35", "icon": "ATRpgC.webp", "origin": "item"},
  "ATRPGHeavyC": {"name_en": "Bane 45", "name_ru": "Bane 45", "icon": "ATRpgC.webp", "origin": "item"},
  "ATRPGIndirectAmmo": {"name_en": "ARC⧸RPG", "name_ru": "ARC⧸RPG", "icon": "ATMortarAmmo.webp", "origin": "item"},
  "ATRPGLightC": {"name_en": "Ignifist 30", "name_ru": "Ignifist 30", "icon": "ATRPGLightC.webp", "origin": "item"},
  "ATRPGTW": {"name_en": "Mounted Bonesaw MK.3", "name_ru": "Mounted Bonesaw MK.3", "icon": "ATRPGTW.webp", "origin": "item"},
  "ATRPGW": {"name_en": "Bonesaw MK.3", "name_ru": "Противотанковый РПГ (станковый)", "icon": "ATRPGTW.webp", "origin": "item"},
  "ATRifleAmmo": {"name_en": "14.5mm", "name_ru": "14.5 мм", "icon": "ATRifleAmmo.webp", "origin": "item"},
  "ATRifleAssaultW": {"name_en": "228 Satterley Heavy Storm Rifle", "name_ru": "228 Satterley Heavy Storm Rifle", "icon": "ATRifleAssaultWtga.webp", "origin": "item"},
  "ATRifleAutomaticW": {"name_en": "Booker Greyhound Model 910", "name_ru": "Booker Greyhound Model 910", "icon": "ATRifleAutomaticW.webp", "origin": "item"},
  "ATRifleLightC": {"name_en": "“Dawn” Ve.II", "name_ru": "“Dawn” Ve.II", "icon": "ATRifleLightC.webp", "origin": "item"},
  "ATRifleSniperC": {"name_en": "“Quickhatch” Rt.I", "name_ru": "“Quickhatch” Rt.I", "icon": "ATRifleSniperCtga.webp", "origin": "item"},
  "ATRifleTC": {"name_en": "“Typhon” ra.XII", "name_ru": "“Typhon” ra.XII", "icon": "ATRifleTC.webp", "origin": "item"},
  "ATRifleW": {"name_en": "Neville Anti-Tank Rifle", "name_ru": "противотанковое ружье 20мм", "icon": "ATRifle.webp", "origin": "item"},
  "AirSirenT": {"name_en": "Air Raid Siren", "name_ru": "Air Raid Siren", "icon": "AirSirenT.webp", "origin": "item"},
  "AircraftAmmo": {"name_en": "20mm", "name_ru": "20мм", "icon": "AircraftAmmo.webp", "origin": "item"},
  "AircraftBomberC": {"name_en": "V-1 Tzykalia", "name_ru": "V-1 Tzykalia", "icon": "AircraftBomberC.webp", "origin": "vehicle"},
  "AircraftBomberW": {"name_en": "Tulka P4 Welkinrive", "name_ru": "Tulka P4 Welkinrive", "icon": "AircraftBomberW.webp", "origin": "vehicle"},
  "AircraftDepot": {"name_en": "Aircraft Depot", "name_ru": "Aircraft Depot", "icon": "AircraftDepot.png", "origin": "structure"},
  "AircraftDiveC": {"name_en": "Mergo-4 “Myrmidon”", "name_ru": "Mergo-4 “Myrmidon”", "icon": "AircraftDiveC.webp", "origin": "vehicle"},
  "AircraftFactory": {"name_en": "Aircraft Hangar", "name_ru": "Aircraft Hangar", "icon": "AircraftFactory.webp", "origin": "structure"},
  "AircraftFighterC": {"name_en": "Toxot-902 “Blind Silver”", "name_ru": "Toxot-902 “Blind Silver”", "icon": "AircraftFigtherC.webp", "origin": "vehicle"},
  "AircraftFighterW": {"name_en": "Luminary Mk. II Harbinger", "name_ru": "Luminary Mk. II Harbinger", "icon": "AircraftFighterWIcon.webp", "origin": "vehicle"},
  "AircraftParatrooperC": {"name_en": "V-5b Pegasus", "name_ru": "V-5b Pegasus", "icon": "AircraftParatrooperCIcon.webp", "origin": "vehicle"},
  "AircraftParatrooperW": {"name_en": "Rinnspeir Mk. I Zealot", "name_ru": "Rinnspeir Mk. I Zealot", "icon": "AircraftParatrooperWIcon.webp", "origin": "vehicle"},
  "AircraftScout2C": {"name_en": "A59 Venti “Perdix”", "name_ru": "A59 Venti “Perdix”", "icon": "AircraftScout2CIcon.webp", "origin": "vehicle"},
  "AircraftScout2W": {"name_en": "Luminary Mk. VI Emissary", "name_ru": "Luminary Mk. VI Emissary", "icon": "AircraftScout2WIcon.webp", "origin": "vehicle"},
  "AircraftScoutC": {"name_en": "A51 Venti “Daedalus”", "name_ru": "A51 Venti “Daedalus”", "icon": null, "origin": "vehicle"},
  "AircraftScoutW": {"name_en": "Luminary Mk. IV Herald", "name_ru": "Luminary Mk. IV Herald", "icon": null, "origin": "vehicle"},
  "AircraftTorpedoAmmo": {"name_en": "Tenta Torpedo", "name_ru": "Tenta Torpedo", "icon": "AircraftTorpedoAmmo.webp", "origin": "item"},
  "AircraftTorpedoW": {"name_en": "M925 Austringer Man-O-War", "name_ru": "M925 Austringer Man-O-War", "icon": null, "origin": "vehicle"},
  "AircraftWaterW": {"name_en": "Tulka I1.9 White Raven", "name_ru": "Tulka I1.9 White Raven", "icon": null, "origin": "vehicle"},
  "Aluminum": {"name_en": "Aluminum", "name_ru": "Aluminum", "icon": null, "origin": "item"},
  "AluminumA": {"name_en": "Aluminum Alloy", "name_ru": "Алюминий", "icon": "AlyuminievyySplav.png", "origin": "item"},
  "AmbulanceC": {"name_en": "R-12 - “Salus” Ambulance", "name_ru": "R-12 - “Salus” Ambulance", "icon": null, "origin": "vehicle"},
  "AmbulanceFlameC": {"name_en": "R-12b - “Salva” Flame Truck", "name_ru": "R-12b - “Salva” Flame Truck", "icon": "AmbulanceFlameC.webp", "origin": "vehicle"},
  "AmbulanceFlameW": {"name_en": "Dunne Dousing Engine 3r", "name_ru": "пожарная машина", "icon": "AmbulanceFlameW.webp", "origin": "vehicle"},
  "AmbulanceW": {"name_en": "Dunne Responder 3e", "name_ru": "скорая помощь", "icon": "Ambulance.webp", "origin": "vehicle"},
  "AmmoUniformW": {"name_en": "Specialist's Overcoat", "name_ru": "шинель специалиста", "icon": "AmmoUniformW.webp", "origin": "item"},
  "ArmoredCar2LargeW": {"name_en": "O'Brien V.101 Freeman", "name_ru": "бронированная дюна", "icon": null, "origin": "vehicle"},
  "ArmoredCar2MultiW": {"name_en": "O'Brien V.200 Squire", "name_ru": "O'Brien V.200 Squire", "icon": "ArmoredCar2MultiW.webp", "origin": "vehicle"},
  "ArmoredCar2TwinW": {"name_en": "O'Brien V.190 Knave", "name_ru": "O'Brien V.101 Freeman / Twin AC", "icon": "ArmoredCarTwinW.webp", "origin": "vehicle"},
  "ArmoredCarATW": {"name_en": "O'Brien V.113 Gravekeeper", "name_ru": "O'Brien V.113 Gravekeeper", "icon": null, "origin": "vehicle"},
  "ArmoredCarC": {"name_en": "T3 “Xiphos”", "name_ru": "T3 “Xiphos”", "icon": null, "origin": "vehicle"},
  "ArmoredCarFlameW": {"name_en": "O'Brien V.130 Wild Jack", "name_ru": "Бронеавтомобиль с огнемётом", "icon": "ArmoredCarFlameWarVehicleW.webp", "origin": "vehicle"},
  "ArmoredCarMobilityW": {"name_en": "O'Brien V.121 Highlander", "name_ru": "Мобильная бронемашина", "icon": "ArmoredCarMobilityWarVehicleW.webp", "origin": "vehicle"},
  "ArmoredCarOffensiveC": {"name_en": "T5 “Percutio”", "name_ru": "T5 “Percutio”", "icon": null, "origin": "vehicle"},
  "ArmoredCarTwinC": {"name_en": "T8 “Gemini”", "name_ru": "T8 “Gemini”", "icon": "ArmoredCarTwinC.webp", "origin": "vehicle"},
  "ArmoredCarW": {"name_en": "O'Brien V.110", "name_ru": "O", "icon": "ArmoredCarWarVehicleW.webp", "origin": "vehicle"},
  "ArmourUniformC": {"name_en": "Velian Flak Vest", "name_ru": "Velian Flak Vest", "icon": "ArmourUniformC.webp", "origin": "item"},
  "ArmourUniformW": {"name_en": "Gunner's Breastplate", "name_ru": "Стальная кираса", "icon": "ArmourUniformW.webp", "origin": "item"},
  "AssaultRifleAmmo": {"name_en": "7.92mm", "name_ru": "7.92-мм", "icon": "AssaultRifleAmmo.webp", "origin": "item"},
  "AssaultRifleC": {"name_en": "Catara mo.II", "name_ru": "Catara mo.II", "icon": null, "origin": "item"},
  "AssaultRifleHeavyC": {"name_en": "“Dusk” ce.III", "name_ru": "“Dusk” ce.III", "icon": "AssaultRifleHeavyC.webp", "origin": "item"},
  "AssaultRifleHeavyW": {"name_en": "Booker Storm Rifle Model 838", "name_ru": "Booker Storm Rifle Model 838", "icon": null, "origin": "item"},
  "AssaultRifleW": {"name_en": "Aalto Storm Rifle 24", "name_ru": "Aalto Storm Rifle 24", "icon": null, "origin": "item"},
  "Bandages": {"name_en": "Bandages", "name_ru": "бинт", "icon": "Bandages.webp", "origin": "item"},
  "BannerTW": {"name_en": "War Ensign", "name_ru": "War Ensign", "icon": null, "origin": "item"},
  "BarbedWireMaterials": {"name_en": "Barbed Wire", "name_ru": "колючая проволока", "icon": "BarbedWireMaterial.webp", "origin": "item"},
  "Barge": {"name_en": "BMS - Aquatipper", "name_ru": "баржа", "icon": "BargeVehicle.webp", "origin": "vehicle"},
  "BattleTankATC": {"name_en": "Lance-25 “Hasta”", "name_ru": "Lance-25 “Hasta”", "icon": "BattleTankATC.webp", "origin": "vehicle"},
  "BattleTankAmmo": {"name_en": "75mm", "name_ru": "75mm", "icon": "BattleTankAmmo.webp", "origin": "item"},
  "BattleTankC": {"name_en": "Lance-36", "name_ru": "Lance-36", "icon": "BattleTankC.webp", "origin": "vehicle"},
  "BattleTankDefensiveW": {"name_en": "Flood Juggernaut Mk. VII", "name_ru": "Flood Juggernaut Mk. VII", "icon": null, "origin": "vehicle"},
  "BattleTankHeavyArtilleryC": {"name_en": "Lance-46 “Sarissa”", "name_ru": "Lance-46 “Sarissa”", "icon": "BattleTankHeavyArtilleryC.webp", "origin": "vehicle"},
  "BattleTankHeavyArtilleryW": {"name_en": "Flood Mk. IX Stain", "name_ru": "Flood Mk. IX Stain", "icon": "BattleTankHeavyArtilleryW.webp", "origin": "vehicle"},
  "BattleTankW": {"name_en": "Flood Mk. I", "name_ru": "Flood Mk. I", "icon": null, "origin": "vehicle"},
  "Bayonet": {"name_en": "Buckhorn CCQ-18", "name_ru": "штык-нож", "icon": "Bayonet.webp", "origin": "item"},
  "Bicycle": {"name_en": "Blumfield LK205", "name_ru": "Blumfield LK205", "icon": null, "origin": "vehicle"},
  "Binoculars": {"name_en": "Binoculars", "name_ru": "бинокль", "icon": "Binoculars.webp", "origin": "item"},
  "BloodPlasma": {"name_en": "Blood Plasma", "name_ru": "Плазма", "icon": "BloodPlasma.webp", "origin": "item"},
  "BomberAmmo": {"name_en": "Mark II Raidbreaker", "name_ru": "Mark II Raidbreaker", "icon": null, "origin": "item"},
  "BusC": {"name_en": "R-15 - “Chariot”", "name_ru": "R-15 - “Chariot”", "icon": "BusC.webp", "origin": "vehicle"},
  "BusW": {"name_en": "Dunne Caravaner 2f", "name_ru": "автобус", "icon": "BusWar.webp", "origin": "vehicle"},
  "Cloth": {"name_en": "Basic Materials", "name_ru": "Базовые материалы", "icon": "Cloth.webp", "origin": "item"},
  "Coal": {"name_en": "Coal", "name_ru": "Coal", "icon": null, "origin": "item"},
  "Components": {"name_en": "Components", "name_ru": "Компоненты", "icon": null, "origin": "item"},
  "Concrete": {"name_en": "Concrete Materials", "name_ru": "Concrete Materials", "icon": null, "origin": "item"},
  "ConcreteMixer": {"name_en": null, "name_ru": "Бетономешалка", "icon": "Betonomeshalka.png", "origin": null},
  "Construction": {"name_en": "BMS - Universal Assembly Rig", "name_ru": "CV (тир 1)", "icon": "ConstructionVehicle.webp", "origin": "vehicle"},
  "ConstructionEquipment": {"name_en": null, "name_ru": "Строительное оборудование", "icon": "StroitelnoeOborudovanie.png", "origin": null},
  "ConstructionUtility": {"name_en": "BMS - Fabricator", "name_ru": "Строительная техника", "icon": null, "origin": "vehicle"},
  "Copper": {"name_en": "Copper", "name_ru": "Copper", "icon": null, "origin": "item"},
  "CopperA": {"name_en": "Copper Alloy", "name_ru": "Медь", "icon": "MednyySplav.png", "origin": "item"},
  "Crane": {"name_en": "BMS - Class 2 Mobile Auto-Crane", "name_ru": "Мобильный автокран БМС 2 класса", "icon": "CraneVehicle.webp", "origin": "vehicle"},
  "Crate": {"name_en": "Crate", "name_ru": "Crate", "icon": null, "origin": "item"},
  "CriticalSoldier": {"name_en": "Critically Wounded Soldier", "name_ru": "Critically Wounded Soldier", "icon": null, "origin": "item"},
  "DemolitionRocketAmmo": {"name_en": "Shatter Missile", "name_ru": "Разрушающая ракета", "icon": "DemolitionRocketAmmo.webp", "origin": "item"},
  "DeployedATRifleTC": {"name_en": "Deployed “Typhon” ra.XII", "name_ru": "Deployed “Typhon” ra.XII", "icon": null, "origin": "structure"},
  "DepthChargeAmmo": {"name_en": "Model-7 “Evie”", "name_ru": "Model-7 “Evie”", "icon": null, "origin": "item"},
  "DestroyerTankFlameW": {"name_en": "Noble Firebrand Mk. XVII", "name_ru": "Noble Firebrand Mk. XVII", "icon": "DestroyerTankFlameW.webp", "origin": "vehicle"},
  "DestroyerTankW": {"name_en": "Noble Widow MK. XIV", "name_ru": "Noble Widow MK. XIV", "icon": null, "origin": "vehicle"},
  "Diesel": {"name_en": "Diesel", "name_ru": "Дизель", "icon": "ResourceFuel.webp", "origin": "item"},
  "DiveBomberAmmo": {"name_en": "912 Shrike Rounds", "name_ru": "912 Shrike Rounds", "icon": "DiveBomberAmmo.webp", "origin": "item"},
  "EmplacedATLargeW": {"name_en": "Huber Starbreaker 94.5mm", "name_ru": "Huber Starbreaker 94.5", "icon": "HuberStarbreaker94.5.png", "origin": "structure"},
  "EmplacedATW": {"name_en": "Leary Shellbore 68mm", "name_ru": "Leary Shellbore 68-мм", "icon": "EmplacedAT.webp", "origin": "structure"},
  "EmplacedAircraftC": {"name_en": "DAE 5b “Zeal”", "name_ru": "DAE 5b Zeal", "icon": "DAE5bZeal.png", "origin": "structure"},
  "EmplacedAircraftW": {"name_en": "Leary AA-70 Bolas", "name_ru": "Leary AA-70 Bolas", "icon": "LearyAA70Bolas.png", "origin": "structure"},
  "EmplacedCannonLargeC": {"name_en": "DAE 2a-1 “Ruptura”", "name_ru": "DAE 2a-1 Ruptura", "icon": "DAE2a1Ruptura.png", "origin": "structure"},
  "EmplacedHeavyArtilleryC": {"name_en": "50-500 “Thunderbolt” Cannon", "name_ru": "50-500 Thunderbolt Cannon", "icon": "50500ThunderboltCannon.png", "origin": "structure"},
  "EmplacedHeavyArtilleryW": {"name_en": "Huber Exalt 150mm", "name_ru": "Huber Exalt 150mm", "icon": "HuberExalt150mm.png", "origin": "structure"},
  "EmplacedIndirectC": {"name_en": "DAE 1o-3 “Polybolos”", "name_ru": "DAE 1o-3 Polybolos", "icon": "DAE1o3Polybolos.png", "origin": "structure"},
  "EmplacedInfantryC": {"name_en": "DAE 1b-2 “Serra”", "name_ru": "DAE 1b-2 Serra", "icon": "DAE1b2Serra.png", "origin": "structure"},
  "EmplacedInfantryW": {"name_en": "Leary Snare Trap 20", "name_ru": "Leary Snare Trap 20", "icon": "EmplacedMG.webp", "origin": "structure"},
  "EmplacedLightArtilleryW": {"name_en": "Huber Lariat 120mm", "name_ru": "Huber Lariat 120мм", "icon": "HuberLariat120mm.png", "origin": "structure"},
  "EmplacedMultiC": {"name_en": "DAE 3b-2 “Hades' Net”", "name_ru": "DAE 3b-2 Hades Net", "icon": "DAE3b2HadesNet.png", "origin": "structure"},
  "EngineerUniformC": {"name_en": "Fabri Rucksack", "name_ru": "Fabri Rucksack", "icon": "EngineerUniformC.webp", "origin": "item"},
  "EngineerUniformW": {"name_en": "Sapper Gear", "name_ru": "Сапёрное снаряжение", "icon": "EngineerUniformW.webp", "origin": "item"},
  "Explosive": {"name_en": "Explosive Powder", "name_ru": "порох", "icon": "ExplosiveTripod.webp", "origin": "item"},
  "ExplosiveLightC": {"name_en": "Hydra's Whisper", "name_ru": "Hydra's Whisper", "icon": null, "origin": "item"},
  "ExplosiveTripod": {"name_en": null, "name_ru": "Станковый Fissura gd.I", "icon": "ExplosiveTripod.webp", "origin": null},
  "FacilityCoal1": {"name_en": "Coke", "name_ru": "Coke", "icon": null, "origin": "item"},
  "FacilityComponents1": {"name_en": "Damaged Components", "name_ru": "Damaged Components", "icon": null, "origin": "item"},
  "FacilityMaterials1": {"name_en": "Construction Materials", "name_ru": "Сборочные материалы I", "icon": "FacilityMaterials10.webp", "origin": "item"},
  "FacilityMaterials10": {"name_en": "Unstable Substances", "name_ru": "Unstable Substances", "icon": "FacilityMaterials10.webp", "origin": "item"},
  "FacilityMaterials12": {"name_en": "Rare Materials", "name_ru": "Rare Materials", "icon": "FacilityMaterials12.webp", "origin": "item"},
  "FacilityMaterials3": {"name_en": "Steel Construction Materials", "name_ru": "Steel Construction Materials", "icon": null, "origin": "item"},
  "FacilityMaterials4": {"name_en": "Assembly Materials I", "name_ru": "Сборочные материалы IV", "icon": "FacilityMaterials09.webp", "origin": "item"},
  "FacilityMaterials5": {"name_en": "Assembly Materials II", "name_ru": "Assembly Materials II", "icon": null, "origin": "item"},
  "FacilityMaterials6": {"name_en": "Assembly Materials III", "name_ru": "Assembly Materials III", "icon": null, "origin": "item"},
  "FacilityMaterials7": {"name_en": "Assembly Materials IV", "name_ru": "Assembly Materials IV", "icon": null, "origin": "item"},
  "FacilityMaterials8": {"name_en": "Assembly Materials V", "name_ru": "Assembly Materials V", "icon": null, "origin": "item"},
  "FacilityMaterials9": {"name_en": "Rare Alloys", "name_ru": "Rare Alloys", "icon": null, "origin": "item"},
  "FacilityOil1": {"name_en": "Heavy Oil", "name_ru": "Нефть для объекта I", "icon": "Neft.png", "origin": "item"},
  "FacilityOil2": {"name_en": "Enriched Oil", "name_ru": "Обогащенное топливо", "icon": "Neft.png", "origin": "item"},
  "FacilityOil3": {"name_en": null, "name_ru": "Нефть для объекта III", "icon": "Neft.png", "origin": null},
  "FacilityPower": {"name_en": "Facility Power", "name_ru": "Facility Power", "icon": null, "origin": "item"},
  "FieldAT2C": {"name_en": "GA6 “Cestus”", "name_ru": "GA6 “Cestus”", "icon": "FieldAT2C.webp", "origin": "vehicle"},
  "FieldAT2W": {"name_en": "Duncan's Coin 14.5mm", "name_ru": "Duncan's Coin 14.5mm", "icon": "FieldAT2W.webp", "origin": "vehicle"},
  "FieldATC": {"name_en": "AA-2 Battering Ram", "name_ru": "AA-2 Battering Ram", "icon": null, "origin": "vehicle"},
  "FieldATDamageW": {"name_en": "Balfour Rampart 68mm", "name_ru": "Balfour Rampart 68mm", "icon": null, "origin": "vehicle"},
  "FieldATW": {"name_en": "Collins Cannon 68mm", "name_ru": "Полевая противотанковая пушка", "icon": "FieldAT2W.webp", "origin": "vehicle"},
  "FieldCannonDamageC": {"name_en": "40-45 “Smelter”", "name_ru": "40-45 “Smelter”", "icon": null, "origin": "vehicle"},
  "FieldCannonW": {"name_en": "Balfour Wolfhound 40mm", "name_ru": "Полевое орудие", "icon": "FieldCannonWVehicle.webp", "origin": "vehicle"},
  "FieldMGC": {"name_en": "G40 “Sagittarii”", "name_ru": "G40 “Sagittarii”", "icon": null, "origin": "vehicle"},
  "FieldMGW": {"name_en": "Swallowtail 988/127-2", "name_ru": "Полевой пулемёт", "icon": null, "origin": "vehicle"},
  "FieldMortarC": {"name_en": "30-250 “Tisiphone” Field Cannon", "name_ru": "30-250 “Tisiphone” Field Cannon", "icon": "FieldMortarC.webp", "origin": "vehicle"},
  "FieldMortarW": {"name_en": "Balfour Falconer 250mm", "name_ru": "Balfour Falconer 250mm", "icon": "FieldMortarW.webp", "origin": "vehicle"},
  "FirePitT2": {"name_en": "Field Range", "name_ru": "Field Range", "icon": null, "origin": "structure"},
  "FireRocketAmmo": {"name_en": "4C-Fire Rocket", "name_ru": "4C-Fire Rocket", "icon": null, "origin": "item"},
  "FirstAidKit": {"name_en": "First Aid Kit", "name_ru": "Набор Первой Помощи", "icon": "FirstAidKit.webp", "origin": "item"},
  "FlameAmmo": {"name_en": "Flame Ammo", "name_ru": "Огненные патроны", "icon": "FlameAmmo.webp", "origin": "item"},
  "FlameBackpackC": {"name_en": "“Molten Wind” v.II Ammo", "name_ru": "“Molten Wind” v.II Ammo", "icon": null, "origin": "item"},
  "FlameBackpackW": {"name_en": "Willow's Bane Ammo", "name_ru": "Топливо для Willow", "icon": "FlamePackW.webp", "origin": "item"},
  "FlameTorchC": {"name_en": "“Molten Wind” v.II Flame Torch", "name_ru": "“Molten Wind” v.II Flame Torch", "icon": null, "origin": "item"},
  "FlameTorchW": {"name_en": "Willow's Bane Model 845", "name_ru": "Willow's Bane Model 845", "icon": null, "origin": "item"},
  "FlatbedTruck": {"name_en": "BMS - Packmule Flatbed", "name_ru": "Флэтбед (пакмул)", "icon": "FlatbedTruckVehicle.webp", "origin": "vehicle"},
  "FortConstructionPart": {"name_en": null, "name_ru": "Строительные детали", "icon": "StroitelnyeDetali.png", "origin": null},
  "FortGarrisonStationPart": {"name_en": null, "name_ru": "Детали подземной крепости", "icon": "DetaliPodzemnoyKreposti.png", "origin": null},
  "FortIntelCenterPart": {"name_en": null, "name_ru": "Разведывательный Центр", "icon": "RazvedyvatelnyyTsentr.png", "origin": null},
  "FortLRArtilleryPart": {"name_en": null, "name_ru": "Детали Штурмового Орудия", "icon": "DetaliShturmovogoOrudiya.png", "origin": null},
  "FortLargeRadarPart": {"name_en": null, "name_ru": "SC-3 Aerial Interceptor Array Parts", "icon": "SC3AerialInterceptorArrayParts.png", "origin": null},
  "FortWeatherStationPart": {"name_en": null, "name_ru": "Детали погодной станции", "icon": "DetaliPogodnoyStantsii.png", "origin": null},
  "Freighter": {"name_en": "BMS - Ironship", "name_ru": "судно Ironship", "icon": "Freighter02Item.webp", "origin": "vehicle"},
  "FreighterLight": {"name_en": "Das Krokodil by VAC", "name_ru": "судно Krokodil", "icon": "LightFreighterVehicle.webp", "origin": "vehicle"},
  "GasMask": {"name_en": "Gas Mask", "name_ru": "противогаз", "icon": "Gasmask.webp", "origin": "item"},
  "GasMaskFilter": {"name_en": "Gas Mask Filter", "name_ru": "Фильтр для противогаза", "icon": "GasMaskFilter.webp", "origin": "item"},
  "GreenAsh": {"name_en": "Green Ash Grenade", "name_ru": "газовая граната", "icon": "DeadlyGas01.webp", "origin": "item"},
  "GrenadeAdapter": {"name_en": null, "name_ru": "Подствольный гранатомёт", "icon": "GrenadeAdapter.webp", "origin": null},
  "GrenadeC": {"name_en": "Bomastone Grenade", "name_ru": "Bomastone Grenade", "icon": "GrenadeC.webp", "origin": "item"},
  "GrenadeLauncherC": {"name_en": "KLG901-2 Lunaire F", "name_ru": "KLG901-2 Lunaire F", "icon": "GrenadeLauncherC.webp", "origin": "item"},
  "GrenadeLauncherTC": {"name_en": "Mounted Fissura gd.I", "name_ru": "Mounted Fissura gd.I", "icon": "GrenadeLauncherTC.webp", "origin": "item"},
  "GrenadeUniformC": {"name_en": "Grenadier's Baldric", "name_ru": "Grenadier's Baldric", "icon": "GrenadeUniformC.webp", "origin": "item"},
  "GrenadeW": {"name_en": "A3 Harpa Fragmentation Grenade", "name_ru": "Осколочная граната", "icon": "GrenadeW.webp", "origin": "item"},
  "GroundMaterials": {"name_en": "Gravel", "name_ru": "гравий", "icon": "GroundMaterials.webp", "origin": "item"},
  "Gunboat2C": {"name_en": "Type B - “Lucian”", "name_ru": "Type B - “Lucian”", "icon": null, "origin": "vehicle"},
  "Gunboat2W": {"name_en": "81f-f Ronan Blackguard", "name_ru": "БТР-Амфибия (Mulloy)", "icon": "Gunboat2W.webp", "origin": "vehicle"},
  "GunboatC": {"name_en": "Type C - “Charon”", "name_ru": "Type C - “Charon”", "icon": null, "origin": "vehicle"},
  "GunboatW": {"name_en": "74b-1 Ronan Gunship", "name_ru": "74b-1 Ronan Gunship", "icon": "GunboatW.webp", "origin": "vehicle"},
  "HEGrenade": {"name_en": "Mammon 91-b", "name_ru": "Маммонка", "icon": "HEGrenade.webp", "origin": "item"},
  "HELaunchedGrenade": {"name_en": "Tremola Grenade GPb-1", "name_ru": "Осколочный снаряд РПГ", "icon": "HELaunchedGrenade.webp", "origin": "item"},
  "HERocketAmmo": {"name_en": "3C-High Explosive Rocket", "name_ru": "3C-High Explosive Rocket", "icon": "HERocketAmmo.webp", "origin": "item"},
  "HalfTrackArtilleryC": {"name_en": "HH-d “Peltast”", "name_ru": "HH-d “Peltast”", "icon": "HalfTrackArtilleryC.webp", "origin": "vehicle"},
  "HalfTrackC": {"name_en": "HH-a “Javelin”", "name_ru": "HH-a “Javelin”", "icon": null, "origin": "vehicle"},
  "HalfTrackDefensiveC": {"name_en": "HH-b “Hoplite”", "name_ru": "HH-b “Hoplite”", "icon": null, "origin": "vehicle"},
  "HalfTrackOffensiveW": {"name_en": "Niska Mk. II Blinder", "name_ru": "Niska Mk. II Blinder", "icon": null, "origin": "vehicle"},
  "HalfTrackTwinW": {"name_en": "Niska Mk. III Scar Twin", "name_ru": "Niska Mk. III Scar Twin", "icon": "HalftrackTwinW.webp", "origin": "vehicle"},
  "HalfTrackW": {"name_en": "Niska Mk. I Gun Motor Carriage", "name_ru": "Полугусеничный бронеавтомобиль", "icon": "HalfTrackWarVehicle.webp", "origin": "vehicle"},
  "HalftrackMultiW": {"name_en": "Niska-Rycker Mk. IX Skycaller", "name_ru": "Niska-Rycker Mk. IX Skycaller", "icon": "HalftrackMultiW.webp", "origin": "vehicle"},
  "Harvester": {"name_en": "BMS - Scrap Hauler", "name_ru": "BMS - Scrap Hauler", "icon": "Harvester.webp", "origin": "vehicle"},
  "HeavyArtilleryAmmo": {"name_en": "150mm", "name_ru": "150-мм", "icon": "HeavyArtilleryAmmo.webp", "origin": "item"},
  "HeavyExplosive": {"name_en": "Heavy Explosive Powder", "name_ru": "Тяжёлая взрывчатка", "icon": "HeavyExplosiveMaterials.webp", "origin": "item"},
  "HeavyTruckC": {"name_en": "AU-A150 Taurine Rigger", "name_ru": "AU-A150 Taurine Rigger", "icon": null, "origin": "vehicle"},
  "HeavyTruckW": {"name_en": "Cnute Cliffwrest", "name_ru": "кнут", "icon": "HeavyTruckW.webp", "origin": "vehicle"},
  "ISGTC": {"name_en": "Daucus isg.III", "name_ru": "Daucus isg.III", "icon": null, "origin": "item"},
  "In06KItem": {"name_en": "Blackened Runestone", "name_ru": "Blackened Runestone", "icon": null, "origin": "item"},
  "InfantryMine": {"name_en": "Crow's Foot Mine", "name_ru": "Crow's Foot Mine", "icon": "InfantryMine.webp", "origin": "item"},
  "Iron": {"name_en": "Iron", "name_ru": "Iron", "icon": null, "origin": "item"},
  "IronA": {"name_en": "Iron Alloy", "name_ru": "Iron Alloy", "icon": null, "origin": "item"},
  "LRArtillery": {"name_en": "Storm Cannon", "name_ru": "Storm Cannon", "icon": null, "origin": "structure"},
  "LRArtilleryAmmo": {"name_en": "300mm", "name_ru": "300mm", "icon": "LRArtilleryAmmo.webp", "origin": "item"},
  "LandingCraftC": {"name_en": "AB-8 “Acheron”", "name_ru": "десантный катер", "icon": null, "origin": "vehicle"},
  "LandingCraftOffensiveC": {"name_en": "AB-11 “Doru”", "name_ru": "AB-11 “Doru”", "icon": null, "origin": "vehicle"},
  "LandingCraftW": {"name_en": "Mulloy LPC", "name_ru": "БТР-Амфибия (Mulloy)", "icon": "LandingCraftWarVehicleW.webp", "origin": "vehicle"},
  "LandingShipC": {"name_en": "Interceptor PA-12", "name_ru": "Interceptor PA-12", "icon": "LandingShipC.webp", "origin": "vehicle"},
  "LandingShipW": {"name_en": "MacConmara Shorerunner", "name_ru": "MacConmara Shorerunner", "icon": "LandingShipW.webp", "origin": "vehicle"},
  "LargeCrane": {"name_en": "BMS - Overseer Sky-Hauler", "name_ru": "BMS - Overseer Sky-Hauler", "icon": null, "origin": "vehicle"},
  "LargeFieldATC": {"name_en": "945g “Stygian Bolt”", "name_ru": "945g “Stygian Bolt”", "icon": null, "origin": "vehicle"},
  "LargeFieldCannonW": {"name_en": "Balfour Stockade 75mm", "name_ru": "Balfour Stockade 75mm", "icon": null, "origin": "vehicle"},
  "LargeFieldLightArtilleryC": {"name_en": "120-68 “Koronides” Field Gun", "name_ru": "120-68 “Koronides” Field Gun", "icon": null, "origin": "vehicle"},
  "LargeFieldMortarC": {"name_en": "40-250 “Alekto” Heavy Cannon", "name_ru": "40-250 “Alekto” Heavy Cannon", "icon": "LargeFieldMortarC.webp", "origin": "vehicle"},
  "LargeFieldMultiW": {"name_en": "Rycker 4/3-F Wasp Nest", "name_ru": "Полевая многозарядная установка", "icon": null, "origin": "vehicle"},
  "LargeShipAircraftC": {"name_en": "Poseidon", "name_ru": "Poseidon", "icon": null, "origin": "vehicle"},
  "LargeShipBaseShip": {"name_en": "BMS - Longhook", "name_ru": "BMS - Longhook", "icon": null, "origin": "vehicle"},
  "LargeShipBattleshipAircraftW": {"name_en": "Mercy", "name_ru": "Mercy", "icon": null, "origin": "vehicle"},
  "LargeShipDestroyerW": {"name_en": "Blacksteele", "name_ru": "Blacksteele", "icon": null, "origin": "vehicle"},
  "LargeShipResourceShip": {"name_en": "BMS - Bowhead", "name_ru": "BMS - Bowhead", "icon": null, "origin": "vehicle"},
  "LargeShipStorageShip": {"name_en": "BMS - Bluefin", "name_ru": "BMS - Bluefin", "icon": null, "origin": "vehicle"},
  "LightAAAmmo": {"name_en": "Absol Anti-Aircraft Rounds", "name_ru": "Зенитный снаряд “Absol”", "icon": "LightAAAmmo.webp", "origin": "item"},
  "LightArtilleryAmmo": {"name_en": "120mm", "name_ru": "120-мм", "icon": "LightArtilleryAmmo.webp", "origin": "item"},
  "LightBoatInfantryC": {"name_en": "K-81e “Sombre”", "name_ru": "K-81e “Sombre”", "icon": "LightBoatInfantryC.webp", "origin": "vehicle"},
  "LightBoatInfantryW": {"name_en": "68A-4 Ronan Fathomer", "name_ru": "лёгкая пехотная лодка", "icon": "LightBoatInfantryWVehicle.webp", "origin": "vehicle"},
  "LightTank2InfantryC": {"name_en": "HC-2 “Scorpion”", "name_ru": "HC-2 “Scorpion”", "icon": null, "origin": "vehicle"},
  "LightTank3C": {"name_en": "HA-1 “Sagaris”", "name_ru": "HA-1 “Sagaris”", "icon": null, "origin": "vehicle"},
  "LightTank3W": {"name_en": "Sharkey-Devitt Birdeater Mk. I", "name_ru": "Sharkey-Devitt Birdeater Mk. I", "icon": null, "origin": "vehicle"},
  "LightTankAmmo": {"name_en": "40mm", "name_ru": "40-мм", "icon": "LightTankAmmo.webp", "origin": "item"},
  "LightTankArtilleryW": {"name_en": "Devitt-Caine Mk. IV MMR", "name_ru": "Легкий арт-танк", "icon": "LightTankArtilleryWar.webp", "origin": "vehicle"},
  "LightTankC": {"name_en": "H-5 “Hatchet”", "name_ru": "строительный прицеп", "icon": "LightTankColVehicle.webp", "origin": "vehicle"},
  "LightTankDefensiveW": {"name_en": "Devitt Ironhide Mk. IV", "name_ru": "Devitt Ironhide Mk. IV", "icon": null, "origin": "vehicle"},
  "LightTankFlameC": {"name_en": "H-19 “Vulcan”", "name_ru": "H-19 “Vulcan”", "icon": "LightTankFlameC.webp", "origin": "vehicle"},
  "LightTankMobilityC": {"name_en": "H-8 “Kranesca”", "name_ru": "H-8 “Kranesca”", "icon": null, "origin": "vehicle"},
  "LightTankOffensiveC": {"name_en": "H-10 “Pelekys”", "name_ru": "H-10 “Pelekys”", "icon": null, "origin": "vehicle"},
  "LightTankW": {"name_en": "Devitt Mk. III", "name_ru": "Devitt Mk. III", "icon": null, "origin": "vehicle"},
  "LiquidContainer": {"name_en": "Liquid Container", "name_ru": "Жидкостный контейнер", "icon": "ZhidkostnyyKonteyner.png", "origin": "structure"},
  "ListeningKit": {"name_en": "Listening Kit", "name_ru": "Набор для прослушивания", "icon": "ListeningKit.webp", "origin": "item"},
  "MGAmmo": {"name_en": "12.7mm", "name_ru": "12.7 мм (пулемётные) патроны", "icon": "MachineGunAmmo.webp", "origin": "item"},
  "MGC": {"name_en": "KRN886-127 Gast Machine Gun", "name_ru": "KRN886-127 Gast Machine Gun", "icon": null, "origin": "item"},
  "MGTC": {"name_en": "Lamentum mm.IV", "name_ru": "Lamentum mm.IV", "icon": null, "origin": "item"},
  "MGTW": {"name_en": "Malone Ratcatcher MK.1", "name_ru": "Станковый пулемет варденов", "icon": "MGW.webp", "origin": "item"},
  "MGW": {"name_en": "Malone MK.2", "name_ru": "Malone MK.2", "icon": "MGW.webp", "origin": "item"},
  "MaceW": {"name_en": "Falias Raiding Club", "name_ru": "Falias Raiding Club", "icon": null, "origin": "item"},
  "MaintenanceSupplies": {"name_en": "Maintenance Supplies", "name_ru": "Припасы Обслуживания", "icon": "MaintenanceSupplies.webp", "origin": "item"},
  "MaterialPlatform": {"name_en": "Material Pallet", "name_ru": "Поддон для материалов", "icon": "MaterialPlatform.webp", "origin": "structure"},
  "MedicUniformC": {"name_en": "Medic Fatigues", "name_ru": "Medic Fatigues", "icon": "MedicUniformC.webp", "origin": "item"},
  "MedicUniformW": {"name_en": "Physician's Jacket", "name_ru": "Куртка врача", "icon": "MedicUniformW.webp", "origin": "item"},
  "MediumBoatC": {"name_en": "Strider", "name_ru": "пожарная машина", "icon": "MediumBoatC.webp", "origin": "vehicle"},
  "MediumBoatW": {"name_en": "Rinnspeir Ornitier-Class Gunship", "name_ru": "Средняя лодка варденов", "icon": "MediumBoatWVehicle.webp", "origin": "vehicle"},
  "MediumTank2C": {"name_en": "86K-a “Bardiche”", "name_ru": "86K-a “Bardiche”", "icon": "MediumTank2C.webp", "origin": "vehicle"},
  "MediumTank2IndirectW": {"name_en": "Gallagher Thornfall Mk. VI", "name_ru": "Gallagher Thornfall Mk. VI", "icon": "MediumTank2IndirectW.webp", "origin": "vehicle"},
  "MediumTank2MultiW": {"name_en": "Gallagher Highwayman Mk. III", "name_ru": "Gallagher Highwayman Mk. III", "icon": "MediumTank2MultiW.webp", "origin": "vehicle"},
  "MediumTank2RangeW": {"name_en": "Gallagher Outlaw Mk. II", "name_ru": "Gallagher Outlaw Mk. II", "icon": "MediumTank2RangeW.webp", "origin": "vehicle"},
  "MediumTank2TwinC": {"name_en": "86K-c “Ranseur”", "name_ru": "86K-c “Ranseur”", "icon": null, "origin": "vehicle"},
  "MediumTank2W": {"name_en": "Gallagher Brigand Mk. I", "name_ru": "Средний танк (тир 2)", "icon": "MediumTank2W.webp", "origin": "vehicle"},
  "MediumTank3C": {"name_en": "90T-v “Nemesis”", "name_ru": "90T-v “Nemesis”", "icon": null, "origin": "vehicle"},
  "MediumTankATW": {"name_en": "Silverhand Lordscar - Mk. X", "name_ru": "Silverhand Lordscar - Mk. X", "icon": "MediumTankATW.webp", "origin": "vehicle"},
  "MediumTankC": {"name_en": "85K-b “Falchion”", "name_ru": "85K-b “Falchion”", "icon": null, "origin": "vehicle"},
  "MediumTankLargeC": {"name_en": "85V-g “Talos”", "name_ru": "85V-g “Talos”", "icon": "MediumTankLargeC.webp", "origin": "vehicle"},
  "MediumTankOffensiveC": {"name_en": "85K-a “Spatha”", "name_ru": "85K-a “Spatha”", "icon": null, "origin": "vehicle"},
  "MediumTankSiegeW": {"name_en": "Silverhand Chieftain - Mk. VI", "name_ru": "Silverhand Chieftain - Mk. VI", "icon": null, "origin": "vehicle"},
  "MediumTankW": {"name_en": "Silverhand - Mk. IV", "name_ru": "Silverhand - Mk. IV", "icon": null, "origin": "vehicle"},
  "Metal": {"name_en": "Salvage", "name_ru": "Salvage", "icon": null, "origin": "item"},
  "MetalBeamMaterials": {"name_en": "Metal Beam", "name_ru": "металлическая балка", "icon": "MetalBeamMaterial.webp", "origin": "item"},
  "MineBoat": {"name_en": "Bellweather by VAC", "name_ru": "Bellweather by VAC", "icon": "Mineboat.webp", "origin": "vehicle"},
  "MiniTankAmmo": {"name_en": "30mm", "name_ru": "Снаряды малого танка", "icon": "MiniTankAmmo.webp", "origin": "item"},
  "MiniTorpedoAmmo": {"name_en": "Quillback Torpedo", "name_ru": "торпеда", "icon": "MiniTorpedoAmmo.webp", "origin": "item"},
  "Mortar": {"name_en": "Cremari Mortar", "name_ru": "миномёт", "icon": "Mortar.webp", "origin": "item"},
  "MortarAmmo": {"name_en": "Mortar Shell", "name_ru": "миномётный снаряд", "icon": "MortarAmmo.webp", "origin": "item"},
  "MortarAmmoFL": {"name_en": "Flare Mortar Shell", "name_ru": "Осветительный миномётный снаряд", "icon": "MortarAmmo.webp", "origin": "item"},
  "MortarAmmoFlame": {"name_en": "Incendiary Mortar Shell", "name_ru": "Зажигательный миномётный снаряд", "icon": "MortarAmmoFlame.webp", "origin": "item"},
  "MortarAmmoSH": {"name_en": "Shrapnel Mortar Shell", "name_ru": "Осколочный миномётный снаряд", "icon": "MortarAmmo.webp", "origin": "item"},
  "MortarTankAmmo": {"name_en": "250mm “Purity” Shell", "name_ru": "Снаряд миномётного танка", "icon": "MortarTankAmmoBR.webp", "origin": "item"},
  "MortarTankAmmoBR": {"name_en": "250mm “Fury” Shell", "name_ru": "Снаряд миномётного танка (бронебойный)", "icon": "MortarTankAmmoBR.webp", "origin": "item"},
  "MortarTankC": {"name_en": "HC-7 “Ballista”", "name_ru": "HC-7 “Ballista”", "icon": null, "origin": "vehicle"},
  "Motorboat": {"name_en": "BMS - Grouper", "name_ru": "BMS - Grouper", "icon": null, "origin": "vehicle"},
  "MotorcycleC": {"name_en": "03MM “Caster”", "name_ru": "03MM “Caster”", "icon": null, "origin": "vehicle"},
  "MotorcycleOffensiveC": {"name_en": "00MS “Stinger”", "name_ru": "00MS “Stinger”", "icon": null, "origin": "vehicle"},
  "MotorcycleW": {"name_en": "Kivela Power Wheel 80-1", "name_ru": "Мотоцикл", "icon": "MotorcycleW.png", "origin": "vehicle"},
  "NavalUniformC": {"name_en": "Remex Garb", "name_ru": "Remex Garb", "icon": "NavalUniformC.webp", "origin": "item"},
  "NavalUniformW": {"name_en": "Gentleman's Peacoat", "name_ru": "форма моряка", "icon": "NavalUniformW.webp", "origin": "item"},
  "OfficerUniformC": {"name_en": "Officialis' Attire", "name_ru": "Officialis' Attire", "icon": "OfficerUniformC.webp", "origin": "item"},
  "OfficerUniformW": {"name_en": "Officer's Regalia", "name_ru": "офицерская форма", "icon": "OfficerUniformW.webp", "origin": "item"},
  "Oil": {"name_en": "Oil", "name_ru": "Нефть", "icon": "Neft.png", "origin": "item"},
  "ParatrooperBackpack": {"name_en": "Paratrooper's Ruck", "name_ru": "Paratrooper's Ruck", "icon": "ParatrooperBackpack.webp", "origin": "item"},
  "ParatrooperUniformC": {"name_en": "Auster's Harness", "name_ru": "Auster's Harness", "icon": "ParatrooperUniformC.webp", "origin": "item"},
  "Petrol": {"name_en": "Petrol", "name_ru": "Бензин", "icon": "RefinedFuel.webp", "origin": "item"},
  "PilotMask": {"name_en": "Flight Mask", "name_ru": "Маска пилота", "icon": "PilotMask.webp", "origin": "item"},
  "PilotUniformC": {"name_en": "Lodesman's Lorica", "name_ru": "Lodesman's Lorica", "icon": "PilotUniformC.webp", "origin": "item"},
  "PilotUniformW": {"name_en": "Aviator's Raiment", "name_ru": "Aviator's Raiment", "icon": "PilotUniformW.webp", "origin": "item"},
  "PipeMaterials": {"name_en": "Pipe", "name_ru": "Pipe", "icon": null, "origin": "item"},
  "PistolAmmo": {"name_en": "8mm", "name_ru": "8мм (пистолет)", "icon": "PistolAmmo.webp", "origin": "item"},
  "PistolC": {"name_en": "Ferro 879", "name_ru": "Ferro 879", "icon": "PistolC.webp", "origin": "item"},
  "PistolLightW": {"name_en": "Cascadier 873", "name_ru": "Cascadier 873", "icon": "PistolLightW.webp", "origin": "item"},
  "PistolW": {"name_en": "Ahti Model 2", "name_ru": "Ahti Model 2", "icon": "PistolW.webp", "origin": "item"},
  "PrototypeKit": {"name_en": "Prototype Kit", "name_ru": "Prototype Kit", "icon": null, "origin": "item"},
  "RPGTW": {"name_en": "Cutler Foebreaker", "name_ru": "РПГ (танковый вариант)", "icon": "RpgW.webp", "origin": "item"},
  "Radio": {"name_en": "Radio", "name_ru": "рация", "icon": "Radio.webp", "origin": "item"},
  "RadioBackpack": {"name_en": "Radio Backpack", "name_ru": "Радиорюкзак", "icon": "RadioBackpack.webp", "origin": "item"},
  "RareMaterials": {"name_en": null, "name_ru": "Редкие материалы", "icon": "RedkieMaterialy.png", "origin": null},
  "RareMetal": {"name_en": "Rare Metal", "name_ru": "Редкий металл", "icon": "RedkiyMetall.png", "origin": "item"},
  "ReservePower": {"name_en": "Reserve Power", "name_ru": "Reserve Power", "icon": null, "origin": "item"},
  "ResourceContainer": {"name_en": "Resource Container", "name_ru": "контейнер для ресурсов", "icon": "ResourceContainer.webp", "origin": "structure"},
  "Revolver": {"name_en": "Cometa T2-9", "name_ru": "револьвер", "icon": "Revolver.webp", "origin": "item"},
  "RevolverAmmo": {"name_en": ".44 Mag", "name_ru": ".44 Магнум", "icon": "RevolverAmmo.webp", "origin": "item"},
  "RifleAmmo": {"name_en": "7.62mm", "name_ru": "7.62-мм", "icon": "RifleAmmo.webp", "origin": "item"},
  "RifleAutomaticC": {"name_en": "Catena rt.IV Auto-Rifle", "name_ru": "Catena rt.IV Auto-Rifle", "icon": "RifleAutomaticC.webp", "origin": "item"},
  "RifleAutomaticW": {"name_en": "Sampo Auto-Rifle 77", "name_ru": "Автоматическая винтовка Sampo 77", "icon": "RifleAutomaticW.webp", "origin": "item"},
  "RifleC": {"name_en": "Argenti r.II Rifle", "name_ru": "Argenti r.II Rifle", "icon": "RifleC.webp", "origin": "item"},
  "RifleHeavyC": {"name_en": "Volta r.I Repeater", "name_ru": "Volta r.I Repeater", "icon": "RifleHeavyC.webp", "origin": "item"},
  "RifleHeavyW": {"name_en": "The Hangman 757", "name_ru": "Хангман 757", "icon": "RifleHeavyC.webp", "origin": "item"},
  "RifleLightC": {"name_en": "Fuscina pi.I", "name_ru": "Fuscina pi.I", "icon": "RifleLightC.webp", "origin": "item"},
  "RifleLightW": {"name_en": "Blakerow 871", "name_ru": "винтовка Blakerov", "icon": "RifleLightC.webp", "origin": "item"},
  "RifleLongC": {"name_en": "KRR2-790 Omen", "name_ru": "KRR2-790 Omen", "icon": "RifleLongC.webp", "origin": "item"},
  "RifleLongW": {"name_en": "Clancy Cinder M3", "name_ru": "Clancy Cinder M3", "icon": "RifleLongW.webp", "origin": "item"},
  "RifleShortW": {"name_en": "No.2B Hawthorne", "name_ru": "No.2B Hawthorne", "icon": "RifleShortW.webp", "origin": "item"},
  "RifleW": {"name_en": "No.2 Loughcaster", "name_ru": "Винтовка No.2 Loughcaster", "icon": "RifleW.webp", "origin": "item"},
  "Rocket": {"name_en": "A0E-9 Rocket", "name_ru": "A0E-9 Rocket", "icon": null, "origin": "structure"},
  "RocketPartBottom": {"name_en": "A0E-9 Rocket Booster", "name_ru": "AOE-9 Ракетный Ускоритель", "icon": "AOE9RaketnyyUskoritel.png", "origin": "structure"},
  "RocketPartCenter": {"name_en": "A0E-9 Rocket Body", "name_ru": "Корпус ракеты AOE-9", "icon": "KorpusRaketyAOE9.png", "origin": "structure"},
  "RocketPartTop": {"name_en": "A0E-9 Rocket Warhead", "name_ru": "AOE-9 ракетная боеголовка", "icon": "AOE9RaketnayaBoegolovka.png", "origin": "structure"},
  "RocketSite": {"name_en": "A0E-9 Rocket Platform", "name_ru": "A0E-9 Rocket Platform", "icon": null, "origin": "structure"},
  "RpgAmmo": {"name_en": "RPG", "name_ru": "снаряд РПГ", "icon": "RpgAmmo.webp", "origin": "item"},
  "RpgW": {"name_en": "Cutler Launcher 4", "name_ru": "Cutler Launcher 4", "icon": "RpgW.webp", "origin": "item"},
  "SMGAmmo": {"name_en": "9mm", "name_ru": "9мм", "icon": "SubMachineGunAmmo.webp", "origin": "item"},
  "SMGC": {"name_en": "“The Pitch Gun” mc.V", "name_ru": "“The Pitch Gun” mc.V", "icon": "SMGC.webp", "origin": "item"},
  "SMGHeavyC": {"name_en": "“Lionclaw” mc.VIII", "name_ru": "“Lionclaw” mc.VIII", "icon": "SMGHeavyC.webp", "origin": "item"},
  "SMGHeavyW": {"name_en": "No.1 “The Liar” Submachine Gun", "name_ru": "Пистолет-пулемёт No.1 ", "icon": "SMGHeavyW.webp", "origin": "item"},
  "SMGW": {"name_en": "Fiddler Submachine Gun Model 868", "name_ru": "Пистолет пулемет Fiddler", "icon": "SubMachineGun.webp", "origin": "item"},
  "SandbagMaterials": {"name_en": "Sandbag", "name_ru": "Мешки с песком (материалы)", "icon": "SandbagMaterial.webp", "origin": "item"},
  "SatchelChargeT": {"name_en": null, "name_ru": "Заряд Аллигатор", "icon": "SatchelCharge.webp", "origin": null},
  "SatchelChargeW": {"name_en": "Alligator Charge", "name_ru": "Хавок Заряд", "icon": "SatchelCharge.webp", "origin": "item"},
  "ScoutTankMultiW": {"name_en": "King Jester Mk. I-1", "name_ru": "King Jester Mk. I-1", "icon": "ScoutTankMultiW.webp", "origin": "vehicle"},
  "ScoutTankOffensiveW": {"name_en": "King Gallant Mk. II", "name_ru": "King Gallant Mk. II", "icon": "ScoutTankOffensiveW.webp", "origin": "vehicle"},
  "ScoutTankW": {"name_en": "King Spire Mk. I", "name_ru": "King Spire Mk.1 (скаут танк)", "icon": "ScoutTankW.webp", "origin": "vehicle"},
  "ScoutUniformC": {"name_en": "Recon Camo", "name_ru": "Recon Camo", "icon": "ScoutUniformC.webp", "origin": "item"},
  "ScoutUniformW": {"name_en": "Outrider's Mantle", "name_ru": "Дозорная мантия", "icon": "ScoutUniformW.webp", "origin": "item"},
  "ScoutVehicleMobilityC": {"name_en": "UV-05a “Argonaut”", "name_ru": "UV-05a “Argonaut”", "icon": null, "origin": "vehicle"},
  "ScoutVehicleOffensiveC": {"name_en": "UV-24 “Icarus”", "name_ru": "UV-24 “Icarus”", "icon": null, "origin": "vehicle"},
  "ScoutVehicleOffensiveW": {"name_en": "Drummond Spitfire 100d", "name_ru": "Spitfire", "icon": "ScoutVehicleOffensiveWarVehicleW.webp", "origin": "vehicle"},
  "ScoutVehicleUtilityC": {"name_en": "UV-5c “Odyssey”", "name_ru": "Машина скорой помощи", "icon": "ScoutVehicleUtilityCVehicleC.webp", "origin": "vehicle"},
  "ScoutVehicleUtilityW": {"name_en": "Drummond Loscann 55c", "name_ru": "Drummond Loscann 55c", "icon": null, "origin": "vehicle"},
  "ScoutVehicleW": {"name_en": "Drummond 100a", "name_ru": "O'Brien V.110 / Скаут", "icon": "ScoutVehicleWarVehicleW.webp", "origin": "vehicle"},
  "ShipPart1": {"name_en": "Naval Hull Segments", "name_ru": "Корабельный сегмент корпуса", "icon": "KorabelnyySegmentKorpusa.png", "origin": "structure"},
  "ShipPart2": {"name_en": "Naval Shell Plating", "name_ru": "Корабельная обшивка корпуса", "icon": "KorabelnayaObshivkaKorpusa.png", "origin": "structure"},
  "ShipPart3": {"name_en": "Naval Turbine Components", "name_ru": "Компоненты морских турбин", "icon": "KomponentyMorskikhTurbin.png", "origin": "structure"},
  "ShippingContainer": {"name_en": "Shipping Container", "name_ru": "Грузовой контейнер", "icon": "ShippingContainerStructure.webp", "origin": "structure"},
  "ShotgunAmmo": {"name_en": "Buckshot", "name_ru": "дробь", "icon": "ShotgunAmmo.webp", "origin": "item"},
  "ShotgunC": {"name_en": "KRF1-750 Dragonfly", "name_ru": "KRF1-750 Dragonfly", "icon": "ShotgunC.webp", "origin": "item"},
  "ShotgunW": {"name_en": "No.4 The Pillory Scattergun", "name_ru": "дробовик", "icon": "ShotgunW.webp", "origin": "item"},
  "Shovel": {"name_en": "Shovel", "name_ru": "лопата", "icon": "Shovel.webp", "origin": "item"},
  "SledgeHammer": {"name_en": "Sledge Hammer", "name_ru": "кувалда", "icon": "SledgeHammer.webp", "origin": "item"},
  "SmokeGrenade": {"name_en": "PT-815 Smoke Grenade", "name_ru": "дымовая граната", "icon": "Smokegrenade.webp", "origin": "item"},
  "SniperRifleC": {"name_en": "KRR3-792 Auger", "name_ru": "KRR3-792 Auger", "icon": "SniperRifleC.webp", "origin": "item"},
  "SniperRifleW": {"name_en": "Clancy-Raca M4", "name_ru": "Clancy-Raca M4", "icon": null, "origin": "item"},
  "SnowUniformC": {"name_en": "Heavy Topcoat", "name_ru": "Heavy Topcoat", "icon": "SnowUniformC.webp", "origin": "item"},
  "SnowUniformW": {"name_en": null, "name_ru": "Парка Caoivish", "icon": "SnowUniformW.webp", "origin": null},
  "SoldierSupplies": {"name_en": "Soldier Supplies", "name_ru": "рубашки", "icon": "SoldatskoeSnaryazhenie.png", "origin": "item"},
  "SoldierUniformW": {"name_en": "Infantry Battledress", "name_ru": "Infantry Battledress", "icon": "SoldierUniformW.webp", "origin": "item"},
  "StickyBomb": {"name_en": "Anti-Tank Sticky Bomb", "name_ru": "липкая бомба (стика)", "icon": "StickyBomb.webp", "origin": "item"},
  "StructureCrate": {"name_en": "Shippable Crate", "name_ru": "Ящик с сооружениями", "icon": "YashchikSSooruzheniyami.png", "origin": "structure"},
  "Sulfur": {"name_en": "Sulfur", "name_ru": "Sulfur", "icon": null, "origin": "item"},
  "SuperTankC": {"name_en": "O-75b “Ares”", "name_ru": "O-75b “Ares”", "icon": null, "origin": "vehicle"},
  "SuperTankW": {"name_en": "Cullen Predator Mk. III", "name_ru": "Cullen Predator Mk. III", "icon": null, "origin": "vehicle"},
  "SurfaceWaterMine": {"name_en": "E681-B Hullbreaker Mine", "name_ru": "Морская мина E681-B", "icon": "SurfaceMine.webp", "origin": "item"},
  "SwordC": {"name_en": "Eleos Infantry Dagger", "name_ru": "Eleos Infantry Dagger", "icon": null, "origin": "item"},
  "TankMine": {"name_en": "Abisme AT-99", "name_ru": "Abisme AT-99", "icon": null, "origin": "item"},
  "TankUniformC": {"name_en": "Tankman's Coveralls", "name_ru": "Tankman's Coveralls", "icon": "TankUniformC.webp", "origin": "item"},
  "TankUniformW": {"name_en": "Padded Boiler Suit", "name_ru": "форма танкиста", "icon": "TankUniformW.webp", "origin": "item"},
  "TanketteC": {"name_en": "T12 “Actaeon” Tankette", "name_ru": "T12 “Actaeon” Tankette", "icon": null, "origin": "vehicle"},
  "TanketteFlameC": {"name_en": "T14 “Vesta” Tankette", "name_ru": "T14 “Vesta” Tankette", "icon": "TanketteFlameC.webp", "origin": "vehicle"},
  "TanketteMultiC": {"name_en": "T13 “Deioneus” Rocket Battery", "name_ru": "T13 “Deioneus” Rocket Battery", "icon": "TanketteMultiC.webp", "origin": "vehicle"},
  "TanketteOffensiveC": {"name_en": "T20 “Ixion” Tankette", "name_ru": "T20 “Ixion” Tankette", "icon": null, "origin": "vehicle"},
  "TorpedoAmmo": {"name_en": "Moray Torpedo", "name_ru": "Moray Torpedo", "icon": null, "origin": "item"},
  "TrailerLiquid": {"name_en": "Rooster - Lamploader", "name_ru": "Жидкостный прицеп", "icon": "FuelTrailer.webp", "origin": "vehicle"},
  "TrailerMaterial": {"name_en": "Rooster - Tumblebox", "name_ru": "строительный прицеп", "icon": "MaterialTrailer.webp", "origin": "vehicle"},
  "TrailerResource": {"name_en": "Rooster - Junkwagon", "name_ru": "Ресурсный прицеп", "icon": "ResourceTrailer.webp", "origin": "vehicle"},
  "TrainLRArtillery": {"name_en": "Tempest Cannon RA-2", "name_ru": "Tempest Cannon RA-2", "icon": null, "origin": "vehicle"},
  "TraumaKit": {"name_en": "Trauma Kit", "name_ru": "Травма-аптечка", "icon": "TraumaKit.webp", "origin": "item"},
  "Tripod": {"name_en": "Tripod", "name_ru": "Тренога", "icon": "DeployableTripod.webp", "origin": "item"},
  "TruckC": {"name_en": "R-1 Hauler", "name_ru": "R-1 Hauler", "icon": null, "origin": "vehicle"},
  "TruckDefensiveW": {"name_en": "Dunne Leatherback 2a", "name_ru": "Дюна", "icon": "TruckDefensiveW.webp", "origin": "vehicle"},
  "TruckLiquidC": {"name_en": "RR-3 “Stolon” Tanker", "name_ru": "RR-3 “Stolon” Tanker", "icon": null, "origin": "vehicle"},
  "TruckLiquidW": {"name_en": "Dunne Fuelrunner 2d", "name_ru": "Дюна бензовоз", "icon": null, "origin": "vehicle"},
  "TruckMobilityC": {"name_en": "R-5b “Sisyphus” Hauler", "name_ru": "R-5b “Sisyphus” Hauler", "icon": null, "origin": "vehicle"},
  "TruckMobilityW": {"name_en": "Dunne Landrunner 12c", "name_ru": "Landrunner", "icon": "TruckMobilityWarVehicle.webp", "origin": "vehicle"},
  "TruckMultiC": {"name_en": "R-17 “Retiarius” Skirmisher", "name_ru": "R-17 “Retiarius” Skirmisher", "icon": "TruckMultiC.webp", "origin": "vehicle"},
  "TruckOffensiveC": {"name_en": "R-9 “Speartip” Escort", "name_ru": "R-9 “Speartip” Escort", "icon": null, "origin": "vehicle"},
  "TruckResourceC": {"name_en": "R-5 “Atlas” Hauler", "name_ru": "R-5 “Atlas” Hauler", "icon": null, "origin": "vehicle"},
  "TruckResourceW": {"name_en": "Dunne Loadlugger 3c", "name_ru": "самосвал", "icon": "013_Loadlugger.png", "origin": "vehicle"},
  "TruckW": {"name_en": "Dunne Transport", "name_ru": "грузовик", "icon": "TruckWarVehicle.webp", "origin": "vehicle"},
  "Unknown": {"name_en": null, "name_ru": "Неизвестно", "icon": null, "origin": null},
  "Water": {"name_en": "Water", "name_ru": "вода", "icon": "Water.webp", "origin": "item"},
  "WaterBucket": {"name_en": "Water Bucket", "name_ru": "Ведро для воды", "icon": "Water.webp", "origin": "item"},
  "WaterMine": {"name_en": "E680-S Rudder Lock", "name_ru": "E680-S Rudder Lock", "icon": null, "origin": "item"},
  "WaterWallMaterials": {"name_en": "Naval Buoy", "name_ru": "naval buoy", "icon": "WaterWall.webp", "origin": "item"},
  "WindsockT": {"name_en": "Wind Sock", "name_ru": "Wind Sock", "icon": null, "origin": "item"},
  "Wood": {"name_en": "Refined Materials", "name_ru": "Refined Materials", "icon": null, "origin": "item"},
  "WorkHammer": {"name_en": "Hammer", "name_ru": "Hammer", "icon": null, "origin": "item"},
  "WorkWrench": {"name_en": "Wrench", "name_ru": "Гаечный ключ", "icon": "WorkWrench.webp", "origin": "item"},
  "WoundedCarriedPlayer": {"name_en": "Wounded Player", "name_ru": "Wounded Player", "icon": null, "origin": "item"},
  "Wreckage": {"name_en": "Wreckage", "name_ru": "Wreckage", "icon": null, "origin": "item"},
};

function stripServiceSuffix(value: string): string {
  return value
    .replace(/\s*\((?:ящик|ящ|штука|шт|crate|crates?)\)\s*$/iu, "")
    .replace(/\s+(?:ящиков|ящика|ящик|ящ|штук|штука|шт)\.?\s*$/iu, "")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function lookupKey(value: string): string {
  return stripServiceSuffix(value)
    .toLocaleLowerCase("ru-RU")
    .replace(/ё/g, "е")
    .replace(/[^a-z0-9а-я]+/giu, "")
    .trim();
}

type ItemLookup = { code: string; item: ItemConfig; enriched?: FoxholeDataEntry };

function toItemConfig(entry: FoxholeDataEntry): ItemConfig {
  return {
    name_en: entry.nameEn,
    name_ru: entry.nameRu,
    icon: entry.icon,
    origin: entry.origin,
  };
}

const ITEMS_BY_LOOKUP_NAME = Object.entries(ITEM_CODES).reduce<Map<string, ItemLookup>>((map, [code, item]) => {
  const value = { code, item };
  map.set(lookupKey(code), value);
  map.set(lookupKey(item.name_ru), value);
  if (item.name_en) map.set(lookupKey(item.name_en), value);
  return map;
}, new Map());

for (const [code, entry] of Object.entries(FOXHOLE_DATA)) {
  const value = { code, item: toItemConfig(entry), enriched: entry };
  ITEMS_BY_LOOKUP_NAME.set(lookupKey(code), value);
  ITEMS_BY_LOOKUP_NAME.set(lookupKey(entry.nameRu), value);
  if (entry.nameEn) ITEMS_BY_LOOKUP_NAME.set(lookupKey(entry.nameEn), value);
}

function resolveItem(rawName: string): ItemLookup | null {
  const raw = stripServiceSuffix(String(rawName ?? "").trim());
  if (!raw) return null;
  const exact = ITEM_CODES[raw];
  const enriched = FOXHOLE_DATA[raw];
  const normalized = lookupKey(raw);
  const direct = exact
    ? { code: raw, item: exact, enriched: FOXHOLE_DATA[raw] }
    : enriched
      ? { code: raw, item: toItemConfig(enriched), enriched }
      : ITEMS_BY_LOOKUP_NAME.get(normalized);
  if (direct) return direct;

  // Мягкое совпадение помогает для коротких складских названий:
  // «120-мм» ↔ «120мм снаряды», «950-70b ...» ↔ официальный name_ru.
  for (const [key, value] of ITEMS_BY_LOOKUP_NAME) {
    if (key.length >= 4 && (key.includes(normalized) || normalized.includes(key))) return value;
  }
  return null;
}

/**
 * Возвращает оригинальную игровую иконку предмета, если она есть в реестре.
 * Точные связи из item-icon-overrides.ts имеют приоритет над базовым item_codes.py.
 */
export function getItemIconPath(rawName: string): string | null {
  const resolved = resolveItem(rawName);
  if (!resolved) return null;
  const icon = ITEM_ICON_OVERRIDES[resolved.code] ?? resolved.item.icon ?? resolved.enriched?.icon;
  return icon ? `/FoxholeWikiPhotos/${encodeURIComponent(icon).replace(/%2F/g, "/")}` : null;
}

export function getItemConfig(rawName: string): ItemConfig | null {
  return resolveItem(rawName)?.item ?? null;
}
