// Автогенерация из item_codes.py (Foxhole Wiki Codenames, 396 кодов) + список из gui_app.py
export type ItemOrigin = "item" | "vehicle" | "structure" | "other";
export type ItemCategory = "Оружие" | "Боеприпасы" | "Материалы" | "Медицина" | "Снаряжение" | "Техника" | "Сооружения" | "Прочее";
export interface CatalogItem { code: string | null; name: string; en: string | null; origin: ItemOrigin; category: ItemCategory; }
export const ITEM_CATEGORIES: ItemCategory[] = ["Оружие", "Боеприпасы", "Материалы", "Медицина", "Снаряжение", "Техника", "Сооружения", "Прочее"];
export const ITEM_CATALOG: CatalogItem[] = [
  { code: "RevolverAmmo", name: ".44 Магнум", en: ".44 Mag", origin: "item", category: "Боеприпасы" },
  { code: "MotorcycleOffensiveC", name: "00MS “Stinger”", en: "00MS “Stinger”", origin: "vehicle", category: "Техника" },
  { code: "MotorcycleC", name: "03MM “Caster”", en: "03MM “Caster”", origin: "vehicle", category: "Техника" },
  { code: "MGAmmo", name: "12.7 мм (пулемётные) патроны", en: "12.7mm", origin: "item", category: "Боеприпасы" },
  { code: null, name: "12.7-мм", en: null, origin: "item", category: "Боеприпасы" },
  { code: "LargeFieldLightArtilleryC", name: "120-68 “Koronides” Field Gun", en: "120-68 “Koronides” Field Gun", origin: "vehicle", category: "Техника" },
  { code: null, name: "120-мм", en: null, origin: "item", category: "Боеприпасы" },
  { code: "LightArtilleryAmmo", name: "120мм снаряды", en: "120mm", origin: "item", category: "Боеприпасы" },
  { code: "ATRifleAmmo", name: "14.5 мм", en: "14.5mm", origin: "item", category: "Боеприпасы" },
  { code: null, name: "150-мм", en: null, origin: "item", category: "Боеприпасы" },
  { code: "HeavyArtilleryAmmo", name: "150мм снаряды", en: "150mm", origin: "item", category: "Боеприпасы" },
  { code: null, name: "20мм", en: null, origin: "item", category: "Боеприпасы" },
  { code: "AircraftAmmo", name: "20мм (зенитные) патроны", en: "20mm", origin: "item", category: "Боеприпасы" },
  { code: "ATRifleAssaultW", name: "228 Satterley Heavy Storm Rifle", en: "228 Satterley Heavy Storm Rifle", origin: "item", category: "Оружие" },
  { code: "FieldMortarC", name: "30-250 “Tisiphone” Field Cannon", en: "30-250 “Tisiphone” Field Cannon", origin: "vehicle", category: "Техника" },
  { code: null, name: "300-мм", en: null, origin: "item", category: "Боеприпасы" },
  { code: "LRArtilleryAmmo", name: "300mm", en: "300mm", origin: "item", category: "Боеприпасы" },
  { code: null, name: "30мм", en: null, origin: "item", category: "Боеприпасы" },
  { code: "HERocketAmmo", name: "3C-High Explosive Rocket", en: "3C-High Explosive Rocket", origin: "item", category: "Боеприпасы" },
  { code: "LargeFieldMortarC", name: "40-250 “Alekto” Heavy Cannon", en: "40-250 “Alekto” Heavy Cannon", origin: "vehicle", category: "Техника" },
  { code: "FieldCannonDamageC", name: "40-45 “Smelter”", en: "40-45 “Smelter”", origin: "vehicle", category: "Техника" },
  { code: "LightTankAmmo", name: "40-мм", en: "40mm", origin: "item", category: "Боеприпасы" },
  { code: "FireRocketAmmo", name: "4C-Fire Rocket", en: "4C-Fire Rocket", origin: "item", category: "Боеприпасы" },
  { code: "EmplacedHeavyArtilleryC", name: "50-500 Thunderbolt Cannon", en: "50-500 “Thunderbolt” Cannon", origin: "structure", category: "Сооружения" },
  { code: "ATAmmo", name: "68-мм", en: "68mm", origin: "item", category: "Боеприпасы" },
  { code: null, name: "7.52-мм", en: null, origin: "item", category: "Боеприпасы" },
  { code: "RifleAmmo", name: "7.62-мм", en: "7.62mm", origin: "item", category: "Боеприпасы" },
  { code: "AssaultRifleAmmo", name: "7.92 мм", en: "7.92mm", origin: "item", category: "Боеприпасы" },
  { code: "GunboatW", name: "74b-1 Ronan Gunship", en: "74b-1 Ronan Gunship", origin: "vehicle", category: "Техника" },
  { code: "BattleTankAmmo", name: "75mm", en: "75mm", origin: "item", category: "Боеприпасы" },
  { code: null, name: "8-мм", en: null, origin: "item", category: "Боеприпасы" },
  { code: "MediumTankOffensiveC", name: "85K-a “Spatha”", en: "85K-a “Spatha”", origin: "vehicle", category: "Техника" },
  { code: "MediumTankC", name: "85K-b “Falchion”", en: "85K-b “Falchion”", origin: "vehicle", category: "Техника" },
  { code: "MediumTankLargeC", name: "85V-g “Talos”", en: "85V-g “Talos”", origin: "vehicle", category: "Техника" },
  { code: "MediumTank2C", name: "86K-a “Bardiche”", en: "86K-a “Bardiche”", origin: "vehicle", category: "Техника" },
  { code: "MediumTank2TwinC", name: "86K-c “Ranseur”", en: "86K-c “Ranseur”", origin: "vehicle", category: "Техника" },
  { code: "PistolAmmo", name: "8мм (пистолет)", en: "8mm", origin: "item", category: "Боеприпасы" },
  { code: "MediumTank3C", name: "90T-v “Nemesis”", en: "90T-v “Nemesis”", origin: "vehicle", category: "Техника" },
  { code: "DiveBomberAmmo", name: "912 Shrike Rounds", en: "912 Shrike Rounds", origin: "item", category: "Боеприпасы" },
  { code: null, name: "94.5мм", en: null, origin: "item", category: "Боеприпасы" },
  { code: "ATLargeAmmo", name: "94.5мм снаряды", en: "94.5mm", origin: "item", category: "Боеприпасы" },
  { code: "LargeFieldATC", name: "945g “Stygian Bolt”", en: "945g “Stygian Bolt”", origin: "vehicle", category: "Техника" },
  { code: null, name: "950-70b Зенитный снаряд", en: null, origin: "item", category: "Боеприпасы" },
  { code: "SMGAmmo", name: "9мм", en: "9mm", origin: "item", category: "Боеприпасы" },
  { code: "Rocket", name: "A0E-9 Rocket", en: "A0E-9 Rocket", origin: "structure", category: "Сооружения" },
  { code: "RocketSite", name: "A0E-9 Rocket Platform", en: "A0E-9 Rocket Platform", origin: "structure", category: "Сооружения" },
  { code: null, name: "A3 Harpa Осколочная граната", en: null, origin: "item", category: "Оружие" },
  { code: "AircraftScoutC", name: "A51 Venti “Daedalus”", en: "A51 Venti “Daedalus”", origin: "vehicle", category: "Техника" },
  { code: "AircraftScout2C", name: "A59 Venti “Perdix”", en: "A59 Venti “Perdix”", origin: "vehicle", category: "Техника" },
  { code: "FieldATC", name: "AA-2 Battering Ram", en: "AA-2 Battering Ram", origin: "vehicle", category: "Техника" },
  { code: "AssaultRifleW", name: "Aalto Storm Rifle 24", en: "Aalto Storm Rifle 24", origin: "item", category: "Оружие" },
  { code: null, name: "Aalto Автоматическая винтовка 24", en: null, origin: "item", category: "Оружие" },
  { code: "LandingCraftOffensiveC", name: "AB-11 “Doru”", en: "AB-11 “Doru”", origin: "vehicle", category: "Техника" },
  { code: "TankMine", name: "Abisme AT-99", en: "Abisme AT-99", origin: "item", category: "Оружие" },
  { code: null, name: "Abisme AT-99 Mine", en: null, origin: "item", category: "Оружие" },
  { code: "PistolW", name: "Ahti Model 2", en: "Ahti Model 2", origin: "item", category: "Оружие" },
  { code: "AirSirenT", name: "Air Raid Siren", en: "Air Raid Siren", origin: "item", category: "Снаряжение" },
  { code: "AircraftDepot", name: "Aircraft Depot", en: "Aircraft Depot", origin: "structure", category: "Сооружения" },
  { code: "AircraftFactory", name: "Aircraft Hangar", en: "Aircraft Hangar", origin: "structure", category: "Сооружения" },
  { code: "Aluminum", name: "Aluminum", en: "Aluminum", origin: "item", category: "Материалы" },
  { code: "AAGunAI", name: "Anti-Air Gun", en: "Anti-Air Gun", origin: "structure", category: "Сооружения" },
  { code: "RocketPartTop", name: "AOE-9 ракетная боеголовка", en: "A0E-9 Rocket Warhead", origin: "structure", category: "Сооружения" },
  { code: "RocketPartBottom", name: "AOE-9 Ракетный Ускоритель", en: "A0E-9 Rocket Booster", origin: "structure", category: "Сооружения" },
  { code: "ATRPGIndirectAmmo", name: "ARC⧸RPG", en: "ARC⧸RPG", origin: "item", category: "Боеприпасы" },
  { code: "RifleC", name: "Argenti r.II Rifle", en: "Argenti r.II Rifle", origin: "item", category: "Оружие" },
  { code: null, name: "Argenti r.II Винтовка", en: null, origin: "item", category: "Оружие" },
  { code: "FacilityMaterials5", name: "Assembly Materials II", en: "Assembly Materials II", origin: "item", category: "Материалы" },
  { code: "FacilityMaterials6", name: "Assembly Materials III", en: "Assembly Materials III", origin: "item", category: "Материалы" },
  { code: "FacilityMaterials7", name: "Assembly Materials IV", en: "Assembly Materials IV", origin: "item", category: "Материалы" },
  { code: "FacilityMaterials8", name: "Assembly Materials V", en: "Assembly Materials V", origin: "item", category: "Материалы" },
  { code: "HeavyTruckC", name: "AU-A150 Taurine Rigger", en: "AU-A150 Taurine Rigger", origin: "vehicle", category: "Техника" },
  { code: "ParatrooperUniformC", name: "Auster's Harness", en: "Auster's Harness", origin: "item", category: "Снаряжение" },
  { code: "PilotUniformW", name: "Aviator's Raiment", en: "Aviator's Raiment", origin: "item", category: "Снаряжение" },
  { code: "ATLaunchedGrenadeW", name: "B2 Varsi Anti-Tank Grenade", en: "B2 Varsi Anti-Tank Grenade", origin: "item", category: "Оружие" },
  { code: "FieldMortarW", name: "Balfour Falconer 250mm", en: "Balfour Falconer 250mm", origin: "vehicle", category: "Техника" },
  { code: "FieldATDamageW", name: "Balfour Rampart 68mm", en: "Balfour Rampart 68mm", origin: "vehicle", category: "Техника" },
  { code: "LargeFieldCannonW", name: "Balfour Stockade 75mm", en: "Balfour Stockade 75mm", origin: "vehicle", category: "Техника" },
  { code: "ATRPGHeavyC", name: "Bane 45", en: "Bane 45", origin: "item", category: "Оружие" },
  { code: "MineBoat", name: "Bellweather by VAC", en: "Bellweather by VAC", origin: "vehicle", category: "Техника" },
  { code: "In06KItem", name: "Blackened Runestone", en: "Blackened Runestone", origin: "item", category: "Прочее" },
  { code: "LargeShipDestroyerW", name: "Blacksteele", en: "Blacksteele", origin: "vehicle", category: "Техника" },
  { code: "Bicycle", name: "Blumfield LK205", en: "Blumfield LK205", origin: "vehicle", category: "Техника" },
  { code: "LargeShipStorageShip", name: "BMS - Bluefin", en: "BMS - Bluefin", origin: "vehicle", category: "Техника" },
  { code: "LargeShipResourceShip", name: "BMS - Bowhead", en: "BMS - Bowhead", origin: "vehicle", category: "Техника" },
  { code: "Motorboat", name: "BMS - Grouper", en: "BMS - Grouper", origin: "vehicle", category: "Техника" },
  { code: "LargeShipBaseShip", name: "BMS - Longhook", en: "BMS - Longhook", origin: "vehicle", category: "Техника" },
  { code: "LargeCrane", name: "BMS - Overseer Sky-Hauler", en: "BMS - Overseer Sky-Hauler", origin: "vehicle", category: "Техника" },
  { code: "Harvester", name: "BMS - Scrap Hauler", en: "BMS - Scrap Hauler", origin: "vehicle", category: "Техника" },
  { code: "GrenadeC", name: "Bomastone Grenade", en: "Bomastone Grenade", origin: "item", category: "Оружие" },
  { code: null, name: "Bomastone Граната", en: null, origin: "item", category: "Оружие" },
  { code: "ATRifleAutomaticW", name: "Booker Greyhound Model 910", en: "Booker Greyhound Model 910", origin: "item", category: "Оружие" },
  { code: "AssaultRifleHeavyW", name: "Booker Storm Rifle Model 838", en: "Booker Storm Rifle Model 838", origin: "item", category: "Оружие" },
  { code: "PistolLightW", name: "Cascadier 873", en: "Cascadier 873", origin: "item", category: "Оружие" },
  { code: "AssaultRifleC", name: "Catara mo.II", en: "Catara mo.II", origin: "item", category: "Оружие" },
  { code: "RifleAutomaticC", name: "Catena rt.IV Auto-Rifle", en: "Catena rt.IV Auto-Rifle", origin: "item", category: "Оружие" },
  { code: "RifleLongW", name: "Clancy Cinder M3", en: "Clancy Cinder M3", origin: "item", category: "Оружие" },
  { code: "SniperRifleW", name: "Clancy-Raca M4", en: "Clancy-Raca M4", origin: "item", category: "Оружие" },
  { code: "Coal", name: "Coal", en: "Coal", origin: "item", category: "Материалы" },
  { code: "FacilityCoal1", name: "Coke", en: "Coke", origin: "item", category: "Материалы" },
  { code: "Concrete", name: "Concrete Materials", en: "Concrete Materials", origin: "item", category: "Материалы" },
  { code: "Copper", name: "Copper", en: "Copper", origin: "item", category: "Материалы" },
  { code: "Crate", name: "Crate", en: "Crate", origin: "item", category: "Материалы" },
  { code: "CriticalSoldier", name: "Critically Wounded Soldier", en: "Critically Wounded Soldier", origin: "item", category: "Прочее" },
  { code: "InfantryMine", name: "Crow's Foot Mine", en: "Crow's Foot Mine", origin: "item", category: "Оружие" },
  { code: "SuperTankW", name: "Cullen Predator Mk. III", en: "Cullen Predator Mk. III", origin: "vehicle", category: "Техника" },
  { code: "RpgW", name: "Cutler Launcher 4", en: "Cutler Launcher 4", origin: "item", category: "Оружие" },
  { code: "Construction", name: "CV (тир 1)", en: "BMS - Universal Assembly Rig", origin: "vehicle", category: "Техника" },
  { code: "EmplacedInfantryC", name: "DAE 1b-2 Serra", en: "DAE 1b-2 “Serra”", origin: "structure", category: "Сооружения" },
  { code: "EmplacedIndirectC", name: "DAE 1o-3 Polybolos", en: "DAE 1o-3 “Polybolos”", origin: "structure", category: "Сооружения" },
  { code: "EmplacedCannonLargeC", name: "DAE 2a-1 Ruptura", en: "DAE 2a-1 “Ruptura”", origin: "structure", category: "Сооружения" },
  { code: "EmplacedMultiC", name: "DAE 3b-2 Hades Net", en: "DAE 3b-2 “Hades' Net”", origin: "structure", category: "Сооружения" },
  { code: "EmplacedAircraftC", name: "DAE 5b Zeal", en: "DAE 5b “Zeal”", origin: "structure", category: "Сооружения" },
  { code: "FacilityComponents1", name: "Damaged Components", en: "Damaged Components", origin: "item", category: "Материалы" },
  { code: "ISGTC", name: "Daucus isg.III", en: "Daucus isg.III", origin: "item", category: "Оружие" },
  { code: "DeployedATRifleTC", name: "Deployed “Typhon” ra.XII", en: "Deployed “Typhon” ra.XII", origin: "structure", category: "Сооружения" },
  { code: "LightTankDefensiveW", name: "Devitt Ironhide Mk. IV", en: "Devitt Ironhide Mk. IV", origin: "vehicle", category: "Техника" },
  { code: "LightTankW", name: "Devitt Mk. III", en: "Devitt Mk. III", origin: "vehicle", category: "Техника" },
  { code: "ScoutVehicleUtilityW", name: "Drummond Loscann 55c", en: "Drummond Loscann 55c", origin: "vehicle", category: "Техника" },
  { code: "FieldAT2W", name: "Duncan's Coin 14.5mm", en: "Duncan's Coin 14.5mm", origin: "vehicle", category: "Техника" },
  { code: "WaterMine", name: "E680-S Rudder Lock", en: "E680-S Rudder Lock", origin: "item", category: "Материалы" },
  { code: "SwordC", name: "Eleos Infantry Dagger", en: "Eleos Infantry Dagger", origin: "item", category: "Оружие" },
  { code: "EngineerUniformC", name: "Fabri Rucksack", en: "Fabri Rucksack", origin: "item", category: "Снаряжение" },
  { code: "FacilityPower", name: "Facility Power", en: "Facility Power", origin: "item", category: "Материалы" },
  { code: "MaceW", name: "Falias Raiding Club", en: "Falias Raiding Club", origin: "item", category: "Оружие" },
  { code: "PistolC", name: "Ferro 879", en: "Ferro 879", origin: "item", category: "Оружие" },
  { code: "FirePitT2", name: "Field Range", en: "Field Range", origin: "structure", category: "Сооружения" },
  { code: "BattleTankDefensiveW", name: "Flood Juggernaut Mk. VII", en: "Flood Juggernaut Mk. VII", origin: "vehicle", category: "Техника" },
  { code: "BattleTankW", name: "Flood Mk. I", en: "Flood Mk. I", origin: "vehicle", category: "Техника" },
  { code: "BattleTankHeavyArtilleryW", name: "Flood Mk. IX Stain", en: "Flood Mk. IX Stain", origin: "vehicle", category: "Техника" },
  { code: "RifleLightC", name: "Fuscina pi.I", en: "Fuscina pi.I", origin: "item", category: "Оружие" },
  { code: "FieldMGC", name: "G40 “Sagittarii”", en: "G40 “Sagittarii”", origin: "vehicle", category: "Техника" },
  { code: "FieldAT2C", name: "GA6 “Cestus”", en: "GA6 “Cestus”", origin: "vehicle", category: "Техника" },
  { code: "MediumTank2MultiW", name: "Gallagher Highwayman Mk. III", en: "Gallagher Highwayman Mk. III", origin: "vehicle", category: "Техника" },
  { code: "MediumTank2RangeW", name: "Gallagher Outlaw Mk. II", en: "Gallagher Outlaw Mk. II", origin: "vehicle", category: "Техника" },
  { code: "MediumTank2IndirectW", name: "Gallagher Thornfall Mk. VI", en: "Gallagher Thornfall Mk. VI", origin: "vehicle", category: "Техника" },
  { code: "GrenadeUniformC", name: "Grenadier's Baldric", en: "Grenadier's Baldric", origin: "item", category: "Оружие" },
  { code: "LightTankOffensiveC", name: "H-10 “Pelekys”", en: "H-10 “Pelekys”", origin: "vehicle", category: "Техника" },
  { code: "LightTankFlameC", name: "H-19 “Vulcan”", en: "H-19 “Vulcan”", origin: "vehicle", category: "Техника" },
  { code: "LightTankMobilityC", name: "H-8 “Kranesca”", en: "H-8 “Kranesca”", origin: "vehicle", category: "Техника" },
  { code: "LightTank3C", name: "HA-1 “Sagaris”", en: "HA-1 “Sagaris”", origin: "vehicle", category: "Техника" },
  { code: "WorkHammer", name: "Hammer", en: "Hammer", origin: "item", category: "Снаряжение" },
  { code: "LightTank2InfantryC", name: "HC-2 “Scorpion”", en: "HC-2 “Scorpion”", origin: "vehicle", category: "Техника" },
  { code: "MortarTankC", name: "HC-7 “Ballista”", en: "HC-7 “Ballista”", origin: "vehicle", category: "Техника" },
  { code: "SnowUniformC", name: "Heavy Topcoat", en: "Heavy Topcoat", origin: "item", category: "Снаряжение" },
  { code: "HalfTrackC", name: "HH-a “Javelin”", en: "HH-a “Javelin”", origin: "vehicle", category: "Техника" },
  { code: "HalfTrackDefensiveC", name: "HH-b “Hoplite”", en: "HH-b “Hoplite”", origin: "vehicle", category: "Техника" },
  { code: "HalfTrackArtilleryC", name: "HH-d “Peltast”", en: "HH-d “Peltast”", origin: "vehicle", category: "Техника" },
  { code: "EmplacedHeavyArtilleryW", name: "Huber Exalt 150mm", en: "Huber Exalt 150mm", origin: "structure", category: "Сооружения" },
  { code: "EmplacedLightArtilleryW", name: "Huber Lariat 120мм", en: "Huber Lariat 120mm", origin: "structure", category: "Сооружения" },
  { code: "EmplacedATLargeW", name: "Huber Starbreaker 94.5", en: "Huber Starbreaker 94.5mm", origin: "structure", category: "Сооружения" },
  { code: "ExplosiveLightC", name: "Hydra's Whisper", en: "Hydra's Whisper", origin: "item", category: "Материалы" },
  { code: "ATRPGLightC", name: "Ignifist 30", en: "Ignifist 30", origin: "item", category: "Оружие" },
  { code: "SoldierUniformW", name: "Infantry Battledress", en: "Infantry Battledress", origin: "item", category: "Снаряжение" },
  { code: "LandingShipC", name: "Interceptor PA-12", en: "Interceptor PA-12", origin: "vehicle", category: "Техника" },
  { code: "Iron", name: "Iron", en: "Iron", origin: "item", category: "Материалы" },
  { code: "IronA", name: "Iron Alloy", en: "Iron Alloy", origin: "item", category: "Материалы" },
  { code: "LightBoatInfantryC", name: "K-81e “Sombre”", en: "K-81e “Sombre”", origin: "vehicle", category: "Техника" },
  { code: "ScoutTankOffensiveW", name: "King Gallant Mk. II", en: "King Gallant Mk. II", origin: "vehicle", category: "Техника" },
  { code: "ScoutTankMultiW", name: "King Jester Mk. I-1", en: "King Jester Mk. I-1", origin: "vehicle", category: "Техника" },
  { code: "ScoutTankW", name: "King Spire Mk.1 (скаут танк)", en: "King Spire Mk. I", origin: "vehicle", category: "Техника" },
  { code: "GrenadeLauncherC", name: "KLG901-2 Lunaire F", en: "KLG901-2 Lunaire F", origin: "item", category: "Оружие" },
  { code: "ShotgunC", name: "KRF1-750 Dragonfly", en: "KRF1-750 Dragonfly", origin: "item", category: "Оружие" },
  { code: "MGC", name: "KRN886-127 Gast Machine Gun", en: "KRN886-127 Gast Machine Gun", origin: "item", category: "Оружие" },
  { code: "RifleLongC", name: "KRR2-790 Omen", en: "KRR2-790 Omen", origin: "item", category: "Оружие" },
  { code: "SniperRifleC", name: "KRR3-792 Auger", en: "KRR3-792 Auger", origin: "item", category: "Оружие" },
  { code: "MGTC", name: "Lamentum mm.IV", en: "Lamentum mm.IV", origin: "item", category: "Боеприпасы" },
  { code: "BattleTankATC", name: "Lance-25 “Hasta”", en: "Lance-25 “Hasta”", origin: "vehicle", category: "Техника" },
  { code: "BattleTankC", name: "Lance-36", en: "Lance-36", origin: "vehicle", category: "Техника" },
  { code: "BattleTankHeavyArtilleryC", name: "Lance-46 “Sarissa”", en: "Lance-46 “Sarissa”", origin: "vehicle", category: "Техника" },
  { code: "TruckMobilityW", name: "Landrunner", en: "Dunne Landrunner 12c", origin: "vehicle", category: "Техника" },
  { code: "EmplacedAircraftW", name: "Leary AA-70 Bolas", en: "Leary AA-70 Bolas", origin: "structure", category: "Сооружения" },
  { code: "EmplacedATW", name: "Leary Shellbore 68-мм", en: "Leary Shellbore 68mm", origin: "structure", category: "Сооружения" },
  { code: "EmplacedInfantryW", name: "Leary Snare Trap 20", en: "Leary Snare Trap 20", origin: "structure", category: "Сооружения" },
  { code: "PilotUniformC", name: "Lodesman's Lorica", en: "Lodesman's Lorica", origin: "item", category: "Снаряжение" },
  { code: "AircraftFighterW", name: "Luminary Mk. II Harbinger", en: "Luminary Mk. II Harbinger", origin: "vehicle", category: "Техника" },
  { code: "AircraftScoutW", name: "Luminary Mk. IV Herald", en: "Luminary Mk. IV Herald", origin: "vehicle", category: "Техника" },
  { code: "AircraftScout2W", name: "Luminary Mk. VI Emissary", en: "Luminary Mk. VI Emissary", origin: "vehicle", category: "Техника" },
  { code: "AircraftTorpedoW", name: "M925 Austringer Man-O-War", en: "M925 Austringer Man-O-War", origin: "vehicle", category: "Техника" },
  { code: "LandingShipW", name: "MacConmara Shorerunner", en: "MacConmara Shorerunner", origin: "vehicle", category: "Техника" },
  { code: "MGW", name: "Malone MK.2", en: "Malone MK.2", origin: "item", category: "Оружие" },
  { code: "BomberAmmo", name: "Mark II Raidbreaker", en: "Mark II Raidbreaker", origin: "item", category: "Боеприпасы" },
  { code: "MedicUniformC", name: "Medic Fatigues", en: "Medic Fatigues", origin: "item", category: "Медицина" },
  { code: "LargeShipBattleshipAircraftW", name: "Mercy", en: "Mercy", origin: "vehicle", category: "Техника" },
  { code: "AircraftDiveC", name: "Mergo-4 “Myrmidon”", en: "Mergo-4 “Myrmidon”", origin: "vehicle", category: "Техника" },
  { code: "DepthChargeAmmo", name: "Model-7 “Evie”", en: "Model-7 “Evie”", origin: "item", category: "Боеприпасы" },
  { code: "TorpedoAmmo", name: "Moray Torpedo", en: "Moray Torpedo", origin: "item", category: "Боеприпасы" },
  { code: "ATRPGTW", name: "Mounted Bonesaw MK.3", en: "Mounted Bonesaw MK.3", origin: "item", category: "Оружие" },
  { code: "GrenadeLauncherTC", name: "Mounted Fissura gd.I", en: "Mounted Fissura gd.I", origin: "item", category: "Оружие" },
  { code: "WaterWallMaterials", name: "naval buoy", en: "Naval Buoy", origin: "item", category: "Материалы" },
  { code: "HalfTrackOffensiveW", name: "Niska Mk. II Blinder", en: "Niska Mk. II Blinder", origin: "vehicle", category: "Техника" },
  { code: "HalfTrackTwinW", name: "Niska Mk. III Scar Twin", en: "Niska Mk. III Scar Twin", origin: "vehicle", category: "Техника" },
  { code: "HalftrackMultiW", name: "Niska-Rycker Mk. IX Skycaller", en: "Niska-Rycker Mk. IX Skycaller", origin: "vehicle", category: "Техника" },
  { code: "RifleShortW", name: "No.2B Hawthorne", en: "No.2B Hawthorne", origin: "item", category: "Оружие" },
  { code: "DestroyerTankFlameW", name: "Noble Firebrand Mk. XVII", en: "Noble Firebrand Mk. XVII", origin: "vehicle", category: "Техника" },
  { code: "DestroyerTankW", name: "Noble Widow MK. XIV", en: "Noble Widow MK. XIV", origin: "vehicle", category: "Техника" },
  { code: "ArmoredCarW", name: "O", en: "O'Brien V.110", origin: "vehicle", category: "Техника" },
  { code: "ArmoredCar2TwinW", name: "O'Brien V.101 Freeman / Twin AC", en: "O'Brien V.190 Knave", origin: "vehicle", category: "Техника" },
  { code: "ScoutVehicleW", name: "O'Brien V.110 / Скаут", en: "Drummond 100a", origin: "vehicle", category: "Техника" },
  { code: "ArmoredCarATW", name: "O'Brien V.113 Gravekeeper", en: "O'Brien V.113 Gravekeeper", origin: "vehicle", category: "Техника" },
  { code: "ArmoredCar2MultiW", name: "O'Brien V.200 Squire", en: "O'Brien V.200 Squire", origin: "vehicle", category: "Техника" },
  { code: "SuperTankC", name: "O-75b “Ares”", en: "O-75b “Ares”", origin: "vehicle", category: "Техника" },
  { code: "OfficerUniformC", name: "Officialis' Attire", en: "Officialis' Attire", origin: "item", category: "Снаряжение" },
  { code: null, name: "O’Brien V.112", en: null, origin: "item", category: "Техника" },
  { code: "ParatrooperBackpack", name: "Paratrooper's Ruck", en: "Paratrooper's Ruck", origin: "item", category: "Снаряжение" },
  { code: "PipeMaterials", name: "Pipe", en: "Pipe", origin: "item", category: "Материалы" },
  { code: "LargeShipAircraftC", name: "Poseidon", en: "Poseidon", origin: "vehicle", category: "Техника" },
  { code: "PrototypeKit", name: "Prototype Kit", en: "Prototype Kit", origin: "item", category: "Снаряжение" },
  { code: "TruckC", name: "R-1 Hauler", en: "R-1 Hauler", origin: "vehicle", category: "Техника" },
  { code: "AmbulanceC", name: "R-12 - “Salus” Ambulance", en: "R-12 - “Salus” Ambulance", origin: "vehicle", category: "Техника" },
  { code: "AmbulanceFlameC", name: "R-12b - “Salva” Flame Truck", en: "R-12b - “Salva” Flame Truck", origin: "vehicle", category: "Техника" },
  { code: "BusC", name: "R-15 - “Chariot”", en: "R-15 - “Chariot”", origin: "vehicle", category: "Техника" },
  { code: "TruckMultiC", name: "R-17 “Retiarius” Skirmisher", en: "R-17 “Retiarius” Skirmisher", origin: "vehicle", category: "Техника" },
  { code: "TruckResourceC", name: "R-5 “Atlas” Hauler", en: "R-5 “Atlas” Hauler", origin: "vehicle", category: "Техника" },
  { code: "TruckMobilityC", name: "R-5b “Sisyphus” Hauler", en: "R-5b “Sisyphus” Hauler", origin: "vehicle", category: "Техника" },
  { code: "TruckOffensiveC", name: "R-9 “Speartip” Escort", en: "R-9 “Speartip” Escort", origin: "vehicle", category: "Техника" },
  { code: "FacilityMaterials9", name: "Rare Alloys", en: "Rare Alloys", origin: "item", category: "Материалы" },
  { code: "FacilityMaterials12", name: "Rare Materials", en: "Rare Materials", origin: "item", category: "Материалы" },
  { code: "ScoutUniformC", name: "Recon Camo", en: "Recon Camo", origin: "item", category: "Снаряжение" },
  { code: "Wood", name: "Refined Materials", en: "Refined Materials", origin: "item", category: "Материалы" },
  { code: "NavalUniformC", name: "Remex Garb", en: "Remex Garb", origin: "item", category: "Материалы" },
  { code: "ReservePower", name: "Reserve Power", en: "Reserve Power", origin: "item", category: "Прочее" },
  { code: "AircraftParatrooperW", name: "Rinnspeir Mk. I Zealot", en: "Rinnspeir Mk. I Zealot", origin: "vehicle", category: "Техника" },
  { code: "TruckLiquidC", name: "RR-3 “Stolon” Tanker", en: "RR-3 “Stolon” Tanker", origin: "vehicle", category: "Техника" },
  { code: "Metal", name: "Salvage", en: "Salvage", origin: "item", category: "Материалы" },
  { code: "FortLargeRadarPart", name: "SC-3 Aerial Interceptor Array Parts", en: null, origin: "other", category: "Прочее" },
  { code: "LightTank3W", name: "Sharkey-Devitt Birdeater Mk. I", en: "Sharkey-Devitt Birdeater Mk. I", origin: "vehicle", category: "Техника" },
  { code: "MediumTankW", name: "Silverhand - Mk. IV", en: "Silverhand - Mk. IV", origin: "vehicle", category: "Техника" },
  { code: "MediumTankSiegeW", name: "Silverhand Chieftain - Mk. VI", en: "Silverhand Chieftain - Mk. VI", origin: "vehicle", category: "Техника" },
  { code: "MediumTankATW", name: "Silverhand Lordscar - Mk. X", en: "Silverhand Lordscar - Mk. X", origin: "vehicle", category: "Техника" },
  { code: "ScoutVehicleOffensiveW", name: "Spitfire", en: "Drummond Spitfire 100d", origin: "vehicle", category: "Техника" },
  { code: "FacilityMaterials3", name: "Steel Construction Materials", en: "Steel Construction Materials", origin: "item", category: "Материалы" },
  { code: "LRArtillery", name: "Storm Cannon", en: "Storm Cannon", origin: "structure", category: "Сооружения" },
  { code: "Sulfur", name: "Sulfur", en: "Sulfur", origin: "item", category: "Материалы" },
  { code: null, name: "Swallowtail emergency services", en: null, origin: "item", category: "Техника" },
  { code: "TanketteC", name: "T12 “Actaeon” Tankette", en: "T12 “Actaeon” Tankette", origin: "vehicle", category: "Техника" },
  { code: "TanketteMultiC", name: "T13 “Deioneus” Rocket Battery", en: "T13 “Deioneus” Rocket Battery", origin: "vehicle", category: "Техника" },
  { code: "TanketteFlameC", name: "T14 “Vesta” Tankette", en: "T14 “Vesta” Tankette", origin: "vehicle", category: "Техника" },
  { code: "TanketteOffensiveC", name: "T20 “Ixion” Tankette", en: "T20 “Ixion” Tankette", origin: "vehicle", category: "Техника" },
  { code: "ArmoredCarC", name: "T3 “Xiphos”", en: "T3 “Xiphos”", origin: "vehicle", category: "Техника" },
  { code: "ArmoredCarOffensiveC", name: "T5 “Percutio”", en: "T5 “Percutio”", origin: "vehicle", category: "Техника" },
  { code: "ArmoredCarTwinC", name: "T8 “Gemini”", en: "T8 “Gemini”", origin: "vehicle", category: "Техника" },
  { code: "TankUniformC", name: "Tankman's Coveralls", en: "Tankman's Coveralls", origin: "item", category: "Снаряжение" },
  { code: "TrainLRArtillery", name: "Tempest Cannon RA-2", en: "Tempest Cannon RA-2", origin: "vehicle", category: "Техника" },
  { code: "AircraftTorpedoAmmo", name: "Tenta Torpedo", en: "Tenta Torpedo", origin: "item", category: "Боеприпасы" },
  { code: "AircraftFighterC", name: "Toxot-902 “Blind Silver”", en: "Toxot-902 “Blind Silver”", origin: "vehicle", category: "Техника" },
  { code: "AircraftWaterW", name: "Tulka I1.9 White Raven", en: "Tulka I1.9 White Raven", origin: "vehicle", category: "Техника" },
  { code: "AircraftBomberW", name: "Tulka P4 Welkinrive", en: "Tulka P4 Welkinrive", origin: "vehicle", category: "Техника" },
  { code: "Gunboat2C", name: "Type B - “Lucian”", en: "Type B - “Lucian”", origin: "vehicle", category: "Техника" },
  { code: "GunboatC", name: "Type C - “Charon”", en: "Type C - “Charon”", origin: "vehicle", category: "Техника" },
  { code: "FacilityMaterials10", name: "Unstable Substances", en: "Unstable Substances", origin: "item", category: "Материалы" },
  { code: "ScoutVehicleMobilityC", name: "UV-05a “Argonaut”", en: "UV-05a “Argonaut”", origin: "vehicle", category: "Техника" },
  { code: "ScoutVehicleOffensiveC", name: "UV-24 “Icarus”", en: "UV-24 “Icarus”", origin: "vehicle", category: "Техника" },
  { code: "AircraftBomberC", name: "V-1 Tzykalia", en: "V-1 Tzykalia", origin: "vehicle", category: "Техника" },
  { code: "AircraftParatrooperC", name: "V-5b Pegasus", en: "V-5b Pegasus", origin: "vehicle", category: "Техника" },
  { code: "ArmourUniformC", name: "Velian Flak Vest", en: "Velian Flak Vest", origin: "item", category: "Снаряжение" },
  { code: "ATRPGC", name: "Venom c.II 35", en: "Venom c.II 35", origin: "item", category: "Оружие" },
  { code: "RifleHeavyC", name: "Volta r.I Repeater", en: "Volta r.I Repeater", origin: "item", category: "Оружие" },
  { code: "BannerTW", name: "War Ensign", en: "War Ensign", origin: "item", category: "Снаряжение" },
  { code: "FlameTorchW", name: "Willow's Bane Model 845", en: "Willow's Bane Model 845", origin: "item", category: "Оружие" },
  { code: "WindsockT", name: "Wind Sock", en: "Wind Sock", origin: "item", category: "Снаряжение" },
  { code: "WoundedCarriedPlayer", name: "Wounded Player", en: "Wounded Player", origin: "item", category: "Прочее" },
  { code: "Wreckage", name: "Wreckage", en: "Wreckage", origin: "item", category: "Прочее" },
  { code: "BusW", name: "автобус", en: "Dunne Caravaner 2f", origin: "vehicle", category: "Техника" },
  { code: "AluminumA", name: "Алюминий", en: "Aluminum Alloy", origin: "item", category: "Материалы" },
  { code: "ATRPGAmmo", name: "АРПГ Снаряды", en: "AP⧸RPG", origin: "item", category: "Боеприпасы" },
  { code: null, name: "Базовые материалы", en: null, origin: "item", category: "Материалы" },
  { code: "Barge", name: "баржа", en: "BMS - Aquatipper", origin: "vehicle", category: "Техника" },
  { code: "Petrol", name: "Бензин", en: "Petrol", origin: "item", category: "Материалы" },
  { code: "ConcreteMixer", name: "Бетономешалка", en: null, origin: "other", category: "Материалы" },
  { code: "Cloth", name: "биматы", en: "Basic Materials", origin: "item", category: "Материалы" },
  { code: "Binoculars", name: "бинокль", en: "Binoculars", origin: "item", category: "Снаряжение" },
  { code: "Bandages", name: "бинт", en: "Bandages", origin: "item", category: "Медицина" },
  { code: null, name: "Бинты", en: null, origin: "item", category: "Медицина" },
  { code: "ArmoredCarFlameW", name: "Бронеавтомобиль с огнемётом", en: "O'Brien V.130 Wild Jack", origin: "vehicle", category: "Техника" },
  { code: null, name: "Бронебойный навесной/РПГ", en: null, origin: "item", category: "Оружие" },
  { code: null, name: "Бронебойный/РПГ", en: null, origin: "item", category: "Оружие" },
  { code: "ArmoredCar2LargeW", name: "бронированная дюна", en: "O'Brien V.101 Freeman", origin: "vehicle", category: "Техника" },
  { code: "Gunboat2W", name: "БТР-Амфибия (Mulloy)", en: "81f-f Ronan Blackguard", origin: "vehicle", category: "Техника" },
  { code: "LandingCraftW", name: "БТР-Амфибия (Mulloy)", en: "Mulloy LPC", origin: "vehicle", category: "Техника" },
  { code: "WaterBucket", name: "Ведро для воды", en: "Water Bucket", origin: "item", category: "Материалы" },
  { code: null, name: "Ветроуказатель", en: null, origin: "item", category: "Снаряжение" },
  { code: "RifleLightW", name: "винтовка Blakerov", en: "Blakerow 871", origin: "item", category: "Оружие" },
  { code: "RifleW", name: "Винтовка No.2 Loughcaster", en: "No.2 Loughcaster", origin: "item", category: "Оружие" },
  { code: "RifleAutomaticW", name: "Винтовка Sampo 77", en: "Sampo Auto-Rifle 77", origin: "item", category: "Оружие" },
  { code: "Water", name: "вода", en: "Water", origin: "item", category: "Материалы" },
  { code: "WorkWrench", name: "Гаечный ключ", en: "Wrench", origin: "item", category: "Снаряжение" },
  { code: "GreenAsh", name: "газовая граната", en: "Green Ash Grenade", origin: "item", category: "Оружие" },
  { code: "GroundMaterials", name: "гравий", en: "Gravel", origin: "item", category: "Материалы" },
  { code: "ATGrenadeW", name: "Граната BF5 White Ash Flask", en: "BF5 White Ash Flask Grenade", origin: "item", category: "Оружие" },
  { code: "TruckW", name: "грузовик", en: "Dunne Transport", origin: "vehicle", category: "Техника" },
  { code: "ShippingContainer", name: "Грузовой контейнер", en: "Shipping Container", origin: "structure", category: "Сооружения" },
  { code: "LandingCraftC", name: "десантный катер", en: "AB-8 “Acheron”", origin: "vehicle", category: "Техника" },
  { code: "FortWeatherStationPart", name: "Детали погодной станции", en: null, origin: "other", category: "Прочее" },
  { code: "FortGarrisonStationPart", name: "Детали подземной крепости", en: null, origin: "other", category: "Прочее" },
  { code: "FortLRArtilleryPart", name: "Детали Штурмового Орудия", en: null, origin: "other", category: "Прочее" },
  { code: null, name: "Детонатор Хавок Заряда", en: null, origin: "item", category: "Оружие" },
  { code: "Diesel", name: "Дизель", en: "Diesel", origin: "item", category: "Материалы" },
  { code: "ShotgunW", name: "дробовик", en: "No.4 The Pillory Scattergun", origin: "item", category: "Оружие" },
  { code: "ShotgunAmmo", name: "дробь", en: "Buckshot", origin: "item", category: "Боеприпасы" },
  { code: "SmokeGrenade", name: "дымовая граната", en: "PT-815 Smoke Grenade", origin: "item", category: "Оружие" },
  { code: null, name: "Дымовая граната PT-815", en: null, origin: "item", category: "Оружие" },
  { code: "TruckDefensiveW", name: "Дюна", en: "Dunne Leatherback 2a", origin: "vehicle", category: "Техника" },
  { code: "TruckLiquidW", name: "Дюна бензовоз", en: "Dunne Fuelrunner 2d", origin: "vehicle", category: "Техника" },
  { code: "LiquidContainer", name: "Жидкостный контейнер", en: "Liquid Container", origin: "structure", category: "Сооружения" },
  { code: "TrailerLiquid", name: "Жидкостный прицеп", en: "Rooster - Lamploader", origin: "vehicle", category: "Техника" },
  { code: null, name: "Зажигал. минометный снаряд", en: null, origin: "item", category: "Боеприпасы" },
  { code: "MortarAmmoFlame", name: "Зажигательный миномётный снаряд", en: "Incendiary Mortar Shell", origin: "item", category: "Боеприпасы" },
  { code: "SatchelChargeT", name: "Заряд Аллигатор", en: null, origin: "other", category: "Оружие" },
  { code: "AAAmmo", name: "Зенитный снаряд 950-70b", en: "950-70b Anti-Aircraft Shell", origin: "item", category: "Боеприпасы" },
  { code: "LightAAAmmo", name: "Зенитный снаряд “Absol”", en: "Absol Anti-Aircraft Rounds", origin: "item", category: "Боеприпасы" },
  { code: "SnowUniformW", name: "зимняя униформа", en: null, origin: "other", category: "Снаряжение" },
  { code: "HeavyTruckW", name: "кнут", en: "Cnute Cliffwrest", origin: "vehicle", category: "Техника" },
  { code: "BarbedWireMaterials", name: "колючая проволока", en: "Barbed Wire", origin: "item", category: "Материалы" },
  { code: "Components", name: "Компоненты", en: "Components", origin: "item", category: "Материалы" },
  { code: "ShipPart3", name: "Компоненты морских турбин", en: "Naval Turbine Components", origin: "structure", category: "Сооружения" },
  { code: "ResourceContainer", name: "контейнер для ресурсов", en: "Resource Container", origin: "structure", category: "Сооружения" },
  { code: "ShipPart2", name: "Корабельная обшивка корпуса", en: "Naval Shell Plating", origin: "structure", category: "Сооружения" },
  { code: "ShipPart1", name: "Корабельный сегмент корпуса", en: "Naval Hull Segments", origin: "structure", category: "Сооружения" },
  { code: "RocketPartCenter", name: "Корпус ракеты AOE-9", en: "A0E-9 Rocket Body", origin: "structure", category: "Сооружения" },
  { code: "SledgeHammer", name: "кувалда", en: "Sledge Hammer", origin: "item", category: "Снаряжение" },
  { code: "LightTankArtilleryW", name: "Легкий арт-танк", en: "Devitt-Caine Mk. IV MMR", origin: "vehicle", category: "Техника" },
  { code: "StickyBomb", name: "липкая бомба (стика)", en: "Anti-Tank Sticky Bomb", origin: "item", category: "Боеприпасы" },
  { code: "Shovel", name: "лопата", en: "Shovel", origin: "item", category: "Снаряжение" },
  { code: "LightBoatInfantryW", name: "лёгкая пехотная лодка", en: "68A-4 Ronan Fathomer", origin: "vehicle", category: "Техника" },
  { code: "HEGrenade", name: "Маммонка", en: "Mammon 91-b", origin: "item", category: "Оружие" },
  { code: "PilotMask", name: "Маска пилота", en: "Flight Mask", origin: "item", category: "Снаряжение" },
  { code: "ScoutVehicleUtilityC", name: "Машина скорой помощи", en: "UV-5c “Odyssey”", origin: "vehicle", category: "Техника" },
  { code: "CopperA", name: "Медь", en: "Copper Alloy", origin: "item", category: "Материалы" },
  { code: "MetalBeamMaterials", name: "металлическая балка", en: "Metal Beam", origin: "item", category: "Материалы" },
  { code: "SandbagMaterials", name: "Мешки с песком (материалы)", en: "Sandbag", origin: "item", category: "Материалы" },
  { code: null, name: "Мешок с песком", en: null, origin: "item", category: "Материалы" },
  { code: "Mortar", name: "миномёт", en: "Cremari Mortar", origin: "item", category: "Оружие" },
  { code: null, name: "Миномёт Cremari", en: null, origin: "item", category: "Оружие" },
  { code: "MortarAmmo", name: "миномётный снаряд", en: "Mortar Shell", origin: "item", category: "Боеприпасы" },
  { code: "ArmoredCarMobilityW", name: "Мобильная бронемашина", en: "O'Brien V.121 Highlander", origin: "vehicle", category: "Техника" },
  { code: "Crane", name: "мобильный кран", en: "BMS - Class 2 Mobile Auto-Crane", origin: "vehicle", category: "Техника" },
  { code: null, name: "Молоток", en: null, origin: "item", category: "Снаряжение" },
  { code: "SurfaceWaterMine", name: "Морская мина E681-B", en: "E681-B Hullbreaker Mine", origin: "item", category: "Оружие" },
  { code: "MotorcycleW", name: "Мотоцикл", en: "Kivela Power Wheel 80-1", origin: "vehicle", category: "Техника" },
  { code: "ListeningKit", name: "Набор для прослушивания", en: "Listening Kit", origin: "item", category: "Снаряжение" },
  { code: "FirstAidKit", name: "Набор Первой Помощи", en: "First Aid Kit", origin: "item", category: "Медицина" },
  { code: "Unknown", name: "Неизвестно", en: null, origin: "other", category: "Прочее" },
  { code: null, name: "Нестабильные материалы", en: null, origin: "item", category: "Материалы" },
  { code: "Oil", name: "Нефть", en: "Oil", origin: "item", category: "Материалы" },
  { code: "FacilityOil1", name: "Нефть для объекта I", en: "Heavy Oil", origin: "item", category: "Материалы" },
  { code: "FacilityOil2", name: "Нефть для объекта II", en: "Enriched Oil", origin: "item", category: "Материалы" },
  { code: "FacilityOil3", name: "Нефть для объекта III", en: null, origin: "other", category: "Материалы" },
  { code: null, name: "Огнемётное топливо", en: null, origin: "item", category: "Материалы" },
  { code: "FlameAmmo", name: "Огненные патроны", en: "Flame Ammo", origin: "item", category: "Боеприпасы" },
  { code: "MortarAmmoFL", name: "Осветительный миномётный снаряд", en: "Flare Mortar Shell", origin: "item", category: "Боеприпасы" },
  { code: "GrenadeW", name: "Осколочная граната", en: "A3 Harpa Fragmentation Grenade", origin: "item", category: "Оружие" },
  { code: null, name: "Осколочная граната A3 Harpa", en: null, origin: "item", category: "Оружие" },
  { code: "MortarAmmoSH", name: "Осколочный миномётный снаряд", en: "Shrapnel Mortar Shell", origin: "item", category: "Боеприпасы" },
  { code: "HELaunchedGrenade", name: "Осколочный снаряд РПГ", en: "Tremola Grenade GPb-1", origin: "item", category: "Боеприпасы" },
  { code: "OfficerUniformW", name: "офицерская форма", en: "Officer's Regalia", origin: "item", category: "Снаряжение" },
  { code: "SMGW", name: "Пистолет пулемет Fiddler", en: "Fiddler Submachine Gun Model 868", origin: "item", category: "Оружие" },
  { code: "SMGHeavyW", name: "Пистолет-пулемёт No.1", en: "No.1 “The Liar” Submachine Gun", origin: "item", category: "Оружие" },
  { code: "BloodPlasma", name: "Плазма", en: "Blood Plasma", origin: "item", category: "Медицина" },
  { code: null, name: "Повреждённый Колониальный авиадвигатель", en: null, origin: "item", category: "Материалы" },
  { code: "MaterialPlatform", name: "Поддон для материалов", en: "Material Pallet", origin: "structure", category: "Сооружения" },
  { code: "GrenadeAdapter", name: "Подствольный гранатомёт", en: null, origin: "other", category: "Оружие" },
  { code: "AmbulanceFlameW", name: "пожарная машина", en: "Dunne Dousing Engine 3r", origin: "vehicle", category: "Техника" },
  { code: "MediumBoatC", name: "пожарная машина", en: "Strider", origin: "vehicle", category: "Техника" },
  { code: "LargeFieldMultiW", name: "Полевая многозарядная установка", en: "Rycker 4/3-F Wasp Nest", origin: "vehicle", category: "Техника" },
  { code: "FieldATW", name: "Полевая противотанковая пушка", en: "Collins Cannon 68mm", origin: "vehicle", category: "Техника" },
  { code: "FieldCannonW", name: "Полевое орудие", en: "Balfour Wolfhound 40mm", origin: "vehicle", category: "Техника" },
  { code: "FieldMGW", name: "Полевой пулемёт", en: "Swallowtail 988/127-2", origin: "vehicle", category: "Техника" },
  { code: "HalfTrackW", name: "Полугусеничный бронеавтомобиль", en: "Niska Mk. I Gun Motor Carriage", origin: "vehicle", category: "Техника" },
  { code: "Explosive", name: "порох", en: "Explosive Powder", origin: "item", category: "Материалы" },
  { code: null, name: "Припасы Обслуживания", en: null, origin: "item", category: "Материалы" },
  { code: "GasMask", name: "противогаз", en: "Gas Mask", origin: "item", category: "Медицина" },
  { code: "ATRifleW", name: "противотанковое ружье 20мм", en: "Neville Anti-Tank Rifle", origin: "item", category: "Оружие" },
  { code: "ATRPGW", name: "Противотанковый РПГ (станковый)", en: "Bonesaw MK.3", origin: "item", category: "Оружие" },
  { code: "RadioBackpack", name: "Радиорюкзак", en: "Radio Backpack", origin: "item", category: "Снаряжение" },
  { code: "FortIntelCenterPart", name: "Разведывательный Центр", en: null, origin: "other", category: "Прочее" },
  { code: "DemolitionRocketAmmo", name: "Разрушающая ракета", en: "Shatter Missile", origin: "item", category: "Боеприпасы" },
  { code: "Radio", name: "рация", en: "Radio", origin: "item", category: "Снаряжение" },
  { code: null, name: "Реанимационный набор", en: null, origin: "item", category: "Медицина" },
  { code: "Revolver", name: "револьвер", en: "Cometa T2-9", origin: "item", category: "Оружие" },
  { code: "RareMaterials", name: "Редкие материалы", en: null, origin: "other", category: "Материалы" },
  { code: "RareMetal", name: "Редкий металл", en: "Rare Metal", origin: "item", category: "Материалы" },
  { code: null, name: "Реликтовые материалы", en: null, origin: "item", category: "Материалы" },
  { code: "TrailerResource", name: "Ресурсный прицеп", en: "Rooster - Junkwagon", origin: "vehicle", category: "Техника" },
  { code: null, name: "РПГ", en: null, origin: "item", category: "Оружие" },
  { code: null, name: "РПГ \"Carnyx\"", en: null, origin: "item", category: "Оружие" },
  { code: "RPGTW", name: "РПГ (танковый вариант)", en: "Cutler Foebreaker", origin: "item", category: "Оружие" },
  { code: "SoldierSupplies", name: "рубашки", en: "Soldier Supplies", origin: "item", category: "Материалы" },
  { code: null, name: "Рюкзак Десантника", en: null, origin: "item", category: "Снаряжение" },
  { code: "TruckResourceW", name: "самосвал", en: "Dunne Loadlugger 3c", origin: "vehicle", category: "Техника" },
  { code: null, name: "Сапёрное снаряжение", en: null, origin: "item", category: "Снаряжение" },
  { code: "FacilityMaterials1", name: "Сборочные материалы I", en: "Construction Materials", origin: "item", category: "Материалы" },
  { code: null, name: "Сборочные материалы II", en: null, origin: "item", category: "Материалы" },
  { code: "FacilityMaterials4", name: "Сборочные материалы IV", en: "Assembly Materials I", origin: "item", category: "Материалы" },
  { code: null, name: "Сирена воздушной тревоги", en: null, origin: "item", category: "Снаряжение" },
  { code: "AmbulanceW", name: "скорая помощь", en: "Dunne Responder 3e", origin: "vehicle", category: "Техника" },
  { code: "MortarTankAmmo", name: "Снаряд миномётного танка", en: "250mm “Purity” Shell", origin: "item", category: "Боеприпасы" },
  { code: "MortarTankAmmoBR", name: "Снаряд миномётного танка (бронебойный)", en: "250mm “Fury” Shell", origin: "item", category: "Боеприпасы" },
  { code: "RpgAmmo", name: "снаряд РПГ", en: "RPG", origin: "item", category: "Боеприпасы" },
  { code: "MiniTankAmmo", name: "Снаряды малого танка", en: "30mm", origin: "item", category: "Боеприпасы" },
  { code: null, name: "Солдатские припасы (Имки)", en: null, origin: "item", category: "Материалы" },
  { code: "MaintenanceSupplies", name: "Сопли", en: "Maintenance Supplies", origin: "item", category: "Материалы" },
  { code: "MediumTank2W", name: "Средний танк (тир 2)", en: "Gallagher Brigand Mk. I", origin: "vehicle", category: "Техника" },
  { code: "MediumBoatW", name: "Средняя лодка варденов", en: "Rinnspeir Ornitier-Class Gunship", origin: "vehicle", category: "Техника" },
  { code: null, name: "Сталь", en: null, origin: "item", category: "Материалы" },
  { code: "ArmourUniformW", name: "Стальная кираса", en: "Gunner's Breastplate", origin: "item", category: "Материалы" },
  { code: "ExplosiveTripod", name: "Станковый Fissura gd.I", en: null, origin: "other", category: "Материалы" },
  { code: "MGTW", name: "Станковый пулемет варденов", en: "Malone Ratcatcher MK.1", origin: "item", category: "Оружие" },
  { code: "ConstructionUtility", name: "Строительная техника", en: "BMS - Fabricator", origin: "vehicle", category: "Техника" },
  { code: "ConstructionEquipment", name: "Строительное оборудование", en: null, origin: "other", category: "Прочее" },
  { code: "FortConstructionPart", name: "Строительные детали", en: null, origin: "other", category: "Прочее" },
  { code: null, name: "Строительные материалы", en: null, origin: "item", category: "Материалы" },
  { code: "LightTankC", name: "строительный прицеп", en: "H-5 “Hatchet”", origin: "vehicle", category: "Техника" },
  { code: "TrailerMaterial", name: "строительный прицеп", en: "Rooster - Tumblebox", origin: "vehicle", category: "Техника" },
  { code: "Freighter", name: "судно Ironship", en: "BMS - Ironship", origin: "vehicle", category: "Техника" },
  { code: "FreighterLight", name: "судно Krokodil", en: "Das Krokodil by VAC", origin: "vehicle", category: "Техника" },
  { code: "FlameBackpackW", name: "Топливо для Willow", en: "Willow's Bane Ammo", origin: "item", category: "Материалы" },
  { code: "MiniTorpedoAmmo", name: "торпеда", en: "Quillback Torpedo", origin: "item", category: "Боеприпасы" },
  { code: null, name: "Торпеда \"Quillback\"", en: null, origin: "item", category: "Боеприпасы" },
  { code: "TraumaKit", name: "Травма-аптечка", en: "Trauma Kit", origin: "item", category: "Медицина" },
  { code: "Tripod", name: "Тренога", en: "Tripod", origin: "item", category: "Снаряжение" },
  { code: null, name: "Труба", en: null, origin: "item", category: "Материалы" },
  { code: null, name: "Тяжелое топливо", en: null, origin: "item", category: "Материалы" },
  { code: "HeavyExplosive", name: "Тяжёлая взрывчатка", en: "Heavy Explosive Powder", origin: "item", category: "Материалы" },
  { code: null, name: "Тяжёлый порох", en: null, origin: "item", category: "Материалы" },
  { code: "GasMaskFilter", name: "Фильтр для противогаза", en: "Gas Mask Filter", origin: "item", category: "Медицина" },
  { code: null, name: "Флаг Варденов", en: null, origin: "item", category: "Снаряжение" },
  { code: null, name: "Флаг Колонистов", en: null, origin: "item", category: "Снаряжение" },
  { code: "FlatbedTruck", name: "Флэтбед (пакмул)", en: "BMS - Packmule Flatbed", origin: "vehicle", category: "Техника" },
  { code: "EngineerUniformW", name: "форма инженера", en: "Sapper Gear", origin: "item", category: "Снаряжение" },
  { code: "MedicUniformW", name: "форма медика", en: "Physician's Jacket", origin: "item", category: "Медицина" },
  { code: "NavalUniformW", name: "форма моряка", en: "Gentleman's Peacoat", origin: "item", category: "Материалы" },
  { code: "ScoutUniformW", name: "форма разведчика", en: "Outrider's Mantle", origin: "item", category: "Снаряжение" },
  { code: "TankUniformW", name: "форма танкиста", en: "Padded Boiler Suit", origin: "item", category: "Снаряжение" },
  { code: "SatchelChargeW", name: "Хавок Заряд", en: "Alligator Charge", origin: "item", category: "Оружие" },
  { code: "RifleHeavyW", name: "Хангман 757", en: "The Hangman 757", origin: "item", category: "Оружие" },
  { code: "AmmoUniformW", name: "шинель специалиста", en: "Specialist's Overcoat", origin: "item", category: "Боеприпасы" },
  { code: null, name: "Штурмовая винтовка Aalto 24", en: null, origin: "item", category: "Оружие" },
  { code: null, name: "Штурмовая винтовка Booker Model 838", en: null, origin: "item", category: "Оружие" },
  { code: "Bayonet", name: "штык-нож", en: "Buckhorn CCQ-18", origin: "item", category: "Оружие" },
  { code: "StructureCrate", name: "Ящик с сооружениями", en: "Shippable Crate", origin: "structure", category: "Сооружения" },
  { code: "ATRifleLightC", name: "“Dawn” Ve.II", en: "“Dawn” Ve.II", origin: "item", category: "Оружие" },
  { code: "AssaultRifleHeavyC", name: "“Dusk” ce.III", en: "“Dusk” ce.III", origin: "item", category: "Оружие" },
  { code: "SMGHeavyC", name: "“Lionclaw” mc.VIII", en: "“Lionclaw” mc.VIII", origin: "item", category: "Оружие" },
  { code: "FlameBackpackC", name: "“Molten Wind” v.II Ammo", en: "“Molten Wind” v.II Ammo", origin: "item", category: "Оружие" },
  { code: "FlameTorchC", name: "“Molten Wind” v.II Flame Torch", en: "“Molten Wind” v.II Flame Torch", origin: "item", category: "Оружие" },
  { code: "ATRifleSniperC", name: "“Quickhatch” Rt.I", en: "“Quickhatch” Rt.I", origin: "item", category: "Оружие" },
  { code: "SMGC", name: "“The Pitch Gun” mc.V", en: "“The Pitch Gun” mc.V", origin: "item", category: "Оружие" },
  { code: "ATRifleTC", name: "“Typhon” ra.XII", en: "“Typhon” ra.XII", origin: "item", category: "Оружие" },
];
export const ITEM_OPTIONS: string[] = ITEM_CATALOG.map((i) => i.name);
export const ITEM_CODE_MAP: Record<string, string> = Object.fromEntries(ITEM_CATALOG.filter((i) => i.code).map((i) => [i.code as string, i.name]));
