// СГЕНЕРИРОВАНО scripts/extract-matrix.mjs — матрица предметов из дистрибутива штаба (часть 3)
export type ItemCategory = "Оружие" | "Боеприпасы" | "Материалы" | "Медицина" | "Снаряжение" | "Техника" | "Сооружения" | "Прочее";

export interface GeneItem {
  id: string;
  /** Англ. / вики-название (код из рапорта сканера) */
  title: string;
  /** Отображаемое название */
  ru: string;
  cat: ItemCategory;
  /** Файл иконки в /FoxholeWikiPhotos или null */
  icon: string | null;
}

export const ITEM_CATEGORIES: ItemCategory[] = ["Оружие", "Боеприпасы", "Материалы", "Медицина", "Снаряжение", "Техника", "Сооружения", "Прочее"];

export const GENE_ITEMS: GeneItem[] = [
  { id: "44-mag-0", title: ".44 Mag", ru: ".44 Магнум", cat: "Боеприпасы", icon: "RevolverAmmo.webp" },
  { id: "00ms-stinger-1", title: "00MS “Stinger”", ru: "00MS “Stinger”", cat: "Техника", icon: "MotorcycleOffensiveVehicleC.webp" },
  { id: "03mm-caster-2", title: "03MM “Caster”", ru: "03MM “Caster”", cat: "Техника", icon: "MotorcycleVehicleC.webp" },
  { id: "12-7mm-3", title: "12.7mm", ru: "12.7 мм (пулемётные) патроны", cat: "Боеприпасы", icon: "MachineGunAmmo.webp" },
  { id: "12-7-мм-4", title: "12.7-мм", ru: "12.7-мм", cat: "Боеприпасы", icon: "MachineGunAmmo.webp" },
  { id: "120-68-koronides-field-gun-5", title: "120-68 “Koronides” Field Gun", ru: "120-68 “Koronides” Field Gun", cat: "Техника", icon: "FieldArtilleryColVehicle.webp" },
  { id: "120-мм-6", title: "120-мм", ru: "120-мм", cat: "Боеприпасы", icon: "LightArtilleryAmmo.webp" },
  { id: "120mm-7", title: "120mm", ru: "120мм снаряды", cat: "Боеприпасы", icon: "AircraftAmmo.webp" },
  { id: "14-5mm-8", title: "14.5mm", ru: "14.5 мм", cat: "Боеприпасы", icon: "ATRifleAmmo.webp" },
  { id: "150-мм-9", title: "150-мм", ru: "150-мм", cat: "Боеприпасы", icon: "HeavyArtilleryAmmo.webp" },
  { id: "150mm-10", title: "150mm", ru: "150мм снаряды", cat: "Боеприпасы", icon: "HeavyArtilleryAmmo.webp" },
  { id: "20мм-11", title: "20мм", ru: "20мм", cat: "Боеприпасы", icon: "AircraftAmmo.webp" },
  { id: "20mm-12", title: "20mm", ru: "20мм (зенитные) патроны", cat: "Боеприпасы", icon: "AircraftAmmo.webp" },
  { id: "228-satterley-heavy-storm-rifle-13", title: "228 Satterley Heavy Storm Rifle", ru: "228 Satterley Heavy Storm Rifle", cat: "Оружие", icon: "ATRifleAssaultWtga.webp" },
  { id: "30-250-tisiphone-field-cannon-14", title: "30-250 “Tisiphone” Field Cannon", ru: "30-250 “Tisiphone” Field Cannon", cat: "Техника", icon: "FieldMortarC.webp" },
  { id: "300-мм-15", title: "300-мм", ru: "300-мм", cat: "Боеприпасы", icon: null },
  { id: "300mm-16", title: "300mm", ru: "300mm", cat: "Боеприпасы", icon: "LRArtilleryAmmo.webp" },
  { id: "30мм-17", title: "30мм", ru: "30мм", cat: "Боеприпасы", icon: null },
  { id: "3c-high-explosive-rocket-18", title: "3C-High Explosive Rocket", ru: "3C-High Explosive Rocket", cat: "Боеприпасы", icon: "HERocketAmmo.webp" },
  { id: "40-250-alekto-heavy-cannon-19", title: "40-250 “Alekto” Heavy Cannon", ru: "40-250 “Alekto” Heavy Cannon", cat: "Техника", icon: "LargeFieldMortarC.webp" },
  { id: "40-45-smelter-20", title: "40-45 “Smelter”", ru: "40-45 “Smelter”", cat: "Техника", icon: "FieldATOffensiveC.webp" },
  { id: "40mm-21", title: "40mm", ru: "40-мм", cat: "Боеприпасы", icon: "LightTankAmmo.webp" },
  { id: "4c-fire-rocket-22", title: "4C-Fire Rocket", ru: "4C-Fire Rocket", cat: "Боеприпасы", icon: "FlameRocketAmmo.webp" },
  { id: "50-500-thunderbolt-cannon-23", title: "50-500 “Thunderbolt” Cannon", ru: "50-500 Thunderbolt Cannon", cat: "Сооружения", icon: null },
  { id: "68mm-24", title: "68mm", ru: "68-мм", cat: "Боеприпасы", icon: "ATAmmo.webp" },
  { id: "7-52-мм-25", title: "7.52-мм", ru: "7.52-мм", cat: "Боеприпасы", icon: null },
  { id: "7-62mm-26", title: "7.62mm", ru: "7.62-мм", cat: "Боеприпасы", icon: "RifleAmmo.webp" },
  { id: "7-92mm-27", title: "7.92mm", ru: "7.92 мм", cat: "Боеприпасы", icon: "AssaultRifleAmmo.webp" },
  { id: "74b-1-ronan-gunship-28", title: "74b-1 Ronan Gunship", ru: "74b-1 Ronan Gunship", cat: "Техника", icon: "GunboatW.webp" },
  { id: "75mm-29", title: "75mm", ru: "75mm", cat: "Боеприпасы", icon: "BattleTankAmmo.webp" },
  { id: "8-мм-30", title: "8-мм", ru: "8-мм", cat: "Боеприпасы", icon: "ATAmmo.webp" },
  { id: "85k-a-spatha-31", title: "85K-a “Spatha”", ru: "85K-a “Spathа”", cat: "Техника", icon: "ColonialMediumTankOffensive.webp" },
  { id: "85k-b-falchion-32", title: "85K-b “Falchion”", ru: "85K-b “Falchion”", cat: "Техника", icon: "ColonialMediumTank.webp" },
  { id: "85v-g-talos-33", title: "85V-g “Talos”", ru: "85V-g “Talos”", cat: "Техника", icon: "MediumTankLargeC.webp" },
  { id: "86k-a-bardiche-34", title: "86K-a “Bardiche”", ru: "86K-a “Bardiche”", cat: "Техника", icon: "MediumTank2C.webp" },
  { id: "86k-c-ranseur-35", title: "86K-c “Ranseur”", ru: "86K-c “Ranseur”", cat: "Техника", icon: "MediumTank2TwinCVehicle.webp" },
  { id: "8mm-36", title: "8mm", ru: "8мм (пистолет)", cat: "Боеприпасы", icon: "PistolAmmo.webp" },
  { id: "90t-v-nemesis-37", title: "90T-v “Nemesis”", ru: "90T-v “Nemesis”", cat: "Техника", icon: "MediumTank3CItem.webp" },
  { id: "912-shrike-rounds-38", title: "912 Shrike Rounds", ru: "912 Shrike Rounds", cat: "Боеприпасы", icon: "DiveBomberAmmo.webp" },
  { id: "94-5мм-39", title: "94.5мм", ru: "94.5мм", cat: "Боеприпасы", icon: "ATLargeAmmo.webp" },
  { id: "94-5mm-40", title: "94.5mm", ru: "94.5мм снаряды", cat: "Боеприпасы", icon: "ATLargeAmmo.webp" },
  { id: "945g-stygian-bolt-41", title: "945g “Stygian Bolt”", ru: "945g “Stygian Bolt”", cat: "Техника", icon: "FieldATHeavyC.webp" },
  { id: "950-70b-зенитный-снаряд-42", title: "950-70b Зенитный снаряд", ru: "950-70b Зенитный снаряд", cat: "Боеприпасы", icon: null },
  { id: "9mm-43", title: "9mm", ru: "9мм", cat: "Боеприпасы", icon: "SubMachineGunAmmo.webp" },
  { id: "a0e-9-rocket-44", title: "A0E-9 Rocket", ru: "A0E-9 Rocket", cat: "Сооружения", icon: "Rocket.jpg" },
  { id: "a0e-9-rocket-platform-45", title: "A0E-9 Rocket Platform", ru: "A0E-9 Rocket Platform", cat: "Сооружения", icon: "RocketSite.webp" },
  { id: "a3-harpa-осколочная-граната-46", title: "A3 Harpa Осколочная граната", ru: "A3 Harpa Осколочная граната", cat: "Оружие", icon: "GrenadeW.webp" },
  { id: "a51-venti-daedalus-47", title: "A51 Venti “Daedalus”", ru: "A51 Venti “Daedalus”", cat: "Техника", icon: "AircraftScoutCIcon.webp" },
  { id: "a59-venti-perdix-48", title: "A59 Venti “Perdix”", ru: "A59 Venti “Perdix”", cat: "Техника", icon: "AircraftScout2CIcon.webp" },
  { id: "aa-2-battering-ram-49", title: "AA-2 Battering Ram", ru: "AA-2 Battering Ram", cat: "Техника", icon: "FieldAntiTankColVehicle.webp" },
  { id: "aalto-автоматическая-винтовка-24-50", title: "Aalto Автоматическая винтовка 24", ru: "Aalto Автоматическая винтовка 24", cat: "Оружие", icon: null },
  { id: "aalto-storm-rifle-24-51", title: "Aalto Storm Rifle 24", ru: "Aalto Storm Rifle 24", cat: "Оружие", icon: "AssaultRifleItem.webp" },
  { id: "ab-11-doru-52", title: "AB-11 “Doru”", ru: "AB-11 “Doru”", cat: "Техника", icon: "LandingCraftOffensiveVehicleC.webp" },
  { id: "abisme-at-99-53", title: "Abisme AT-99", ru: "Abisme AT-99", cat: "Оружие", icon: "AntiTankMine.webp" },
  { id: "abisme-at-99-mine-54", title: "Abisme AT-99 Mine", ru: "Abisme AT-99 Mine", cat: "Оружие", icon: "AntiTankMine.webp" },
  { id: "ahti-model-2-55", title: "Ahti Model 2", ru: "Ahti Model 2", cat: "Оружие", icon: "PistolW.webp" },
  { id: "air-raid-siren-56", title: "Air Raid Siren", ru: "Air Raid Siren", cat: "Снаряжение", icon: "AirSirenT.webp" },
  { id: "aircraft-depot-57", title: "Aircraft Depot", ru: "Aircraft Depot", cat: "Сооружения", icon: "AircraftDepot.png" },
  { id: "aircraft-hangar-58", title: "Aircraft Hangar", ru: "Aircraft Hangar", cat: "Сооружения", icon: "AircraftFactory.webp" },
  { id: "aluminum-59", title: "Aluminum", ru: "Aluminum", cat: "Материалы", icon: "ResouceAluminumIcon.png" },
  { id: "anti-air-gun-60", title: "Anti-Air Gun", ru: "Anti-Air Gun", cat: "Сооружения", icon: "Anti-Air_Gun.jpg" },
  { id: "a0e-9-rocket-warhead-61", title: "A0E-9 Rocket Warhead", ru: "AOE-9 ракетная боеголовка", cat: "Сооружения", icon: null },
  { id: "a0e-9-rocket-booster-62", title: "A0E-9 Rocket Booster", ru: "AOE-9 Ракетный Ускоритель", cat: "Сооружения", icon: null },
  { id: "arc-rpg-63", title: "ARC⧸RPG", ru: "ARC⧸RPG", cat: "Боеприпасы", icon: "ATMortarAmmo.webp" },
  { id: "argenti-r-ii-винтовка-64", title: "Argenti r.II Винтовка", ru: "Argenti r.II Винтовка", cat: "Оружие", icon: null },
  { id: "argenti-r-ii-rifle-65", title: "Argenti r.II Rifle", ru: "Argenti r.II Rifle", cat: "Оружие", icon: "RifleC.webp" },
  { id: "assembly-materials-ii-66", title: "Assembly Materials II", ru: "Assembly Materials II", cat: "Материалы", icon: "AssemblyMaterials2.webp" },
  { id: "assembly-materials-iii-67", title: "Assembly Materials III", ru: "Assembly Materials III", cat: "Материалы", icon: "AssemblyMaterials3.webp" },
  { id: "assembly-materials-iv-68", title: "Assembly Materials IV", ru: "Assembly Materials IV", cat: "Материалы", icon: "AssemblyMaterials4.webp" },
  { id: "assembly-materials-v-69", title: "Assembly Materials V", ru: "Assembly Materials V", cat: "Материалы", icon: "AssemblyMaterials5.webp" },
  { id: "au-a150-taurine-rigger-70", title: "AU-A150 Taurine Rigger", ru: "AU-A150 Taurine Rigger", cat: "Техника", icon: "HeavyTruckCVehicleC.webp" },
  { id: "austers-harness-71", title: "Auster's Harness", ru: "Auster's Harness", cat: "Снаряжение", icon: "ParatrooperUniformC.webp" },
  { id: "aviators-raiment-72", title: "Aviator's Raiment", ru: "Aviator's Raiment", cat: "Снаряжение", icon: "PilotUniformW.webp" },
  { id: "b2-varsi-anti-tank-grenade-73", title: "B2 Varsi Anti-Tank Grenade", ru: "B2 Varsi Anti-Tank Grenade", cat: "Оружие", icon: "ATLaunchedGrenadeW.webp" },
  { id: "balfour-falconer-250mm-74", title: "Balfour Falconer 250mm", ru: "Balfour Falconer 250mm", cat: "Техника", icon: "FieldMortarW.webp" },
  { id: "balfour-rampart-68mm-75", title: "Balfour Rampart 68mm", ru: "Balfour Rampart 68mm", cat: "Техника", icon: "FieldCannonOffensiveW.webp" },
  { id: "balfour-stockade-75mm-76", title: "Balfour Stockade 75mm", ru: "Balfour Stockade 75mm", cat: "Техника", icon: "FieldCannonHeavyW.webp" },
  { id: "bane-45-77", title: "Bane 45", ru: "Bane 45", cat: "Оружие", icon: "ATRpgC.webp" },
  { id: "bellweather-by-vac-78", title: "Bellweather by VAC", ru: "Bellweather by VAC", cat: "Техника", icon: "Mineboat.webp" },
  { id: "blackened-runestone-79", title: "Blackened Runestone", ru: "Blackened Runestone", cat: "Прочее", icon: "RunestoneSIcon.png" },
  { id: "blacksteele-80", title: "Blacksteele", ru: "Blacksteele", cat: "Техника", icon: "LargeShipDestroyerW.webp" },
  { id: "blumfield-lk205-81", title: "Blumfield LK205", ru: "Blumfield LK205", cat: "Техника", icon: "RelicBicycleVehicle.webp" },
  { id: "bms-bluefin-82", title: "BMS - Bluefin", ru: "BMS - Bluefin", cat: "Техника", icon: null },
  { id: "bms-bowhead-83", title: "BMS - Bowhead", ru: "BMS - Bowhead", cat: "Техника", icon: "LargeShipResource.webp" },
  { id: "bms-grouper-84", title: "BMS - Grouper", ru: "BMS - Grouper", cat: "Техника", icon: "Motorboat.webp" },
  { id: "bms-longhook-85", title: "BMS - Longhook", ru: "BMS - Longhook", cat: "Техника", icon: "LargeShipBaseShip.webp" },
  { id: "bms-overseer-sky-hauler-86", title: "BMS - Overseer Sky-Hauler", ru: "BMS - Overseer Sky-Hauler", cat: "Техника", icon: "LargeCrane.webp" },
  { id: "bms-scrap-hauler-87", title: "BMS - Scrap Hauler", ru: "BMS - Scrap Hauler", cat: "Техника", icon: "Harvester.webp" },
  { id: "bomastone-граната-88", title: "Bomastone Граната", ru: "Bomastone Граната", cat: "Оружие", icon: null },
  { id: "bomastone-grenade-89", title: "Bomastone Grenade", ru: "Bomastone Grenade", cat: "Оружие", icon: "GrenadeC.webp" },
  { id: "booker-greyhound-model-910-90", title: "Booker Greyhound Model 910", ru: "Booker Greyhound Model 910", cat: "Оружие", icon: "ATRifleAutomaticW.webp" },
  { id: "booker-storm-rifle-model-838-91", title: "Booker Storm Rifle Model 838", ru: "Booker Storm Rifle Model 838", cat: "Оружие", icon: "AssaultRifleHeavyWItem.webp" },
  { id: "cascadier-873-92", title: "Cascadier 873", ru: "Cascadier 873", cat: "Оружие", icon: "PistolLightW.webp" },
  { id: "catara-mo-ii-93", title: "Catara mo.II", ru: "Catara mo.II", cat: "Оружие", icon: "LightMachineGun.webp" },
  { id: "catena-rt-iv-auto-rifle-94", title: "Catena rt.IV Auto-Rifle", ru: "Catena rt.IV Auto-Rifle", cat: "Оружие", icon: "RifleAutomaticC.webp" },
  { id: "clancy-cinder-m3-95", title: "Clancy Cinder M3", ru: "Clancy Cinder M3", cat: "Оружие", icon: "RifleLongW.webp" },
  { id: "clancy-raca-m4-96", title: "Clancy-Raca M4", ru: "Clancy-Raca M4", cat: "Оружие", icon: "SniperRifle.webp" },
  { id: "coal-97", title: "Coal", ru: "Coal", cat: "Материалы", icon: "CoalIcon.webp" },
  { id: "coke-98", title: "Coke", ru: "Coke", cat: "Материалы", icon: "CokeIcon.webp" },
  { id: "concrete-materials-99", title: "Concrete Materials", ru: "Concrete Materials", cat: "Материалы", icon: "ConcreteBag.webp" },
  { id: "copper-100", title: "Copper", ru: "Copper", cat: "Материалы", icon: "ResourceCopperRefined.png" },
  { id: "crate-101", title: "Crate", ru: "Crate", cat: "Материалы", icon: null },
  { id: "critically-wounded-soldier-102", title: "Critically Wounded Soldier", ru: "Critically Wounded Soldier", cat: "Прочее", icon: "CriticallyWounded.webp" },
  { id: "crows-foot-mine-103", title: "Crow's Foot Mine", ru: "Crow's Foot Mine", cat: "Оружие", icon: "InfantryMine.webp" },
  { id: "cullen-predator-mk-iii-104", title: "Cullen Predator Mk. III", ru: "Cullen Predator Mk. III", cat: "Техника", icon: "SuperTankWVehicle.webp" },
  { id: "cutler-launcher-4-105", title: "Cutler Launcher 4", ru: "Cutler Launcher 4", cat: "Оружие", icon: "RpgW.webp" },
  { id: "bms-universal-assembly-rig-106", title: "BMS - Universal Assembly Rig", ru: "CV (тир 1)", cat: "Техника", icon: "ConstructionVehicle.webp" },
  { id: "dae-1b-2-serra-107", title: "DAE 1b-2 “Serra”", ru: "DAE 1b-2 Serra", cat: "Сооружения", icon: null },
  { id: "dae-1o-3-polybolos-108", title: "DAE 1o-3 “Polybolos”", ru: "DAE 1o-3 Polybolos", cat: "Сооружения", icon: null },
  { id: "dae-2a-1-ruptura-109", title: "DAE 2a-1 “Ruptura”", ru: "DAE 2a-1 Ruptura", cat: "Сооружения", icon: null },
  { id: "dae-3b-2-hades-net-110", title: "DAE 3b-2 “Hades' Net”", ru: "DAE 3b-2 Hades Net", cat: "Сооружения", icon: null },
  { id: "dae-5b-zeal-111", title: "DAE 5b “Zeal”", ru: "DAE 5b Zeal", cat: "Сооружения", icon: null },
  { id: "damaged-components-112", title: "Damaged Components", ru: "Damaged Components", cat: "Материалы", icon: "ComponentsDamaged.webp" },
  { id: "daucus-isg-iii-113", title: "Daucus isg.III", ru: "Daucus isg.III", cat: "Оружие", icon: "InfantrySupportGun.webp" },
  { id: "deployed-typhon-ra-xii-114", title: "Deployed “Typhon” ra.XII", ru: "Deployed “Typhon” ra.XII", cat: "Сооружения", icon: "ATRifleTC.webp" },
  { id: "devitt-ironhide-mk-iv-115", title: "Devitt Ironhide Mk. IV", ru: "Devitt Ironhide Mk. IV", cat: "Техника", icon: "LightTankWarDefensiveVehicle.webp" },
  { id: "devitt-mk-iii-116", title: "Devitt Mk. III", ru: "Devitt Mk. III", cat: "Техника", icon: "LightTankWarDefensiveVehicle.webp" },
  { id: "drummond-loscann-55c-117", title: "Drummond Loscann 55c", ru: "Drummond Loscann 55c", cat: "Техника", icon: "ScoutVehicleAmphibiousWarVehicleW.webp" },
  { id: "duncans-coin-14-5mm-118", title: "Duncan's Coin 14.5mm", ru: "Duncan's Coin 14.5mm", cat: "Техника", icon: "FieldAT2W.webp" },
  { id: "e680-s-rudder-lock-119", title: "E680-S Rudder Lock", ru: "E680-S Rudder Lock", cat: "Материалы", icon: "SeaMine.webp" },
  { id: "eleos-infantry-dagger-120", title: "Eleos Infantry Dagger", ru: "Eleos Infantry Dagger", cat: "Оружие", icon: "StilSwordC.webp" },
  { id: "fabri-rucksack-121", title: "Fabri Rucksack", ru: "Fabri Rucksack", cat: "Снаряжение", icon: "EngineerUniformC.webp" },
  { id: "facility-power-122", title: "Facility Power", ru: "Facility Power", cat: "Материалы", icon: "FilterPower.webp" },
  { id: "falias-raiding-club-123", title: "Falias Raiding Club", ru: "Falias Raiding Club", cat: "Оружие", icon: "TrenchMaceW.webp" },
  { id: "ferro-879-124", title: "Ferro 879", ru: "Ferro 879", cat: "Оружие", icon: "PistolC.webp" },
  { id: "field-range-125", title: "Field Range", ru: "Field Range", cat: "Сооружения", icon: "FirePitIcon.webp" },
  { id: "flood-juggernaut-mk-vii-126", title: "Flood Juggernaut Mk. VII", ru: "Flood Juggernaut Mk. VII", cat: "Техника", icon: "BattleTankWarDefensiveVehicle.webp" },
  { id: "flood-mk-i-127", title: "Flood Mk. I", ru: "Flood Mk. I", cat: "Техника", icon: "BattleTankWar.webp" },
  { id: "flood-mk-ix-stain-128", title: "Flood Mk. IX Stain", ru: "Flood Mk. IX Stain", cat: "Техника", icon: "BattleTankHeavyArtilleryW.webp" },
  { id: "fuscina-pi-i-129", title: "Fuscina pi.I", ru: "Fuscina pi.I", cat: "Оружие", icon: "RifleLightC.webp" },
  { id: "g40-sagittarii-130", title: "G40 “Sagittarii”", ru: "G40 “Sagittarii”", cat: "Техника", icon: "FieldMachineGun.webp" },
  { id: "ga6-cestus-131", title: "GA6 “Cestus”", ru: "GA6 “Cestus”", cat: "Техника", icon: "FieldAT2C.webp" },
  { id: "gallagher-highwayman-mk-iii-132", title: "Gallagher Highwayman Mk. III", ru: "Gallagher Highwayman Mk. III", cat: "Техника", icon: "MediumTank2MultiW.webp" },
  { id: "gallagher-outlaw-mk-ii-133", title: "Gallagher Outlaw Mk. II", ru: "Gallagher Outlaw Mk. II", cat: "Техника", icon: "MediumTank2RangeW.webp" },
  { id: "gallagher-thornfall-mk-vi-134", title: "Gallagher Thornfall Mk. VI", ru: "Gallagher Thornfall Mk. VI", cat: "Техника", icon: "MediumTank2IndirectW.webp" },
  { id: "grenadiers-baldric-135", title: "Grenadier's Baldric", ru: "Grenadier's Baldric", cat: "Оружие", icon: "GrenadeUniformC.webp" },
  { id: "h-10-pelekys-136", title: "H-10 “Pelekys”", ru: "H-10 “Pelekys”", cat: "Техника", icon: "LightTankOffensiveCVehicle.webp" },
  { id: "h-19-vulcan-137", title: "H-19 “Vulcan”", ru: "H-19 “Vulcan”", cat: "Техника", icon: "LightTankFlameC.webp" },
  { id: "h-8-kranesca-138", title: "H-8 “Kranesca”", ru: "H-8 “Kranesca”", cat: "Техника", icon: "LightTankColMobilityVehicle.webp" },
  { id: "ha-1-sagaris-139", title: "HA-1 “Sagaris”", ru: "HA-1 “Sagaris”", cat: "Техника", icon: "LightTank3CVehicle.webp" },
  { id: "hammer-140", title: "Hammer", ru: "Hammer", cat: "Снаряжение", icon: "Hammer.webp" },
  { id: "hc-2-scorpion-141", title: "HC-2 “Scorpion”", ru: "HC-2 “Scorpion”", cat: "Техника", icon: "LightTank2InfantryCVehicle.webp" },
  { id: "hc-7-ballista-142", title: "HC-7 “Ballista”", ru: "HC-7 “Ballista”", cat: "Техника", icon: "MortarTankVehicle.webp" },
  { id: "heavy-topcoat-143", title: "Heavy Topcoat", ru: "Heavy Topcoat", cat: "Снаряжение", icon: "SnowUniformC.webp" },
  { id: "hh-a-javelin-144", title: "HH-a “Javelin”", ru: "HH-a “Javelin”", cat: "Техника", icon: "HalfTrackColVehicle.webp" },
  { id: "hh-b-hoplite-145", title: "HH-b “Hoplite”", ru: "HH-b “Hoplite”", cat: "Техника", icon: "HalfTrackColHeavyArmorVehicle.webp" },
  { id: "hh-d-peltast-146", title: "HH-d “Peltast”", ru: "HH-d “Peltast”", cat: "Техника", icon: "HalfTrackArtilleryC.webp" },
  { id: "huber-exalt-150mm-147", title: "Huber Exalt 150mm", ru: "Huber Exalt 150mm", cat: "Сооружения", icon: null },
  { id: "huber-lariat-120mm-148", title: "Huber Lariat 120mm", ru: "Huber Lariat 120мм", cat: "Сооружения", icon: null },
  { id: "huber-starbreaker-94-5mm-149", title: "Huber Starbreaker 94.5mm", ru: "Huber Starbreaker 94.5", cat: "Сооружения", icon: null },
  { id: "hydras-whisper-150", title: "Hydra's Whisper", ru: "Hydra's Whisper", cat: "Материалы", icon: "Bangalore.webp" },
  { id: "ignifist-30-151", title: "Ignifist 30", ru: "Ignifist 30", cat: "Оружие", icon: "ATRPGLightC.webp" },
  { id: "infantry-battledress-152", title: "Infantry Battledress", ru: "Infantry Battledress", cat: "Снаряжение", icon: "SoldierUniformW.webp" },
  { id: "interceptor-pa-12-153", title: "Interceptor PA-12", ru: "Interceptor PA-12", cat: "Техника", icon: "LandingShipC.webp" },
  { id: "iron-154", title: "Iron", ru: "Iron", cat: "Материалы", icon: "ResouceIron.png" },
  { id: "iron-alloy-155", title: "Iron Alloy", ru: "Iron Alloy", cat: "Материалы", icon: "ResouceIronRefined.png" },
  { id: "k-81e-sombre-156", title: "K-81e “Sombre”", ru: "K-81e “Sombre”", cat: "Техника", icon: "LightBoatInfantryC.webp" },
  { id: "king-gallant-mk-ii-157", title: "King Gallant Mk. II", ru: "King Gallant Mk. II", cat: "Техника", icon: "ScoutTankOffensiveW.webp" },
  { id: "king-jester-mk-i-1-158", title: "King Jester Mk. I-1", ru: "King Jester Mk. I-1", cat: "Техника", icon: "ScoutTankMultiW.webp" },
  { id: "king-spire-mk-i-159", title: "King Spire Mk. I", ru: "King Spire Mk.1 (скаут танк)", cat: "Техника", icon: "ScoutTankW.webp" },
  { id: "klg901-2-lunaire-f-160", title: "KLG901-2 Lunaire F", ru: "KLG901-2 Lunaire F", cat: "Оружие", icon: "GrenadeLauncherC.webp" },
  { id: "krf1-750-dragonfly-161", title: "KRF1-750 Dragonfly", ru: "KRF1-750 Dragonfly", cat: "Оружие", icon: "ShotgunC.webp" },
  { id: "krn886-127-gast-machine-gun-162", title: "KRN886-127 Gast Machine Gun", ru: "KRN886-127 Gast Machine Gun", cat: "Оружие", icon: "MGC.webp" },
  { id: "krr2-790-omen-163", title: "KRR2-790 Omen", ru: "KRR2-790 Omen", cat: "Оружие", icon: "RifleLongC.webp" },
  { id: "krr3-792-auger-164", title: "KRR3-792 Auger", ru: "KRR3-792 Auger", cat: "Оружие", icon: "SniperRifleC.webp" },
  { id: "lamentum-mm-iv-165", title: "Lamentum mm.IV", ru: "Lamentum mm.IV", cat: "Боеприпасы", icon: "HeavyMachineGun.webp" },
  { id: "lance-25-hasta-166", title: "Lance-25 “Hasta”", ru: "Lance-25 “Hasta”", cat: "Техника", icon: "BattleTankATC.webp" },
  { id: "lance-36-167", title: "Lance-36", ru: "Lance-36", cat: "Техника", icon: "BattleTankC.webp" },
  { id: "lance-46-sarissa-168", title: "Lance-46 “Sarissa”", ru: "Lance-46 “Sarissa”", cat: "Техника", icon: "BattleTankHeavyArtilleryC.webp" },
  { id: "dunne-landrunner-12c-169", title: "Dunne Landrunner 12c", ru: "Landrunner", cat: "Техника", icon: "TruckMobilityWarVehicle.webp" },
  { id: "leary-aa-70-bolas-170", title: "Leary AA-70 Bolas", ru: "Leary AA-70 Bolas", cat: "Сооружения", icon: null },
  { id: "leary-shellbore-68mm-171", title: "Leary Shellbore 68mm", ru: "Leary Shellbore 68-мм", cat: "Сооружения", icon: "EmplacedAT.webp" },
  { id: "leary-snare-trap-20-172", title: "Leary Snare Trap 20", ru: "Leary Snare Trap 20", cat: "Сооружения", icon: "EmplacedMG.webp" },
  { id: "lodesmans-lorica-173", title: "Lodesman's Lorica", ru: "Lodesman's Lorica", cat: "Снаряжение", icon: "PilotUniformC.webp" },
  { id: "luminary-mk-ii-harbinger-174", title: "Luminary Mk. II Harbinger", ru: "Luminary Mk. II Harbinger", cat: "Техника", icon: "AircraftFighterWIcon.webp" },
  { id: "luminary-mk-iv-herald-175", title: "Luminary Mk. IV Herald", ru: "Luminary Mk. IV Herald", cat: "Техника", icon: "AircraftScoutWIcon.webp" },
  { id: "luminary-mk-vi-emissary-176", title: "Luminary Mk. VI Emissary", ru: "Luminary Mk. VI Emissary", cat: "Техника", icon: null },
  { id: "m925-austringer-man-o-war-177", title: "M925 Austringer Man-O-War", ru: "M925 Austringer Man-O-War", cat: "Техника", icon: "AircraftTorpedoWIcon.webp" },
  { id: "macconmara-shorerunner-178", title: "MacConmara Shorerunner", ru: "MacConmara Shorerunner", cat: "Техника", icon: "LandingShipW.webp" },
  { id: "malone-mk-2-179", title: "Malone MK.2", ru: "Malone MK.2", cat: "Оружие", icon: "MGW.webp" },
  { id: "mark-ii-raidbreaker-180", title: "Mark II Raidbreaker", ru: "Mark II Raidbreaker", cat: "Боеприпасы", icon: "AerialBombs.webp" },
  { id: "medic-fatigues-181", title: "Medic Fatigues", ru: "Medic Fatigues", cat: "Медицина", icon: "MedicUniformC.webp" },
  { id: "mercy-182", title: "Mercy", ru: "Mercy", cat: "Техника", icon: "LargeShipBattleshipAircraftW.webp" },
  { id: "mergo-4-myrmidon-183", title: "Mergo-4 “Myrmidon”", ru: "Mergo-4 “Myrmidon”", cat: "Техника", icon: "AircraftDiveC.webp" },
  { id: "model-7-evie-184", title: "Model-7 “Evie”", ru: "Model-7 “Evie”", cat: "Боеприпасы", icon: "DepthCharge.webp" },
  { id: "moray-torpedo-185", title: "Moray Torpedo", ru: "Moray Torpedo", cat: "Боеприпасы", icon: "Torpedo.webp" },
  { id: "mounted-bonesaw-mk-3-186", title: "Mounted Bonesaw MK.3", ru: "Mounted Bonesaw MK.3", cat: "Оружие", icon: "ATRPGTW.webp" },
  { id: "mounted-fissura-gd-i-187", title: "Mounted Fissura gd.I", ru: "Mounted Fissura gd.I", cat: "Оружие", icon: "GrenadeLauncherTC.webp" },
  { id: "naval-buoy-188", title: "Naval Buoy", ru: "naval buoy", cat: "Материалы", icon: "WaterWall.webp" },
  { id: "niska-mk-ii-blinder-189", title: "Niska Mk. II Blinder", ru: "Niska Mk. II Blinder", cat: "Техника", icon: "HalfTrackOffensiveWarVehicle.webp" },
  { id: "niska-mk-iii-scar-twin-190", title: "Niska Mk. III Scar Twin", ru: "Niska Mk. III Scar Twin", cat: "Техника", icon: "HalftrackTwinW.webp" },
  { id: "niska-rycker-mk-ix-skycaller-191", title: "Niska-Rycker Mk. IX Skycaller", ru: "Niska-Rycker Mk. IX Skycaller", cat: "Техника", icon: "HalftrackMultiW.webp" },
  { id: "no-2b-hawthorne-192", title: "No.2B Hawthorne", ru: "No.2B Hawthorne", cat: "Оружие", icon: "RifleShortW.webp" },
  { id: "noble-firebrand-mk-xvii-193", title: "Noble Firebrand Mk. XVII", ru: "Noble Firebrand Mk. XVII", cat: "Техника", icon: "DestroyerTankFlameW.webp" },
  { id: "noble-widow-mk-xiv-194", title: "Noble Widow MK. XIV", ru: "Noble Widow MK. XIV", cat: "Техника", icon: "DestroyerTankWVehicle.webp" },
  { id: "o-75b-ares-195", title: "O-75b “Ares”", ru: "O-75b “Ares”", cat: "Техника", icon: "SuperTankCtem.webp" },
  { id: "obrien-v-190-knave-196", title: "O'Brien V.190 Knave", ru: "O'Brien V.101 Freeman / Twin AC", cat: "Техника", icon: "ArmoredCarTwinW.webp" },
  { id: "obrien-v-110-197", title: "O'Brien V.110", ru: "O'Brien V.110", cat: "Техника", icon: "ArmoredCarWarVehicleW.webp" },
  { id: "drummond-100a-198", title: "Drummond 100a", ru: "O'Brien V.110 / Скаут", cat: "Техника", icon: "ScoutVehicleWarVehicleW.webp" },
  { id: "o-brien-v-112-199", title: "O’Brien V.112", ru: "O’Brien V.112", cat: "Техника", icon: null },
  { id: "obrien-v-113-gravekeeper-200", title: "O'Brien V.113 Gravekeeper", ru: "O'Brien V.113 Gravekeeper", cat: "Техника", icon: "ArmoredCarATWVehicleW.webp" },
  { id: "obrien-v-200-squire-201", title: "O'Brien V.200 Squire", ru: "O'Brien V.200 Squire", cat: "Техника", icon: "ArmoredCar2MultiW.webp" },
  { id: "officialis-attire-202", title: "Officialis' Attire", ru: "Officialis' Attire", cat: "Снаряжение", icon: "OfficerUniformC.webp" },
  { id: "paratroopers-ruck-203", title: "Paratrooper's Ruck", ru: "Paratrooper's Ruck", cat: "Снаряжение", icon: "ParatrooperBackpack.webp" },
  { id: "pipe-204", title: "Pipe", ru: "Pipe", cat: "Материалы", icon: "EngineRoomPipe.webp" },
  { id: "poseidon-205", title: "Poseidon", ru: "Poseidon", cat: "Техника", icon: null },
];

export const itemIconPath = (item: GeneItem | null | undefined): string | null =>
  item?.icon ? `/FoxholeWikiPhotos/${item.icon}` : null;
