// Рабочий реестр предметов Foxhole для конструктора заказов.
// Коды и названия — реальные технические имена из реестра клана SINDARIS (item_codes.py).
export type ItemCategory = "Оружие" | "Боеприпасы" | "Материалы" | "Снаряжение" | "Техника" | "Сооружения" | "Прочее";

export interface CatalogItem {
  code: string | null;
  name: string;
  en: string | null;
  category: ItemCategory;
}

export const ITEM_CATEGORIES: ItemCategory[] = ["Оружие", "Боеприпасы", "Материалы", "Снаряжение", "Техника", "Сооружения", "Прочее"];

export const ITEM_CATALOG: CatalogItem[] = [
  // Боеприпасы
  { code: "AAAmmo", name: "Зенитный снаряд 950-70b", en: "950-70b Anti-Aircraft Shell", category: "Боеприпасы" },
  { code: "ATAmmo", name: "68-мм снаряды", en: "68mm", category: "Боеприпасы" },
  { code: "ATLargeAmmo", name: "94.5мм снаряды", en: "94.5mm", category: "Боеприпасы" },
  { code: "ATRPGAmmo", name: "РПГ снаряды", en: "AT RPG Ammo", category: "Боеприпасы" },
  { code: "ATRifleAmmo", name: "14.5 мм патроны", en: "14.5mm", category: "Боеприпасы" },
  { code: "MGAmmo", name: "12.7 мм (пулемётные) патроны", en: "12.7mm", category: "Боеприпасы" },
  { code: "LightArtilleryAmmo", name: "120мм снаряды", en: "120mm", category: "Боеприпасы" },
  { code: "HeavyArtilleryAmmo", name: "150мм снаряды", en: "150mm", category: "Боеприпасы" },
  { code: "LRArtilleryAmmo", name: "300мм снаряды", en: "300mm", category: "Боеприпасы" },
  { code: "AircraftAmmo", name: "20мм (зенитные) патроны", en: "20mm", category: "Боеприпасы" },
  { code: "RifleAmmo", name: "7.62-мм патроны", en: "7.62mm", category: "Боеприпасы" },
  { code: "AssaultRifleAmmo", name: "7.92 мм патроны", en: "7.92mm", category: "Боеприпасы" },
  { code: "BattleTankAmmo", name: "75-мм снаряды", en: "75mm", category: "Боеприпасы" },
  { code: "LightTankAmmo", name: "40-мм снаряды", en: "40mm", category: "Боеприпасы" },
  { code: "HERocketAmmo", name: "Осколочно-фугасная ракета", en: "3C-High Explosive Rocket", category: "Боеприпасы" },
  { code: "FireRocketAmmo", name: "Зажигательная ракета", en: "4C-Fire Rocket", category: "Боеприпасы" },
  { code: "DepthChargeAmmo", name: "Глубинная бомба", en: "Depth Charge", category: "Боеприпасы" },
  { code: "BomberAmmo", name: "Авиабомбы", en: "Aerial Bombs", category: "Боеприпасы" },
  { code: "TorpedoAmmo", name: "Торпеда", en: "Torpedo", category: "Боеприпасы" },
  { code: "TankMine", name: "Противотанковая мина", en: "Anti-Tank Mine", category: "Боеприпасы" },
  { code: "WaterMine", name: "Морская мина", en: "Sea Mine", category: "Боеприпасы" },
  { code: "RevolverAmmo", name: ".44 Магнум", en: ".44 Mag", category: "Боеприпасы" },

  // Оружие
  { code: "ATRifleAssaultW", name: "228 Satterley Heavy Storm Rifle", en: "228 Satterley Heavy Storm Rifle", category: "Оружие" },
  { code: "ATRifleAutomaticW", name: "Booker Greyhound Model 910", en: "Booker Greyhound Model 910", category: "Оружие" },
  { code: "ATRifleLightC", name: "«Dawn» Ve.II", en: "\"Dawn\" Ve.II", category: "Оружие" },
  { code: "ATRifleSniperC", name: "«Quickhatch» Rt.I", en: "\"Quickhatch\" Rt.I", category: "Оружие" },
  { code: "ATRifleW", name: "Противотанковое ружьё Neville", en: "Neville Anti-Tank Rifle", category: "Оружие" },
  { code: "ATRPGC", name: "Venom c.II 35", en: "Venom c.II 35", category: "Оружие" },
  { code: "ATRPGHeavyC", name: "Bane 45", en: "Bane 45", category: "Оружие" },
  { code: "ATRPGLightC", name: "Ignifist 30", en: "Ignifist 30", category: "Оружие" },
  { code: "ATRPGW", name: "Противотанковый РПГ (станковый)", en: "Bonesaw MK.3", category: "Оружие" },
  { code: "ATGrenadeW", name: "Граната BF5 White Ash Flask", en: "BF5 White Ash Flask Grenade", category: "Оружие" },
  { code: "ATLaunchedGrenadeW", name: "Граната B2 Varsi", en: "B2 Varsi Anti-Tank Grenade", category: "Оружие" },
  { code: "AssaultRifleC", name: "Лёгкий пулемёт", en: "Light Machine Gun", category: "Оружие" },
  { code: "AssaultRifleW", name: "Штурмовая винтовка", en: "Assault Rifle", category: "Оружие" },
  { code: "SniperRifleW", name: "Снайперская винтовка", en: "Sniper Rifle", category: "Оружие" },
  { code: "FlameTorchC", name: "Огнемёт (колонисты)", en: "Flamethrower", category: "Оружие" },
  { code: "FlameTorchW", name: "Огнемёт (варден)", en: "Flamethrower", category: "Оружие" },
  { code: "MGC", name: "Пулемёт (станковый)", en: "Machine Gun", category: "Оружие" },
  { code: "MGTC", name: "Тяжёлый пулемёт", en: "Heavy Machine Gun", category: "Оружие" },
  { code: "SwordC", name: "Меч", en: "Sword", category: "Оружие" },
  { code: "MaceW", name: "Булава", en: "Trench Mace", category: "Оружие" },
  { code: "SatchelChargeW", name: "Взрывпакет", en: "Satchel Charge", category: "Оружие" },
  { code: "ExplosiveLightC", name: "Бангалор", en: "Bangalore", category: "Оружие" },
  { code: "ExplosiveTripod", name: "Взрывной треножник", en: "Explosive Tripod", category: "Оружие" },

  // Материалы
  { code: "Aluminum", name: "Алюминий", en: "Aluminum", category: "Материалы" },
  { code: "Components", name: "Компоненты", en: "Components", category: "Материалы" },
  { code: "Concrete", name: "Бетон", en: "Concrete", category: "Материалы" },
  { code: "Copper", name: "Медь (переработанная)", en: "Copper", category: "Материалы" },
  { code: "Coal", name: "Уголь", en: "Coal", category: "Материалы" },
  { code: "Iron", name: "Железная руда", en: "Iron", category: "Материалы" },
  { code: "IronA", name: "Железо (переработанное)", en: "Refined Iron", category: "Материалы" },
  { code: "Metal", name: "Металлолом", en: "Salvage", category: "Материалы" },
  { code: "Sulfur", name: "Сера", en: "Sulfur", category: "Материалы" },
  { code: "Wood", name: "Переработанные материалы", en: "Refined Materials", category: "Материалы" },
  { code: "RareMaterials", name: "Редкие материалы", en: "Rare Materials", category: "Материалы" },
  { code: "PipeMaterials", name: "Трубные материалы", en: "Pipe Materials", category: "Материалы" },
  { code: "Wreckage", name: "Обломки", en: "Wreckage", category: "Материалы" },
  { code: "PrototypeKit", name: "Набор прототипа", en: "Prototype Kit", category: "Материалы" },
  { code: null, name: "Базовые материалы (Bmats)", en: "Basic Materials", category: "Материалы" },
  { code: null, name: "Переработанные материалы (Rmats)", en: "Refined Materials", category: "Материалы" },
  { code: null, name: "Взрывчатые материалы (Emats)", en: "Explosive Materials", category: "Материалы" },
  { code: null, name: "Тяжёлые взрывчатые материалы (Hemats)", en: "Heavy Explosive Materials", category: "Материалы" },
  { code: null, name: "Нефть", en: "Petroleum", category: "Материалы" },
  { code: null, name: "Топливо", en: "Fuel", category: "Материалы" },
  { code: null, name: "Кокс", en: "Coke", category: "Материалы" },
  { code: null, name: "Обогащённое топливо", en: "Enriched Oil", category: "Материалы" },

  // Снаряжение
  { code: "AirSirenT", name: "Сирена воздушной тревоги", en: "Air Raid Siren", category: "Снаряжение" },
  { code: "GrenadeAdapter", name: "Гранатомётный адаптер", en: "Grenade Adapter", category: "Снаряжение" },
  { code: "WorkHammer", name: "Молот", en: "Hammer", category: "Снаряжение" },
  { code: "BannerTW", name: "Знамя", en: "Banner", category: "Снаряжение" },
  { code: "FlameBackpackC", name: "Рюкзак огнемётчика", en: "Flame Pack", category: "Снаряжение" },
  { code: "WindsockT", name: "Флюгер", en: "Windsock", category: "Снаряжение" },
  { code: "CriticalSoldier", name: "Критически ранен", en: "Critically Wounded", category: "Снаряжение" },
  { code: "WoundedCarriedPlayer", name: "Раненый (переносимый)", en: "Wounded", category: "Снаряжение" },
  { code: "SnowUniformW", name: "Зимняя форма", en: "Snow Uniform", category: "Снаряжение" },

  // Техника
  { code: "MotorcycleC", name: "03MM «Caster»", en: "03MM \"Caster\"", category: "Техника" },
  { code: "MotorcycleOffensiveC", name: "00MS «Stinger»", en: "00MS \"Stinger\"", category: "Техника" },
  { code: "Bicycle", name: "Велосипед", en: "Bicycle", category: "Техника" },
  { code: "Motorboat", name: "Моторная лодка", en: "Motorboat", category: "Техника" },
  { code: "TruckC", name: "Грузовик (колонисты)", en: "Truck", category: "Техника" },
  { code: "TruckResourceC", name: "Грузовик-платформа", en: "Resource Truck", category: "Техника" },
  { code: "TruckLiquidC", name: "Бензовоз (колонисты)", en: "Oil Tanker", category: "Техника" },
  { code: "TruckLiquidW", name: "Бензовоз (варден)", en: "Oil Tanker", category: "Техника" },
  { code: "HalfTrackC", name: "Полугусеничный БТР (колонисты)", en: "Half-Track", category: "Техника" },
  { code: "ArmoredCarC", name: "Бронеавтомобиль (колонисты)", en: "Armored Car", category: "Техника" },
  { code: "ArmoredCarOffensiveC", name: "Бронеавтомобиль наступательный", en: "Armored Car Offensive", category: "Техника" },
  { code: "LightTankW", name: "Лёгкий танк (варден)", en: "Light Tank", category: "Техника" },
  { code: "LightTank3C", name: "Лёгкий танк Mk III (колонисты)", en: "Light Tank Mk III", category: "Техника" },
  { code: "MediumTankC", name: "Средний танк (колонисты)", en: "Medium Tank", category: "Техника" },
  { code: "MediumTankOffensiveC", name: "85K-a «Spatha»", en: "85K-a \"Spatha\"", category: "Техника" },
  { code: "MediumTankW", name: "Средний танк (варден)", en: "Medium Tank", category: "Техника" },
  { code: "BattleTankW", name: "Тяжёлый танк (варден)", en: "Battle Tank", category: "Техника" },
  { code: "SuperTankC", name: "Супертанк (колонисты)", en: "Super Tank", category: "Техника" },
  { code: "SuperTankW", name: "Супертанк (варден)", en: "Super Tank", category: "Техника" },
  { code: "TanketteC", name: "Танкетка (колонисты)", en: "Tankette", category: "Техника" },
  { code: "ScoutVehicleMobilityC", name: "Разведывательная машина", en: "Scout Vehicle", category: "Техника" },
  { code: "AircraftBomberC", name: "V-1 Tzykalia (бомбардировщик)", en: "V-1 Tzykalia", category: "Техника" },
  { code: "AircraftBomberW", name: "Tulka P4 Welkinrive (бомбардировщик)", en: "Tulka P4 Welkinrive", category: "Техника" },
  { code: "AircraftFighterC", name: "Истребитель (колонисты)", en: "Fighter Aircraft", category: "Техника" },
  { code: "AircraftFighterW", name: "Истребитель (варден)", en: "Fighter Aircraft", category: "Техника" },
  { code: "AircraftScoutC", name: "Разведывательный самолёт (колонисты)", en: "Scout Aircraft", category: "Техника" },
  { code: "GunboatC", name: "Канонерская лодка (колонисты)", en: "Gunboat", category: "Техника" },
  { code: "GunboatW", name: "74b-1 Ronan Gunship", en: "74b-1 Ronan Gunship", category: "Техника" },
  { code: "LandingCraftC", name: "Десантный катер", en: "Landing Craft", category: "Техника" },
  { code: "LargeShipDestroyerW", name: "Эсминец (варден)", en: "Destroyer", category: "Техника" },
  { code: "TrainLRArtillery", name: "Железнодорожная артиллерия", en: "Train Long Range Artillery", category: "Техника" },

  // Сооружения
  { code: "AAGunAI", name: "Зенитное орудие", en: "Anti-Air Gun", category: "Сооружения" },
  { code: "AircraftDepot", name: "Ангар (депо)", en: "Aircraft Depot", category: "Сооружения" },
  { code: "AircraftFactory", name: "Ангар для авиации", en: "Aircraft Hangar", category: "Сооружения" },
  { code: "EmplacedHeavyArtilleryC", name: "50-500 «Thunderbolt» Cannon", en: "50-500 \"Thunderbolt\" Cannon", category: "Сооружения" },
  { code: "RocketSite", name: "Ракетная площадка", en: "Rocket Site", category: "Сооружения" },
  { code: "LargeCrane", name: "Большой кран", en: "Large Crane", category: "Сооружения" },
  { code: "ConcreteMixer", name: "Бетономешалка", en: "Concrete Mixer", category: "Сооружения" },
  { code: "FortGarrisonStationPart", name: "Гарнизонная станция (форт)", en: "Fort Garrison Station", category: "Сооружения" },
  { code: "FortIntelCenterPart", name: "Разведцентр (форт)", en: "Fort Intel Center", category: "Сооружения" },
  { code: "FortLRArtilleryPart", name: "Дальнобойная артиллерия (форт)", en: "Fort Storm Cannon", category: "Сооружения" },
  { code: "FortLargeRadarPart", name: "Большой радар (форт)", en: "Fort Large Radar", category: "Сооружения" },
  { code: "FortWeatherStationPart", name: "Метеостанция (форт)", en: "Fort Weather Station", category: "Сооружения" },
];
